### ISSUE TITLE
Accessibility: JAWS not reading calendar, grid & highlighting summary page correctly in the Reading/HW page in student view

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#102]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
Accessibility: JAWS not reading calendar, grid & highlighting summary page correctly in the Reading/HW page in student view

**To Reproduce**
1. calendar button not clear, says "button" and date number when we navigate using up/down arrow keys. (But says the hover text when we use tab key to navigate which I think is clear
2. grid representation of milestones says "link" 
3. highlighting summary page says "unlabeled 0 button"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
We've made quite a few changes to both the highlighting summary page and calendar grid, please retest and see if that's better

**Comment by Malar-Natarajan** [comment]
1. calendar button not clear, says "button" and date number when we navigate using up/down arrow keys. (But says the hover text when we use tab key to navigate which I think is clear
2. grid representation of milestones says "link"

These 2 issues are resolved. submitting new issue for the highlight icon
