### ISSUE TITLE
Need to analyze why importing a baked book affected existing course books when no change was made to course/catalog offering

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#103]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
Need to analyze why importing a baked book affected existing course books when no change was made to course/catalog offering.
Issue happened in QA for Physics

**To Reproduce**

**Expected behavior**
The course books should not be affected by an import unless update the catalog offering with the new imported book & set the field "Update ecosystem for associated fields" as yes

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
I can' seem to replicate this.  I'm guessing something else must have caused the behavior I saw.  @Malar-Natarajan can you please double-check this doesn't occur when you do the APUSH or other ecosystem updates?

You can test by ONLY importing a new ecosystem , then check the reference view for a course that uses the old ecosystem.  The reference view SHOULD NOT update to the new content until the offering is changed.

**Comment by Malar-Natarajan** [comment]
This is what we did in QA for the 11/20 release:

1. Imported the manifest: https://raw.githubusercontent.com/openstax/book-manifests/master/Courseware/University%20Physics/University%20Physics%20Test.yml

2. Did not update the catalog/course offering with the new baked import

3. The Physics course books had a different display in the the intro page. The objectives of all the sections were displayed in the Chapter intro page. Eg. Ch 2 had objectives from sections 2.1, 2.2, 2.3, ....2.8, 2.9...

4. We assumed importing the new manifest caused this and did not do any import in staging. So the books in staging remained as it is in production

5. For the current release (12/04), updated the course 2369 (teacher01) with the manifest imported in step 1

6. The TOC and headings are now displaying html code & <spans> for the 2369 course alone

Above said, 
i) How did the book content (especially Intro page objectives) change if the course/catalog offering was not changed (step 3 above)

ii) Now that the course 2369 has incorrect format, does it mean we imported an incorrect manifest

iii) Can we assume now that 2369 course alone has the baked book and not the other courses?


https://drive.google.com/file/d/14CgfK2gu7k8ZDqH-uolmZ55vHt7mwEMh/view?usp=sharing

**Comment by Malar-Natarajan** [comment]
@nathanstitt , my local download folder that saved the manifest has it as "University Physics....yml" 
So I am going to update another physics course with the University Physics manifest to see if that is the correct baked book.
Please hold on troubleshooting this till we see the results of the this test.

![Screen Shot 2018-11-27 at 3.53.36 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/74af50cb-a95e-4cbe-baef-5712a68f9aa9)

**Comment by Malar-Natarajan** [comment]
@nathanstitt I am moving this back to Code column. I tried updating a course with the book that I imported (University Physics)...but it wouldn't save the course ecosystem in the admin settings. 

So please investigate and let us know once a course has the correct baked book.

**Comment by Dantemss** [comment]
You cannot change a course ecosystem from Courseware physics to University Physics, you would have to make a new course.

**Comment by Malar-Natarajan** [comment]
Verified in QA
