### ISSUE TITLE
Study Brains: Speed up submit and continue buttons for reading assignments

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#105]
### Description
Submit and continue buttons currently take between 3-5 seconds to load during assignment completion for reading assignments of 3+ chapters. 

### Acceptance Criteria
- When a student loads reading assignment of 3+ chapters, the assignment loads in under 3 seconds
- When a student selects a multiple choice answer and clicks "submit", the feedback displays in under 3 seconds
- When a student clicks "continue" in a reading assignment step, the page changes in under 3 seconds. 

### High level solution
Currently, we generate about 2 mb of JSON for larger assignments. We cache the tasks to help with load times, and for larger assignments, the effect is useful: caching speeds up requests by about a 1/2 second, with a bigger effect on larger assignments. (https://openstax.slack.com/archives/C0F6Z1JUS/p1551213734189700) 

We will return only the bare minimum needed for viewing an assignment to the student:
  * Task title
  * due date
  * should feedback be shown
  * steps:
    * title
    * the content preview (this is a few sentences max)
    * type
    * is_correct (if due or immediate, same logic as before)
    * is completed

Then when the student visits each step we will load the complete details for the step, mainly the "content" which is either the page for readings, or the complete exercise for home work.

More details of the plan are in https://docs.google.com/document/d/1WYuWeOX3F6lZ8suDr8f7BjVLDCiDClOE3poIj4-5jwo/edit

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- ~If UX design is needed then the UX label is added~
- ~If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.~
- [x] A high-level solution (development approach for the code change) is added to the issue
- ~If prototype code is generated, it is linked to the issue.~
- ~If tech briefs are generated, they are linked to the issue.~

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [ ] Estimate is updated for the work item issues.
  - [x] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - ~The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.~
  - [x] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [x] The solution is updated.

2A-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
I think we may be able to drastically slim down the JSON that's returned by the BE so it only includes attributes the FE needs to know about, such as "is_complete", and "show_feedback"

If we can remove the entire exercise HTML from the payload it should load much faster

**Comment by Malar-Natarajan** [comment]
@nathanstitt 

Few issues noted in QA:
https://tutor-qa.openstax.org/course/2408/task/372461/step/1 . student08

1. skeleton message stays forever while doing a reading/HW and unable to proceed. 

2. the milestones page displays all the reading steps at the same time even if the student has not made any progress

**Comment by Malar-Natarajan** [comment]
@nathanstitt 

1. On opening a reading that is in progress, loads the 1st step instead of where the student left

2. Clicking on a card in the reading milestones is displaying the step before that...eg. If I click step 2 in milestones, step 1 is loaded

Video:
https://drive.google.com/file/d/1ay_fRccAwy5aJZxj3Fqo3y64vjtjkl5S/view?usp=sharing

3. HW assignment - Marker cards (like two step questions, individual review) are occupying the question numbers I think. Please see screenshot with missing 1 & 5 numbers. The actual assignment has only 4 questions
https://tutor-qa.openstax.org/course/2491/task/376748/step/6 . student08
https://tutor-qa.openstax.org/course/2491/metrics/38656 . teacher02

![Screen Shot 2019-04-02 at 4.30.52 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/3a4abb58-19e9-435f-b6e4-68b1bee0eb73)

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
