### ISSUE TITLE
Show students when their work was completed late on dash 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#107]
### Description
On the current student dashboard, when a student completes an assignment late, it doesn't show up as late. The score is show, regardless of whether or not the student completed some or all of the work late. 

![Screen Shot 2018-11-27 at 11.36.37 AM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/aba2fe69-1974-4e0b-8a1e-9d7f0fd14afd)
![2018-11-27_11-39-52.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/2aa459f1-b29b-42e3-80a5-e56f11906ca7)

As an OXT instructor, I want to be able to see when a student finished or last worked an assignment and I want the student's assignment (dashboard and/or student scores) to be marked as late, so that students and I are on the same page about timeliness and credit.

Considerations:
We may not want to show a timestamp on the Student Scores page, because it's pretty busy already. The export might be a better place for this, but open to ideas from UX.
It is important that we show consistency between Student scores page for instructors and students. We may already note the assignment as late on the student page, but they are more likely looking at assignments on their dashboards.
Can a student have finished an assignment on the due date but also have work done past the due date?

### Acceptance Criteria
Students can clearly see when work is late and what work they have done after the deadline
Instructors can see when a student last worked an assignment OR have a way to tell that late work was done and when it was done.
Students and instructors both come away from their dashboards with a similar understanding of the work that has been done on time and the work that is late. 

#### Distilled Acceptance Tests
**Red clock**
- Given that I am a student with a reading or homework assignment
- When that assignment's due date/time passes
- Then I see a red clock on my dashboard, next to the late assignment. The clock does not disappear when the assignment moves to past work.

**Gray clock**
- Given that I am a student with late work
- When my instructor accepts my late work
- Then the red clock next to my assignment turns gray

**Yellow exclamation mark**
- Given that I am a student with an assignment
- When my assignment is due in within 24 hours
- Then I see a yellow exclamation mark next to my assignment.

**Legend**
Red clock: Late
Gray clock: Late but accepted
Yellow exclamation: Due soon

- Given that I am a student, 
- When I log on to my dashboard and I'm on the "This Week" tab
- Then the legend with the red & gray clocks + the yellow exclamation mark appears at the bottom of the assignments "due this week" box _when assignments (due this week) are present_. If no assignments are present in the "this week" box, the legend does not appear. Clarification: Even if there are upcoming assignments, but no assignments due this week, the legend does not appear. 
.
- Given that I am a student, 
- When I log on to my dashboard and I'm on the "Past Work" tab
- Then the legend with the red & gray clocks + the yellow exclamation mark appears at the bottom of the last assignments box _when assignments are present._ 

#### Regression areas to focus on 
- Student Scores page (Instructor - orange triangle)
-  Student Dashboard and Student Scores page (student)

### Other info
**Rules for student dashboard:**
**Homework assignments**
• When a HW is not complete and due within the next 24 hours, a yellow exclamation is shown
• When a HW assignment is not yet started, a students sees “not started”
• When a HW assignment is in-progress and not yet due, a student sees how many questions he/she answered, e.g., 2 out of 12 answered
• When HW assignments is past-due and incomplete, a student sees how many questions he/she answered and a red clock (if the teacher has accepted the late work, the clock is gray). In smaller, light gray text on line 2, the student sees how many questions were complete on due date.
motivation: we want students to complete the work, even if it's late, thus, we show them progress until complete
• When a HW assignment is past-due and complete, student sees how many questions are correct, e.g, 10 out of 12 correct and a red clock (if the teacher has accepted the late work, the clock is gray) In smaller, light gray text on line 2, the student sees how many questions were complete on due date.
• When a HW assignment is past due and was complete on or before due date, the student sees how many questions are correct, e.g, 10 out of 12 correct

**Reading assignments**
• When a reading is not complete and due within the next 24 hours, a yellow exclamation is shown
• When a reading assignment is not yet started, a students sees “not started”
• When a reading assignment is in-progress and not yet due, a student sees “in progress”
• When a reading  assignment is past-due and incomplete, a student sees “in progress” with a red clock 
• When a reading assignment is past-due and complete, a student sees “complete” and a red clock (if the teacher has accepted the late work, the clock is gray)
• When a reading assignment is past due and was complete on or before due date, the student sees “complete”
• Motivation behind not showing number of steps/questions complete or scores: In readings, there is a difference between task steps and questions within the reading that count toward a score. This is potentially confusing to students, so we’ve decided to stick with showing progress indicator only. Students can see scores on their scores page OR in the actual assignment. 

Instructor email:
Hi Micaela. The specific time stamp you provided here is really helpful because it establishes that the program keeps track of details and that we know when things are submitted. For example, when I email students to explain why they didn't get credit for an assignment (I give no credit for late work), I can provide the specific time and date to establish that it was late. That would be a wonderful thing to include in the export file on a regular basis. Also, on their dashboard, some see that an assignment is "complete" when it may have been submitted late. Is there a way to clearly distinguish "complete - late" from "complete - on time" for them? I kid you not, I get dozens of emails about this sort of thing for EVERY assignment, and find it to a chore. A better label, indicating it's late, might really help. Thanks, Jim

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [x] If UX design is needed then the UX label is added
- [x] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [x] A high-level solution (development approach for the code change) is added to the issue
- [x] If prototype code is generated, it is linked to the issue.
- [x] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [x] Estimate is updated for the work item issues.
  - [x] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [x] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [x] Distilled acceptance tests are added to the issue.
  - ~Automated testing criteria are added to issue.~
  - [x] The solution is updated.

2A-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [x] The acceptance tests are finalized in "Given / When / Then" format.
  - [x] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [x] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
This seems to be working fine for me, it shows it as "Late" as it should

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/9afbf0cd-3331-4b76-ae06-bc40166b3038)

**Comment by carlycurran** [comment]
@nathanstitt, I think what happens is that when the assignment goes into the past work tab, it doesn't show the student that the work was late. So if they don't remember, they have something that shows up in conflict with what their teacher sees. I'm going to move this to design and look at it with Devika today.

**Comment by dkhowala** [comment]
This is the first pass. I will get more UX feedback but if you guys have any suggestion, please do let me know. Thanks:)

![StudentDashboard_Tutor_01112019_DK.jpg](https://images.zenhubusercontent.com/5c12c502ea8fd844ba2fce8c/59d37eb1-3317-474c-82ac-aabcf8d89bec)

**Comment by dkhowala** [comment]
We don't have to do it all. I just put everything in one page. We can decide which aspects work better and only include those.

**Comment by carlycurran** [comment]
@nathanstitt can you check to see if we have a yellow clock or exclamation mark? If something is going to be late tomorrow. 

We can leave that, but we need to add it to the legend.

**Comment by nathanstitt** [comment]
@carlycurran currently it's a yellow exclamation mark. We could easily do yellow clock though if you think that makes more sense.

**Comment by Malar-Natarajan** [comment]
@nathanstitt 
Retested in QA:
Student: https://tutor-qa.openstax.org/course/2392?tab=1  student02
Teacher01: https://tutor-qa.openstax.org/course/2392/scores . teacher01

1. Reading clock is not changing color from red to grey in student dashboard even after the teacher accepts late work (Eg. Read01, Read02)
![Screen Shot 2019-02-04 at 3.59.17 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/44d88db7-1d60-4857-a7f3-38f3fc65789a)

2. The clock color changed from red to grey in HW assignments but the score in student dashboard remains 0 (Eg. HW01, HW02 in screenshot)

![Screen Shot 2019-02-04 at 3.56.24 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/022699e1-f3ea-4914-84df-151087f3edbc)

3. Should we consider re-labelling "Due tomorrow". All these 3 readings are due today (Feb 4) at 7 pm and the legend may be confusing depending on what time the student is looking at the dashboard
![Screen Shot 2019-02-04 at 4.07.00 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/9c50c9ae-e86b-4ded-8148-6b3ea0545b81)

**Comment by dkhowala** [comment]
label option: 'Due soon' or is it too vague?

**Comment by carlycurran** [comment]
Decisions: Update "Due Tomorrow" label to "Due soon"
Look at student score update to reflect that.

**Comment by Malar-Natarajan** [comment]
@nathanstitt one more issue to this list. 

https://tutor-qa.openstax.org/course/2380/scores  teacher02
https://tutor-qa.openstax.org/course/2380?tab=0n . student05

1. HW01 was initially set to due date 02/28
2. Student had already completed partial work (before current day 2/5)
3. On 2/5, teacher changes the due date of HW01 as 2/5
4. Student dashboard is displaying red clock for HW01 which is correct
5. Should it also not display the italicized text as 4 of 6 answered on due date

![Screen Shot 2019-02-05 at 4.28.01 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/1f71d352-4e54-4752-99cf-3022374ca884)

**Comment by Malar-Natarajan** [comment]
@dkhowala @carlycurran 

I was looking at the red clock for the above scenario and kept starring at the screen for a while, since the legend said "late but not accepted" but the student did not have any work to be accepted. It took a while for me to realize that the red clock means its just late and doesn't really mean the student has late work to be accepted. 
Do you all think we should have the label for red clock as just Late?

**Comment by carlycurran** [comment]
Actually, yes, that's a great point!

**Comment by Malar-Natarajan** [comment]
additional late work  is not changing color from grey to red

**Comment by Malar-Natarajan** [comment]
Verified in staging. for issue reported on feb 5, regarding grey italicized text in the this week tab, new issue will be submitted
