### ISSUE TITLE
Help & Menu has grey background in Safari & Firefox.

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#108]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
Help & Menu has grey background in Safari & Firefox. Chrome looks ok

**To Reproduce**

**Expected behavior**
Help & Menu has grey background in Safari & Firefox

**Screenshots**
![Screen Shot 2018-11-27 at 1.52.00 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/c8bda752-e13c-4595-a828-d8173d3a445f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2435
