### ISSUE TITLE
The correct answers in QL & HW assignment history are misaligned in teacher view

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#109]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
The correct answers in QL & HW assignment history are misaligned in teacher view. Safari & Chrome have this issue

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2018-11-27 at 2.06.08 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/1919b1a6-0586-4a40-aa99-934d46c5e969)
![Screen Shot 2018-11-27 at 2.01.27 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/d55e59be-225d-47db-9846-3ccdb28e4f4d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed by https://github.com/openstax/tutor-js/pull/2435
