### ISSUE TITLE
Highlighting: Extract code to library 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#11]
# Description
Extract highlighting code to library with specs or comments to prep for Unicorn integration; modify Tutor to use extracted code

# Acceptance
Demonstrate library working in Tutor and another platform

**Comment by carlycurran** [comment]
Tom working with some feedback Phil gave him. This is in good shape.

**Comment by carlycurran** [comment]
- logic hasn't changed much -- just the way it's referenced
- working on review with Nathan and found some issues
- will be ready to merge soon -- for Friday code freeze. 
- Malar will deploy SHA to QA before code freeze if she gets it

**Comment by Malar-Natarajan** [comment]
Verified in QA
