### ISSUE TITLE
Course roster loads with no teacher/student names when the screen is opened the first time. 

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#111]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
Course roster loads with no teacher/student names when the screen is opened the first time. Navigating back and forth loads all names. 

Happens in safari & chrome. See video
https://drive.google.com/file/d/1Rce2aVcc-y9DJmhUQCKP-ItyO8ZgWWSb/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**
https://drive.google.com/file/d/1Rce2aVcc-y9DJmhUQCKP-ItyO8ZgWWSb/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2436

**Comment by Malar-Natarajan** [comment]
Verified in QA
