### ISSUE TITLE
Student Id edit icon in Course Roster page is misaligned

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#112]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
Student Id edit icon in Course Roster page is misaligned. All browsers have this issue

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2018-11-27 at 2.27.51 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/b763716b-8ee5-4f80-a243-2a1667666b4b)
![Screen Shot 2018-11-27 at 2.27.30 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/bfcf38bf-246e-47f3-b10b-913df0a491c3)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2436

**Comment by Malar-Natarajan** [comment]
Verified in QA
