### ISSUE TITLE
React upgrade: Add copied Assignment window display issues 

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#114]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
React upgrade: Add copied Assignment window display issues 
1. Open time & Due time values are overlapping with the field names
2. "Edit other assignment details" looks like plain text though its actually a link

**To Reproduce**

**Expected behavior**

**Screenshots**
Comparative screenshot of QA & staging
![Screen Shot 2018-11-27 at 4.31.38 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/3dc0d16d-1c9c-47b1-b08e-426d7110b806)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2436

**Comment by Malar-Natarajan** [comment]
Verified in QA
