### ISSUE TITLE
React upgrade: How you plan to use window shows all buttons and links like plain text (functionality works though)

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#115]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
How you plan to use window shows all buttons and links like plain text (functionality works though)
1. Why are you asking is not shown as a link in blue
2. Default button "Required as part of grade is not in orange color

On the next Thank You screen the link "back to dashboard" looks like plain text

**To Reproduce**

**Expected behavior**

**Screenshots**
https://drive.google.com/file/d/1K4In5wEmZbCirwvUTGvYqb4jLl3tPpxu/view?usp=sharing

![Screen Shot 2018-11-27 at 4.43.23 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/3883eda0-32a4-481f-931d-20fd624fa528)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2436

**Comment by Malar-Natarajan** [comment]
The issues are fixed with buttons and links in QA.

There is a green bar at the top of the page. Please see screenshot


https://drive.google.com/file/d/1NMptn6-DTqF_OKRMSeL94elYaBtzOgSH/view?usp=sharing

**Comment by Malar-Natarajan** [comment]
Verified in QA
