### ISSUE TITLE
React Upgrade: Highlight edit icon is displayed in bottom of page and not near the actual content that is highlighted

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#118]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: Highlight edit icon is displayed in bottom of page and not near the actual content that is highlighted

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2018-11-28 at 10.56.58 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/870e5507-3160-45e3-934e-dbe954ff39a9)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
Fixed in https://github.com/openstax/tutor-js/pull/2438

**Comment by Malar-Natarajan** [comment]
Verified in QA
