### ISSUE TITLE
Make Preview Course naming consistent

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#120]
### Description
Preview course names are currently inconsistent. 
![Screen Shot 2018-11-28 at 11.49.02 AM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/737db58a-259b-43f4-b225-f560c4d099cb)

### Acceptance Criteria
Remove "with Courseware" from course names

**Comment by nathanstitt** [comment]
the names come from the offering, which can be changed in course admin.
