### ISSUE TITLE
React Upgrade: Assignment creation screens retains values from previously created assignment

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#122]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: Assignment creation screens retains values from previously created assignment
Happens for both HW & Read. Please see video
https://drive.google.com/file/d/1rHBSTuACTwHqdVbMqUAGY4bZ4yZFL502/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
Fixed in https://github.com/openstax/tutor-js/pull/2440

Also could cause HW builder to crash in some readings

**Comment by Malar-Natarajan** [comment]
Verified in QA
