### ISSUE TITLE
React Upgrade: Popup window after selecting subject while creating a new course is formatted incorrectly

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#123]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: Popup window after selecting subject while creating a new course is formatted incorrectly

![Screen Shot 2018-11-28 at 3.59.26 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/d8cf19e4-3310-4813-8f4d-585347dfb998)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
Fixed in https://github.com/openstax/tutor-js/pull/2440

**Comment by Malar-Natarajan** [comment]
Verified in QA
