### ISSUE TITLE
React Upgrade: Menu options are hidden in some cases

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#124]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: Menu options are hidden in some cases

https://drive.google.com/drive/folders/1X8XUcl4p5Z2H9SXCDlQKq3dxVufpX9RN?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
Fixed in https://github.com/openstax/tutor-js/pull/2440

**Comment by Malar-Natarajan** [comment]
Verified in QA
