### ISSUE TITLE
React Upgrade: Reading view section headings are shwing "," instead of "." eg, 1,2 instead of 1.2

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#125]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: Reading view section headings are shwing "," instead of "." eg, 1,2 instead of 1.2

![Screen Shot 2018-11-29 at 10.56.27 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/3037b2ff-2d6f-4d7a-b059-4ccb2d5c237c)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
Fixed in https://github.com/openstax/tutor-js/pull/2440

**Comment by Malar-Natarajan** [comment]
Verified in QA
