### ISSUE TITLE
React Upgrade: The arrows to see next /previous month needs a double click to move on in the Teacher dashboard

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#126]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: The arrows to see next /previous month needs a double click to move on in the Teacher dashboard

https://drive.google.com/file/d/1Y3EAZs7qrpO4RdzQ-ew9AkaxBwf1jApP/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2441

**Comment by Malar-Natarajan** [comment]
Verified in QA
