### ISSUE TITLE
React Upgrade: I typed g & y in assignment name field and looks like a & v

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#127]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**

I typed g & y in assignment name field and looks like a & v

https://drive.google.com/file/d/1Rn9tlmhSy1cO8YD5oiJ3m3AgK3EpudAH/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2441

**Comment by Malar-Natarajan** [comment]
Verified in QA

**Comment by Malar-Natarajan** [comment]
Not working in staging

![Screen Shot 2018-12-05 at 4.14.39 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/9aeaba68-6cd4-4f9b-9f86-3522a881fab8)

**Comment by Malar-Natarajan** [comment]
verified in QA
