### ISSUE TITLE
React Upgrade: Individual student score review link in the Students score page is not working

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#128]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: Individual student score review link in the Students score page is not working

teacher02: https://tutor-qa.openstax.org/course/2380/task/371302/step/1

https://drive.google.com/file/d/1qxXysfOiKNXA2l2jwyCQUWQ_8VjJDTGa/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2441

**Comment by Malar-Natarajan** [comment]
Verified in QA
