### ISSUE TITLE
React upgrade: Back is looking like plain text instead of link (functionality works though) - Get Assignment link page

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#132]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
Back is looking like plain text instead of link (functionality works though) - Get Assignment link page

![Screen Shot 2018-11-30 at 12.01.54 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/0cf43574-25d6-4054-8adf-d20106eac970)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2450

**Comment by Malar-Natarajan** [comment]
Verified in QA
