### ISSUE TITLE
Error when I click "Review" link from Student scores page for an assignment that was not started by the student

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#133]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
Error when I click "Review" link from Student scores page for an assignment that was not started by the student. Clicking refresh sometimes loads the page with the right panel alone and left panel blank.
Was able to reproduce this many times for Reading & HW

![Screen Shot 2018-11-30 at 12.27.02 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/465d5037-1470-40b8-ab5f-451a54cfbdf1)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
Fixed by https://github.com/openstax/tutor-js/pull/2442

**Comment by Malar-Natarajan** [comment]
Verified in Staging
