### ISSUE TITLE
React Upgrade: "What do students see" video screen is blank in Reading assignment teacher view

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#134]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: "What do students see" video screen is blank in Reading assignment teacher view

https://tutor-qa.openstax.org/course/2377/reading/new?due_at=2018-11-30 teacher01

![Screen Shot 2018-11-30 at 11.14.52 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/3d209d80-ef55-41c5-ad3e-35bec8057a12)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
Fixed by https://github.com/openstax/tutor-js/pull/2442

**Comment by Malar-Natarajan** [comment]
Verified in qa
