### ISSUE TITLE
React Upgrade: formatting issue in HW review page..may be for MPQ

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#135]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: formatting issue in HW review page..may be for MPQ

https://tutor-qa.openstax.org/course/2379/metrics/37895 teacher02

![Screen Shot 2018-11-30 at 12.37.06 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/d91ff091-8854-4abc-8bcb-2cb43a51bed7)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2450

**Comment by Malar-Natarajan** [comment]
Verified in QA
