### ISSUE TITLE
React Upgrade: styling issue in reading only

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#136]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: styling issue in reading only

https://tutor-qa.openstax.org/course/2379/task/371305 student05

![Screen Shot 2018-11-30 at 12.46.52 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/7d9656b0-0bb3-4b02-b057-21bb128ff144)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
I'm pretty sure this isn't a regression, it's specific to this content only.

It'll affect any time a vertical image is followed by a

**Comment by brittany-johnson** [comment]
@carlycurran Looking good on QA!
![Screen Shot 2019-01-16 at 10.40.03 AM.png](https://images.zenhubusercontent.com/5b0d6efdd59b032fbd122962/fcddd5df-f5d3-4d36-a435-bb530e7f5192)
