### ISSUE TITLE
React Upgrade: Browse this chapter is not shown as link in assignment builder page for Read & HW

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#137]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: Browse this chapter is not shown as link in assignment builder page for Read & HW

![Screen Shot 2018-11-30 at 1.28.14 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/bf3dbb8c-36b5-4424-9c36-71a809ac508e)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2443

**Comment by Malar-Natarajan** [comment]
Verified in Staging
