### ISSUE TITLE
React Upgrade:  If I click in the top part of the day in teacher dashboard, "cannot assign to past day" is displayed. But if I click below the Read02 I can create assignment

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#138]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_
 If I click in the top part especially above Read02, "cannot assign to past day" is displayed. But if I click below the Read02 I can create assignment

![Screen Shot 2018-11-30 at 1.32.08 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/6be8c724-c0b4-4363-a474-a3c9568c27bb)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
Fixed by https://github.com/openstax/tutor-js/pull/2442

**Comment by Malar-Natarajan** [comment]
Verified in QA
