### ISSUE TITLE
React Upgrade: Question number is not in the beginning when images are present in the exercise

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#139]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: Question number is not in the beginning when images are present in the exercise
https://tutor-qa.openstax.org/course/2379/task/371309/step/7 student05

![Screen Shot 2018-11-30 at 1.50.16 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/3c32077e-5bcd-4c96-8e99-f4fe76c81f2a)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
I believe this is probably a content issue, and is because they have the image appearing first, without any text before it
