### ISSUE TITLE
React Upgrade: View HW assignment page has the exercise count bar at the top hiding the assignment name instead of above the exercise questions 

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#140]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: View HW assignment page has the exercise count bar at the top hiding the assignment name instead of above the exercise questions
Happens in safari & chrome. See video

https://drive.google.com/file/d/1b4-SgZTYNTEiYSQwgz679E2vGGJOPBHj/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2443

**Comment by nathanstitt** [comment]
fixed in: https://github.com/openstax/tutor-js/pull/2443

**Comment by Malar-Natarajan** [comment]
Verified in Staging
