### ISSUE TITLE
React Upgrade: Page tips not showing for new instructor

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#141]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: Page tips not showing for new instructor

https://drive.google.com/file/d/1TXKvZBJUmXX1W8cavpWRY67qhVuejhVL/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
Fixed in https://github.com/openstax/tutor-js/pull/2443

**Comment by Malar-Natarajan** [comment]
Verified in Staging
