### ISSUE TITLE
React Upgrade: Privacy statement is top aligned and Create course button (while viewing preview courses) is also slightly top aligned

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#142]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: Privacy statement is top aligned and Create course button (while viewing preview courses) is also slightly top aligned

https://drive.google.com/open?id=1TXKvZBJUmXX1W8cavpWRY67qhVuejhVL

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
Fixed by https://github.com/openstax/tutor-js/pull/2443

**Comment by Malar-Natarajan** [comment]
Verified in Staging
