### ISSUE TITLE
Error 422 displayed in Reading assignment when we hit the back arrow and then click Continue button

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#146]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
Error 422 displayed in Reading assignment when we hit the back arrow and then click Continue button

**To Reproduce**
Error 422 displayed in Reading assignment when we hit the back arrow and then click Continue button

See video for steps.
https://tutor-qa.openstax.org/course/2390/task/372151/step/1 teacher02

https://drive.google.com/file/d/1kiTN7hDEXoEq51dKkSy_paFxQMEluOL3/view?usp=sharing

![Screen Shot 2018-12-03 at 2.30.00 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/fbd5cbc6-21d7-4b3e-82a9-a71879337997)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
Fixed in https://github.com/openstax/tutor-js/pull/2443

**Comment by Malar-Natarajan** [comment]
Verified in Staging
