### ISSUE TITLE
the sort options in scores/progress is not sorting the course averages which leads to incorrect values in the course averages

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#150]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
the sort options in scores/progress is not sorting the course averages which leads to incorrect values in the course averages.

Please see video.

https://drive.google.com/file/d/1_VgKPE54SoV4eOvz857YfnZs0f7F9XHa/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gregfitch** [comment]
Still happens:

https://drive.google.com/file/d/1Ddz9HkebpiFZLC1gU7AzprcVpvABAVJH/view?usp=sharing

**Comment by gregfitch** [comment]
Verified on QA
