### ISSUE TITLE
Continue & Add it Later in "Add student Id" window does the same thing

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#151]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
Continue & Add it Later in "Add student Id" window does the same thing.
If I leave the student Id blank and hit COntinue, the dashboard is displayed
If I leave the student Id blank and hit Add it later, the dashboard is displayed

Need clarity on the buttons in the screen 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
this was "by design" UX felt that cancel was to generic so they needed a way to explicitly know they could add it later, but also felt that every modal should have a cancel button...
