### ISSUE TITLE
Exercise React Upgrade: This exercise has  lot of repetitions in exercise parameters in QA vs staging. Please check if its a data issue or bug

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#154]
**Describe the bug**
Exercise React Upgrade: This exercise has  lot of repetitions in exercise parameters in QA vs staging. Please check if its a data issue or bug. 

https://drive.google.com/open?id=1Q9NN2sHHKb8Ug1vFYmhqQm_7i-EmQj1u

Another eg. 1759

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
in this case, it's actually staging (pre upgrade code) that has the bug.  Exercise editing should show all tags, but the old code was using the "only important tags" filter. That's the filter that is supposed to only be used in Tutor, not exercises

**Comment by gregfitch** [comment]
deferred until Staging is deployed...

**Comment by gregfitch** [comment]
All tags are being displayed on Staging, but I don't see an assessment with as many CNX modules as the one mentioned above.
