### ISSUE TITLE
Exercise React Upgrade: Add new distractor link is missing styling

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#156]
**Describe the bug**
Exercise React Upgrade: Add new distractor link is missing styling

![Screen Shot 2018-12-06 at 3.09.16 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/04e5ac62-d156-45c1-892a-6b963673f132)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2467

**Comment by gregfitch** [comment]
verified on QA
