### ISSUE TITLE
Exercises React Upgrade: Distractors numbering are not formatted properly

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#157]
**Describe the bug**
Exercises React Upgrade: Distractors numbering are not formatted properly

![Screen Shot 2018-12-06 at 3.12.29 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/599b1086-83db-41fe-b1a2-9df0b0cc609f)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2451

**Comment by gregfitch** [comment]
verified on QA
