### ISSUE TITLE
Exercises: Choose different image is invisible if the selected image has dark background

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#159]
**Describe the bug**
Exercises: Choose different image is invisible if the selected image has dark background

![Screen Shot 2018-12-06 at 3.32.01 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/60334959-b934-48df-936a-75b6fa09c4db)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gregfitch** [comment]
Verified on QA
