### ISSUE TITLE
Exercises React Upgrade: Read Only panel is misaligned

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#161]
_For a BUG include these headings:_

**Describe the bug**
Exercises React Upgrade: Read Only panel is misaligned

![Screen Shot 2018-12-10 at 10.44.30 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/87fd28da-2a89-405a-ab6b-36bf2c41c6bd)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gregfitch** [comment]
Verified on QA
