### ISSUE TITLE
Exercises React Upgrade: Issues with distractor icons after upgrade

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#163]
**Describe the bug**
Exercises React Upgrade: Issues with distractor icons after upgrade

1. The order of icons is different compared to staging. The right answer icon is the first in staging whereas the delete icon is the first in QA. 
2. The icon coloring is different compared to staging
3. Too much space between the icons

![Screen Shot 2018-12-10 at 11.32.47 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/e492439a-fd9d-490f-864e-0a5898dcff94)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gregfitch** [comment]
Verified on QA, spacing accepted

![Screen Shot 2019-01-09 at 10.41.11 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/1b8d90af-cf32-4041-b67f-252e0c5e8c02)
