### ISSUE TITLE
Note icon not showing up for some highlights

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#164]
**Describe the bug**
Note icon is showing up for some notes, but not for others. 
Tutor-QA
Student01
Physics 

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2018-12-11 at 9.46.28 AM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/1d293987-4573-4e3d-974d-4c2ee8a409a0)

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2454

**Comment by nathanstitt** [comment]
fixed by: https://github.com/openstax/tutor-js/pull/2454

**Comment by gregfitch** [comment]
can't reproduce; accepting
