### ISSUE TITLE
Slow Migration during 12/06 deployment 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#165]
**Describe the bug**
Migration in BL migration is running too slowly to make it through deployment

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
slow migration step removed in https://github.com/openstax/biglearn-scheduler/pull/74
