### ISSUE TITLE
Figure links in reading assignments (baked books) showing different figure numbers

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#166]
**Describe the bug**
Figure links in reading assignments showing different figure numbers

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screen Shot 2018-12-12 at 1.19.03 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/93e3281c-446d-44f8-8b9f-81e9dc888d9f)

**Comment by nathanstitt** [comment]
fixed by: https://github.com/openstax/tutor-js/pull/2456

**Comment by gregfitch** [comment]
Verified on QA
