### ISSUE TITLE
Baked books: Some Vertical images has floating text in reference view

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#168]
_For a BUG include these headings:_

**Describe the bug**
Baked books: Some Vertical images has floating text in reference view

![Screen Shot 2018-12-12 at 10.46.57 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/f9e145cf-2046-4ac1-b028-e39ba8fc8266)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brittany-johnson** [comment]
![Screen Shot 2018-12-14 at 12.29.54 AM.png](https://images.zenhubusercontent.com/5b0d6efdd59b032fbd122962/0b208fbb-407e-4830-a2b9-d41ffeac4470)

![Screen Shot 2018-12-14 at 12.30.01 AM.png](https://images.zenhubusercontent.com/5b0d6efdd59b032fbd122962/a1691e5c-8f7c-44a8-966e-c5fe44ba982c)

**Comment by brittany-johnson** [comment]
Addressed in PR https://github.com/openstax/tutor-js/pull/2455

**Comment by gregfitch** [comment]
verified on QA
