### ISSUE TITLE
Baked Books: Equation numbering positions are not matching cnx.org

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#169]
**Describe the bug**
Baked Books: Equation numbering are not matching cnx.org.
1. I see them in cnx.org in the right side as a small label but in tutor its bolded and left sided confusing with regular numbering. 
2. Also the numbers are not exactly pointing to the equation in many cases

This is sec 1.4 in Physics

![Screen Shot 2018-12-12 at 4.14.52 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/9f25d7da-2bd2-48da-bdc0-2e3ee1aee9f7)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
Fixed in https://github.com/openstax/tutor-js/pull/2452

**Comment by Malar-Natarajan** [comment]
Verified in staging
