### ISSUE TITLE
Baked Books: Section numbers in the EOC questions are missing in tutor reference view

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#170]
_For a BUG include these headings:_

**Describe the bug**
Baked Books: Section numbers in the EOC questions are missing in tutor reference view. See screenshot of tutor vs. CNX

https://drive.google.com/file/d/1-FlRjI0JsK9WnVEf2YhX0zYgqmgb2hqk/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brittany-johnson** [comment]
addressed in https://github.com/openstax/tutor-js/pull/2455

**Comment by gregfitch** [comment]
verified on QA
