### ISSUE TITLE
Baked books: Some EOC questions with images are overlapping

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#171]
**Describe the bug**
Baked books: Some EOC questions with images are overlapping

Screenshot is from section 4. Question 42 & 43 are overlapping images & text and confusing

![Screen Shot 2018-12-12 at 3.32.48 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/cc2752ce-5b51-4975-94fb-572c18340aca)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brittany-johnson** [comment]
![Screen Shot 2018-12-14 at 12.18.22 AM.png](https://images.zenhubusercontent.com/5b0d6efdd59b032fbd122962/d28f2622-6a4e-4e17-b5a3-9aa18f696fb1)

**Comment by gregfitch** [comment]
verified on QA
