### ISSUE TITLE
highlight icon is now displaying a bit out of position

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#175]
_For a BUG include these headings:_

**Describe the bug**
highlight icon is now displaying a bit out of position.

From Nathan: It’s caused by the page not being scrolled to the top when it loads.  if that’s the case then everythings offset by the amount you’re scrolled down.  Is not browser specific

https://drive.google.com/file/d/1TTPOIEJ7Gf_am3axL5Y_QlwtXUxkFShl/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed by: https://github.com/openstax/tutor-js/pull/2454

**Comment by gregfitch** [comment]
icon 'settles' a bit below where it initially resides after navigating away from the book page and then back

![Screen Shot 2019-01-07 at 1.31.49 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/362c1d7f-fdee-4b20-a5ac-11129d03fc04)
![Screen Shot 2019-01-07 at 1.34.37 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/70ca152a-df6a-46e3-a92c-9bc1899b3298)

**Comment by gregfitch** [comment]
accepted, bug card filed for the annotation icon under full-width text
