### ISSUE TITLE
Make "set weights" appear as a link

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#176]
**Describe the bug**
"set weights" doesn't look like a link. This is on prod. I think it's a byproduct of the REACT upgrade.

**Screenshots**
![Screen Shot 2018-12-13 at 4.14.33 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/7235bb36-5caa-48a3-8611-74ebdcd34236)

**Comment by gregfitch** [comment]
Verified on QA
