### ISSUE TITLE
Baked books - Reading milestones are showing paragraph titles instead of section heading

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#178]
_For a BUG include these headings:_

**Describe the bug**
Baked books - Reading milestones are showing paragraph titles instead of section heading

![Screen Shot 2018-12-12 at 2.35.23 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/563f50e9-c93a-4b55-ad72-78e95ee62a20)![Screen Shot 2018-12-12 at 2.35.23 PM.png]

![Screen Shot 2018-12-12 at 2.35.16 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/66c1c43a-6925-49c7-a96a-601dfa4ec2ce)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed by https://github.com/openstax/tutor-js/pull/2456

**Comment by gregfitch** [comment]
Some are correct, some are not:

![Screen Shot 2019-01-08 at 1.44.53 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/9d5472dc-2a7d-43c5-92d6-27edbeccbdc3)

![Screen Shot 2019-01-08 at 1.45.00 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/de24873c-2b6b-4b76-810f-cbb3237c6f91)

**Comment by Malar-Natarajan** [comment]
Verified in QA
