### ISSUE TITLE
Baked books: Sims are showing as links in reading/reference view and on clicking opens in a new tab

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#179]
**Describe the bug**
Baked books: Sims are showing as links in reading/reference view and on clicking opens in a new tab

Reference view

![Screen Shot 2018-12-14 at 10.31.20 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/412856e8-4a9f-44b6-888e-44dd2986683e)

Reading view 
https://drive.google.com/file/d/1E_vyjvegDMKl54bQWXvYZAvujtJTUu7O/view?usp=sharing

CNX

![Screen Shot 2018-12-14 at 10.33.48 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/823ab12d-b6f5-42cb-9a86-66d1d492405d)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed by: https://github.com/openstax/tutor-server/pull/1825

**Comment by gregfitch** [comment]
shows the placeholder, links to the sims on Archive
