### ISSUE TITLE
React Upgrade: Cancel button in Delete modal - Highlights & notes page is orange by default vs. before upgrade where Cancel button is grey

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#180]
**Describe the bug**
Cancel button in Delete modal -> Highlights & notes page is orange after upgrade vs. before upgrade where Cancel button is grey

![Screen Shot 2018-12-14 at 12.43.15 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/73f1acf4-c326-4e2c-a3d2-82c54a0bb882)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gregfitch** [comment]
icons are offset in their boxes on Firefox

![Screen Shot 2019-01-09 at 10.50.19 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/3df98ee7-193c-47ab-ae4f-e2578cfdf191)

**Comment by Malar-Natarajan** [comment]
Verified in QA
