### ISSUE TITLE
React Upgrade: Visual issues with performance forecast screen from Teacher's view

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#181]
_For a BUG include these headings:_

**Describe the bug**
React Upgrade: Visual issues with performance forecast screen from Teacher's view

1. The dropdown in the name displays another student's name

2. The info button content is overflowing

![Screen Shot 2018-12-14 at 1.49.25 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/7a86fc2a-887b-46c2-a81f-3847cd5ff808)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gregfitch** [comment]
Verified on QA
