### ISSUE TITLE
In reference view (safari & chrome) the page gets an error especially when I navigate from SIMS

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#183]
_For a BUG include these headings:_

**Describe the bug**
In reference view (safari & chrome) the page gets an error especially when I navigate from SIMS.

As per Nathan, "it looks like there’s some sort of bug going on with cnx archive that’s intermittently triggering safari and causing the sim to fail to load.  i’m debugging it now but it’s not on our end"

"occasionally it fails to load the JS files for the sim.  But other times it works fine, which makes me think that archive may have a server that’s not acting right and causes errors if you happen to get that one.  I posted in #cnx  we’ll see what they say"

https://drive.google.com/file/d/1v0d1slbUeeu_SxkG24dnQQtKzgSxTAzO/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
I think this was fixed by the work on the https redirects. I can't seem to trigger it at least.

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
