### ISSUE TITLE
Some SIMS open as jar file and not in Iframes

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#184]
**Describe the bug**
Some SIMS open as jar file and not in Iframes
Eg. sec 11.3 physics

(Note: I am seeing most of the SIMS working now in both reference & reading, may be CNX did something...IDK)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by carlycurran** [comment]
we've excluded sims that open in .jar files
