### ISSUE TITLE
React Upgrade: when there are more number of assignments on a particular row in teacher dashboard, the remaining rows shrink a bit to adjust the table size

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#190]
_For a BUG include these headings:_

**Describe the bug**
React Upgrade: when there are more number of assignments on a particular row in teacher dashboard, the remaining rows shrink a bit to adjust the table size

https://tutor.openstax.org/course/4805/t/month/2018-12-18 . Hansolo

![Screen Shot 2018-12-18 at 10.04.44 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/dce2d538-31dd-4e9e-b79a-3d99fbc910f9)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed by: https://github.com/openstax/tutor-js/pull/2470

**Comment by gregfitch** [comment]
Are we expecting all of the cells to grow to maintain the aspect ratio of the most cluttered assignment day?

![Screen Shot 2019-01-09 at 10.14.45 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/d34fce5b-408e-48f2-88fa-6bd051f49f38)
