### ISSUE TITLE
Task placeholders are deleted after student starts the assignment which leads to incorrect values

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#191]
**Describe the bug**
Task placeholders are deleted after student starts the assignment which leads to incorrect values

**To Reproduce**
1. Create new assignment with many steps
2. Student 1 completes the entire assignment
3. Student 2 completes partial assignment
4. Student 3 does not start the assignment
5. Download the export after due date

https://tutor-staging.openstax.org/course/4074/scores  teacher01

Read05 Total possible in export (cell O15) shows 68 but if u hover over the circle for Dorthe Read05 it shows 67 and its 100% complete. 

Read06 - Gil 7 of 26, suresh & dorthy shows 0 of 29

**Expected behavior**
Students score should not differ between students and the export

**Screenshots**
https://drive.google.com/file/d/1yerYfnjK7EG8x64HUrG8oxPzv_CV7JiP/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
This seems to happen because:
  * When an assignment is created it contains placeholder steps for personalized exercises
  * The placeholders steps are replaced by real exercises suggested by BL when the student clicks the assignment from their dashboard
  * If BL cannot suggest enough exercises, the placeholder steps are removed
    * Some sections of content have very few exercises tagged as reading.  Physics chapter 30, section 9 has only a single exercise.
 * If placeholder steps are removed, students who did not open the exercise will appear to have more steps than other students

**Comment by carlycurran** [comment]
This should be fixed through Nathan's task steps work!!! Woohoo

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
