### ISSUE TITLE
Study Brains: Certain Free Response populates after its question

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#192]
**Describe the bug**
Study Brains: Certain FR populates after its question

**To Reproduce**
1. Create a course and add it to the study brain and activate it.
2. Enroll two students and create a read assignment within chapter 1 - 3
3. Student 1 is in cohort A and student 2 is in cohort B
4. Student 1 starts the assignment, first section questions do not have FR and next 3 questions did get  the FR which worked good
5. Student 2 starts the assignment. First section questions did get an FR which is correct.
The 2nd section is not supposed to get FR. But the question is displayed first and on clicking submit button the FR box is displayed which is not correct.

https://tutor-qa.openstax.org/course/2392/task/372191/step/18 . student02

Please see video.
https://drive.google.com/file/d/1cEglYKRY8q8ArJLAfQHs13dRhB9F6GOW/view?usp=sharing

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
@Malar-Natarajan I'm completely unable to replicate this.  Can you please retest with the lastest code and see if you can re-create it?  If you can, maybe it's something to do with the assignment, so let me know exactly what sections you selected.

Thanks

**Comment by nathanstitt** [comment]
I tested this on QA with course id 2392

I adding an assignment https://tutor-qa.openstax.org/course/2392/homework/38129 with 3 questions from each section of chapter 1.

Worked it as student01 who's in cohort A, and saw all odd sections (1.1, 1.3) did not have FR, but even (1.2, 1.4) did.

Worked it as student02 who's in cohort B, and saw all even sections lacked FR, but odd had it.

The course has student05 in corhort A, and student06 in B left to test with.

**Comment by carlycurran** [comment]
testing this issue is currently blocked by: https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/105

We're hoping that the work done above will mitigate this bug.

**Comment by carlycurran** [comment]
@nathanstitt @Brooke-Fail @Malar-Natarajan 

I'm moving this out of blocked, because I think we have resolved this issue with the update task steps! 

Let's test it again to be sure :)

**Comment by meeragovindaraju** [comment]
After talking to Nathan, I am closing this issue. We are waiting on @reedstrm for the next steps.
