### ISSUE TITLE
If we hit Back and modify a subject while creating new course the options button do not work to select a different subject

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#193]
**Describe the bug**
If we hit Back and modify a subject while creating new course the options button do not work to select a different subject

See video

https://drive.google.com/file/d/1FX2suDdqzzx3x0vQM-ARiL1W0fUWs7mt/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gregfitch** [comment]
behavior: closes the new course flow and returns the user to their previous screen (course or dashboard)
Accepted
