### ISSUE TITLE
Investigate Error: Right side of assignment cannot be destructured

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#194]
**Describe the bug**

I ran into a problem at https://tutor.openstax.org/course/4872/t/month/2019-01-01 while using browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15.

The request details are:
undefinedThe request body was:
{
"error": "TypeError: Right side of assignment cannot be destructured"
}.
Case #29030

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2477

**Comment by nathanstitt** [comment]
This seems to happen when loading the student dashboard for a course with a different timezone that the user's browser.  The dashboard does load fine, it just logs an error

**Comment by Malar-Natarajan** [comment]
No error received for student using a browser in a different timezone than the course time zone
