### ISSUE TITLE
Get garbage detection running as a flask service

### ISSUE THREAD

**Issue by BruceP99166** [openstax/tutor#199]
# Description
Get garbage detection running as a flask service

# Acceptance
Code runs locally and performs generic garbage detection from a web request.

## Distilled acceptance tests
- Given that a local Tutor installation is running
- When a developer issues a request 
- Then the garbage detection alg replies accurately

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- ~A high-level solution (development approach for the code change) is added to the issue~
- ~If prototype code is generated, it is linked to the issue.~
- ~If tech briefs are generated, they are linked to the issue.~

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [x] Estimate is updated for the work item issues.
  - [x] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - ~The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.~
  - [x] Distilled acceptance tests are added to the issue.
  - ~Automated testing criteria are added to issue.~
  - ~The solution is updated.~

2A-CODE
  - [x] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [x] The acceptance tests are finalized in "Given / When / Then" format.
  - ~Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.~

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

**Comment by nathanstitt** [comment]
I opened https://trello.com/c/nOzSzSX4/199-provision-server-for-garbage-detection on devops board so they can start provisioning servers.

**Comment by carlycurran** [comment]
@nathanstitt does anyone need to review this? (Karina?) Or do you want to move to done?

**Comment by meeragovindaraju** [comment]
After talking to Nathan, I am closing this issue. Regression tests will be done next release after the staging server is up and running.
