### ISSUE TITLE
Intervene when gibberish detected

### ISSUE THREAD

**Issue by BruceP99166** [openstax/tutor#203]
# Description
As OpenStax, I want to intervene when a student submits a gibberish answer, so that I can get that student to practice retrieving knowledge from memory or look up an answer -- in hopes of driving better engagement and learning.

# Acceptance
- Students who input a gibberish free response, get an intervention 
- Students who input in a correct answer do not get an intervention (90% of the time)
- We've tested and selected various prompts (the “ask”) to find the language that resonates most with students

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [x] If UX design is needed then the UX label is added
- [x] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
  - [ ] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [ ] Estimate is updated for the work item issues.
  - [x] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [x] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2A-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by BruceP99166** [comment]
Q1 planning estimate: 34 points
21 - UX design (13 for lo-fi, 5 for mid-fi, 3 for lo-fi)
13 - Code UX solution (stretch for this quarter)

**Comment by dkhowala** [comment]
redlining doc link:

**Comment by dkhowala** [comment]
UX review link: https://invis.io/AHRCTM52PBU

**Comment by Malar-Natarajan** [comment]
@nathanstitt 

reopening this card based on Devika's UX review above

**Comment by dkhowala** [comment]
@nathanstitt : 

Here are the final error messages: 

1. Take another chance
Rewrite your answer after reviewing section <title> OR Submit this answer

2. Not sure? Here’s a hint
This question comes from section <link>. Review and rewrite OR Submit this answer

3. Try again
Take your time. Rewrite your answer after reviewing section <title> OR Submit this answer

4. Give it another shot
Answer in your own words to improve your learning. Review section <link> OR Submit this answer

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by meeragovindaraju** [comment]
After talking to Nathan, I am closing this issue. Regression tests will be done next release after the staging server is up and running.
