### ISSUE TITLE
column marks are partially missing in the student grade averages

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#215]
# Scenario 

Some of the column markers aren't the full height of the table cells.

![Screen Shot 2019-01-09 at 9.53.03 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/4e2aa742-26f5-437c-9288-f640ea5e0652)

# Environment

QA, teacher, student scores

**Comment by Malar-Natarajan** [comment]
Verified in QA
