### ISSUE TITLE
T3.research.23 - Study panic button!

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#22]
# Description

As a researcher, I want to be able to turn off a study mid-stream in case things go bad.

- T3.04.Mip.02 (in old epic doc)
- Initial hours estimate: (8/12/16)
- Envision the following scenario: something starts going bad in a course related to study manipulations, teachers, and students freak out, the word "showstopper" gets tossed around but a quick fix isn't feasible, so researchers hit a scary "kill this study" button.
- Because this is a rather dramatic action, require one researcher and one admin to hit the button before the kill action is taken. (like this: https://goo.gl/khXI6t but not like this: https://goo.gl/mGgSzN and https://goo.gl/Kpstta)
- Prevents any future manipulations from happening, defaults all behavior back to Tutor standard practice.

# Acceptance

# Epic Doc

https://docs.google.com/document/d/1E2CzBNf__8O-pvpzaomUbwzndyCjJM95h3oYzda-d6g/edit#heading=h.auws0ehqcuww

**Comment by nathanstitt** [comment]
this is done, we decided not to add an explicit "panic" button, but instead allow each study to be de-activated and re-activated
