### ISSUE TITLE
Assignment status is not updating on the student dashboard

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#223]
# Scenario 

students completing assignments aren't being shown their status until the page is reloaded; clicking the finish / return to dashboard button at the end of an assignment is not sufficient 

after finishing the reading
![Screen Shot 2019-01-11 at 11.29.46 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/14e76cf9-9d27-499e-8d39-5581c1aec982)

![Screen Shot 2019-01-11 at 11.29.58 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/decf0a9a-3684-470e-8522-a6132af2f209)

after reloading the dashboard
![Screen Shot 2019-01-11 at 11.30.15 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/6570ff1b-18fb-47bc-af25-d0d773601495)

after completing the homework![Screen Shot 2019-01-11 at 11.31.38 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/b1fe3468-c0ad-4e12-9bc7-d935fc37b625)

![Screen Shot 2019-01-11 at 11.31.28 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/de69f987-e8b3-47c5-b052-681e877d1b1c)

after reloading the dashboard and then clicking the external assignment link
![Screen Shot 2019-01-11 at 11.31.48 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/c9ad3882-fc9b-40f2-be42-6f4ed8e6a68b)

final page reload
![Screen Shot 2019-01-11 at 11.32.12 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/18a2efc7-c59f-429d-8519-6d2e4b696827)

# Environment

Staging, newly registered student, baked Bio, current semester
https://tutor-staging.openstax.org/course/4079
gvo8ax+ct873opxjt39g@sharklasers.com

**Comment by gregfitch** [comment]
If the student uses the Menu > Dashboard link, the assignment statuses don't update.

If the student clicks on the OpenStax Tutor Beta home logo, the assignment statuses do update

**Comment by Malar-Natarajan** [comment]
Verified in QA
