### ISSUE TITLE
External assignment loads when trying to remove it after a teacher withdraws the assignment

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#224]
# Scenario 

When trying to remove a withdrawn external assignment, the assignment screen loads after confirming removal. When the student returns to the dashboard, the assignment is gone.

https://drive.google.com/file/d/1bnz7eXCsTO2yrRSJ47Td4cwvkRL5qiCo/view?usp=sharing

# Environment

Staging, student with a withdrawn external assignment

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by Brooke-Fail** [comment]
Verified in Production.
