### ISSUE TITLE
selecting a letter for an assessment multi-choice doesn't select the intended answer

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#227]
# Scenario 

Selecting a letter for an assessment answer is off by one

if you use numbers you get:
1 => a
2 => b
...

if you use letters you get:
a => no answer selected
b => a
c => b
...

# Environment

Staging, student, readings and homeworks

### Checklist for Done
2-CODE
  - [x] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [x] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by Malar-Natarajan** [comment]
@brittany-johnson 
Works good in QA.

Just have this question. The issue description at the top of this card says:

"if you use numbers you get:
1 => a
2 => b"

but now in QA it is like:
0 => 1
1 => b

Is there any specific requirement that has to be followed for accessibility while configuring these keystrokes?

**Comment by brittany-johnson** [comment]
@Malar-Natarajan Ah! Thank you for pointing this out, I only addressed half of the issue (the letters and not the numbers) I'll look into this again

**Comment by Malar-Natarajan** [comment]
Verified in QA

**Comment by Malar-Natarajan** [comment]
Verified in staging
