### ISSUE TITLE
Teacher can archive a section that still has students

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#229]
# Description 

Teachers are not supposed to be able to archive ('Delete Section') a course section with students.

Students in the archived section are presented an error:

![Screen Shot 2019-01-14 at 1.22.11 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/81e1cffe-c5b6-4723-ad2b-9d30903a5c67)

Teachers, using the hidden menu to unarchive, cannot unarchive the section ('2nd' should be in the list, not '1st' and '3rd' which are still active sections):

![Screen Shot 2019-01-14 at 1.33.33 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/7c1eb217-f123-474e-a942-039c5b8a7861)

# Environment

Staging & Production, instructor, course roster

# Acceptance Criteria
- Instructors cannot delete a section (archive) that has students enrolled
- If an instructor tries to delete a section with students enrolled, instructor is prompted to move the students to another section (WHAT HAPPENS TO STUDENT WORK?)
- Instructors can move students between sections
- Instructors can archive sections that do not have students enrolled 
- If a student clicks on an enrollment link to an archived section, student gets an error "not available" message
- Students cannot enroll in more than one section of a course
- Teachers can unarchive sections they previously archived
- Teachers cannot unarchive sections that are active/not archived

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by gregfitch** [comment]
the instructor also cannot close the Archived Section modal

**Comment by carlycurran** [comment]
Need to discuss in scrum. This brings up the question of what we do with a student's previous work? @nathanstitt

**Comment by carlycurran** [comment]
@nathanstitt hid the delete button when a section has students

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
