### ISSUE TITLE
Annotations summary panel has strange tab and scroll behavior

### ISSUE THREAD

**Issue by nathanstitt** [openstax/tutor#23]
As a side effect of how it's implemented, the page content is still rendered behind the summary.

That content still affects the scroll bars and adds invisible tab targets

We need to rework the summary toggle so that it controls what's rendered on-screen and will remove the unwanted panels when they're not visible

**Comment by carlycurran** [comment]
This Trello card issue will be fixed when this ZenHub card work is done :) 
https://trello.com/c/1bLusegz/1620-bug-toc-appear-on-the-summary-page-when-i-made-my-screen-a-little-smaller-and-goes-away-when-its-bigger-but-you-can-get-into-a-s

**Comment by nathanstitt** [comment]
PR is https://app.zenhub.com/workspace/o/openstax/tutor-js/issues/2405

**Comment by Malar-Natarajan** [comment]
Verified in QA
