### ISSUE TITLE
Bug: The card view page doesn't load on the clicking the cardview icon from the highlights and notes page

### ISSUE THREAD

**Issue by dkhowala** [openstax/tutor#230]
### Description
Bug loading the cardview page from the notes & highlights page.

### Acceptance Criteria
The 'cardview page' should load with the first click on the cardview icon.

**Describe the bug**
The card view page doesn't load on the clicking the cardview icon from the highlights and notes page. One has to click twice for the page to load.
https://slack-files.com/T0F5B5PGQ-FFE3DCAFN-082b71327e

**To Reproduce**
1. Go to a student's current course > reading assignment.
2. Click on 'the student notes/highlight icon in the top nav.'
3. Then click on the cardview icon next to it. 
4. See error ( one has to click twice on the cardview icon for the page to load.

**Expected behavior**
The 'cardview page' should load on the first click on the cardview icon.

**Desktop**
 - OS: [e.g. iOS10.14.1]
 - Browser [ chrome ]

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
this is working correctly now, was fixed at some point

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
