### ISSUE TITLE
Design template for AP Physics

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#235]
### Description
Make sure we are set up to import AP Physics 
Get colors and physics book cover card (cnx or marketing)

### Acceptance Criteria
Design assets have been given to Nathan, including book cover files and AP Physics colors.

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [x] Estimate is updated for the work item issues.
  - [x] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [x] Distilled acceptance tests are added to the issue.
  - [x] Automated testing criteria are added to issue.
  - [x] The solution is updated.

2A-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by carlycurran** [comment]
@nathanstitt here is the CNX link for AP Physics :) 
https://cnx.org/contents/jQSmhtXo@19.5:6pB5TgBD@8/Connection-for-AP%C2%AE-Courses

**Comment by nathanstitt** [comment]
[https://app.zenhub.com/files/150623529/08506acc-a021-472b-9cb7-5db188d9263e/download](https://app.zenhub.com/files/150623529/08506acc-a021-472b-9cb7-5db188d9263e/download)

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/edf4df41-fc92-47f2-8d37-88cf1c6027f7)

**Comment by Malar-Natarajan** [comment]
Nothing code related to test
