### ISSUE TITLE
Import AP Bio

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#239]
### Description
Modify existing Bio import to work for AP Bio and perform import, then note problems.
Set as "not available for selection"

### Acceptance Criteria
On QA, as an admin, I can enroll an instructor and a student in AP Bio and see the course.
On production, as a teacher, I cannot select AP Bio as a course

#### Distilled acceptance test
- Given that I am an OpenStaxer, when I create an OpenStax Tutor course from admin, then I have the option to create an AP Bio course. 
- Given that I am an OpenStax Tutor user, when I sign in to my account and create a course, I do not have an option to create an AP Bio course. 
- Given that I am an OpenStaxer who has created an AP Bio course, I should be able to build assignments using the question library and use all features of a typical OpenStax Tutor course.

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [x] Estimate is updated for the work item issues.
  - [x] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - ~The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.~
  - [x] Distilled acceptance tests are added to the issue.
  - ~Automated testing criteria are added to issue.~
  - ~The solution is updated.~

2A-CODE
  - ~[ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.~
  - ~[ ] The acceptance tests are finalized in "Given / When / Then" format.~
  -  ~[ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.~

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
Done!  
![image](https://user-images.githubusercontent.com/79566/53450768-c14dbc00-39e2-11e9-84a2-c312a156f572.png)

**Comment by Brooke-Fail** [comment]
Verified in Production.
