### ISSUE TITLE
Developers need simple ways to manage background jobs/tasks/processes on BL servers

### ISSUE THREAD

**Issue by nathanstitt** [openstax/tutor#24]
Derived from t3.02.03 - As OpenStax R&D, we need to build the necessary algorithmic and software infrastructure to implement Biglearn..  Developers need simple ways to manage background jobs/tasks/processes on BL servers, including: - starting, stopping, checking status, restarting - protections against multiple instances (in some cases) - logging and stack traces - debugging  Support must exist for both ruby and python processes. Both languages will likely need to connect to the database.

**Comment by carlycurran** [comment]
Algorithm and software infrastructure have been built. Systemd is used to manage background jobs in biglearn-sparfa and monit in biglearn-scheduler (but hopefully we'll switch everything to systemd at some point). pidfiles/celery_once are used to prevent running multiple instances of stuff. Logging is either papertrail in scheduler/api or printing to stdout in biglearn-sparfa (captured by systemd). Debugging support... no idea what this is


Closing this card.
