### ISSUE TITLE
Bug: Assignment created on course with change in ecosystem

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#246]
**Describe the bug**

A source is on old ecosystem. 
The course on an old ecosystem is cloned to a new ecosystem
Assignments on the new course are from the old ecosystem with different section IDs. 

If they don't edit the assignment, students should be able to work it. 
If the do go in and edit the assignment, when they click to select different sections, it finds all the exercises for that homework, it displays them in the cardview (linked to sections that were selected), but section has different ID. So exercises cannot be grouped into sections by teacher. Causing Java error. Java error is fixed, but exercises are part of the assignment that the teacher cannot see and cannot edit/deselect. 

We could create additional exercises section at the bottom that the teacher could unselect if they choose.

We haven't noticed this before because they copy the assignment over and never go edit it. 

Going forward, the backend needs to map section IDs from old ecosystem to new ecosystem. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by Malar-Natarajan** [comment]
@nathanstitt 
Tested this in QA and below are the results. I used this course (its copied from a old ecosystem) https://tutor-qa.openstax.org/course/2401/t/month/2019-01-24 teacher01:

Editing a cloned reading: I tried copying a reading from a cloned course. The copied reading did not list the sections that were selected earlier. I went ahead and selected sections 2.1 - 2.5 which was problematic from production screenshots....and get the error in console and the screen does not move to the next screen. Please see video

https://drive.google.com/file/d/1q_tQhICXr_tzb8qpp0fznCDbNMvIlkZl/view?usp=sharing

Editing a cloned HW: I tried copying a HW from a cloned course. Edited the HW to add an exercise from ch 2.1 (or any chapter). On hitting Publish or save this error is received. See screenshot

![Screen Shot 2019-01-22 at 12.54.21 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/40f40435-b959-434c-92aa-e445f4ae2a7a)

**Comment by carlycurran** [comment]
When we imported ecosystem, section IDs are different. We do map them, but not for old, cloned exercises (we think exercises that are no longer in use). 

If you click "add new sections" there is info loss because display can't show previous sections.

This could happen every time we have a new ecosystem where pages that held an exercise have been replaced. 

If teacher doesn't edit assignments, back end maps the exercise to the correct page (we think). If the exercise has been removed, it will be dropped. 

When edited, back end doesn't recognize the the page and it can't pull up the exercise. So the edit becomes replacing sections IDs rather than adding. 

Reading: **Ideally, the mapping would happen when someone clicks "edit"**
The quick for (for this release) will no longer cause and error, and when they click "edit" we'll display new sections. Old pages will be lost. They will lose the assignment, although if they are going in to edit, the probably want to do that anyway. 

HW: We can't display old exercises. They're still there, but cannot be removed. Teachers can add new exercises. Ideally, we'll need to map sections numbers.

**Comment by Malar-Natarajan** [comment]
Verified in staging. Did not get any errors and was able to edit copied assignments from a course created before the baking

**Comment by Malar-Natarajan** [comment]
This failed in production. May be staging did not have the proper test data to test this scenario. 
After fixing the issue, will retest in QA

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
