### ISSUE TITLE
Some student reading assignments are delayed on dashboard when enrolling

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#249]
**Describe the bug**

For some students, (IP in course #4950, Niklas Manz students) reading assignments are not showing up on the student dashboard for a period of time. Other students in the course have no problems seeing the reading assignments. 

This has happened twice and resolved itself within a day both times, but we don't know why it's happening for some and not others. 

**To Reproduce**

**Expected behavior**
Reading assignments should show up within 10 minutes of enrolling.

**Screenshots**

**Desktop (please complete the following information):**

### Checklist for Done
2-CODE
  - [x] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [x] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [x] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
Fixed by code change in https://github.com/openstax/biglearn-scheduler/pull/75

**Comment by Malar-Natarajan** [comment]
No loading issues found in QA

**Comment by Malar-Natarajan** [comment]
No loading issues found in Staging
