### ISSUE TITLE
LMS launch errors out if course has multiple sections

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#255]
### Description
An instructor can integrate an OpenStax Tutor course with multiple sections with an LMS. However, when the students launch, the section picker does not load and they get an error. 

Even if extra sections are deleted from a teacher's course after integration, the LTI launch does not recognize the deletion, and the students still get an error. 

We have explicitly asked instructors _not_ to pair multiple Tutor sections with an LMS. *Before we allow them to do that, I want to understand why we previously nixed this request*

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: Mult-section LMS launch  
**categories**: LMS
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [x] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by carlycurran** [comment]
Change section picker copy to: 

Please select the OpenStax Tutor section you are a member of. If you don't know which section to select, ask your instructor.

**Comment by Malar-Natarajan** [comment]
Verified in Staging - Blackboard

**Comment by Malar-Natarajan** [comment]
Verified in Canvas staging
