### ISSUE TITLE
Bug: LMS Admin can't launch

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#256]
### Description

LMS admin roles cannot launch OpenStax Tutor (via Willo) from LMS

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**
Admin roles get converted to instructor roles for our purposes

**Screenshots**
![Screen Shot 2019-01-23 at 8.07.09 AM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/32d8cc9e-74c8-4936-b4af-2a90e1ddfe4a)

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: LMS admin launch  
**categories**: LMS
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [x] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [x] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [x] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by Malar-Natarajan** [comment]
This has to be tested by Willo pilots and is already in production
