### ISSUE TITLE
Map old ecosystem exercises and sections to new ecosystem

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#258]
### Description
As an instructor I want old ecosystem sections to map to new ecosystem sections, so that when I clone an old course into a new ecosystem, I can still use and edit my homework and reading assignments. 

When we import a new ecosystem, section IDs are different. We do map them, but not for old, cloned exercises (we think exercises that are no longer in use).This could happen every time we have a new ecosystem where sections that held an exercise have been replaced or renumbered.

If a teacher doesn't edit an assignment, the back end maps the exercise to the correct page (we think). If the exercise has been removed, it will be dropped.

If a teacher does try to edit and assignment, the back end doesn't recognize the the old section and it can't pull up the exercise.

Reading: Ideally, the mapping would happen when the old assignment is dragged onto the dashboard or when someone clicks "edit."
Currently,  when a user clicks "edit," we'll display new sections. Old sections will be lost, and the user needs to select new sections (even repeat sections). 

HW: Ideally, we'll need to map section numbers when the assignment is dragged to the dashboard or when it opens or "edit" is clicked. Currently, we can't display old exercises. They're still there, but they do not show up and cannot be removed. Teachers can add new exercises. 

### Acceptance Criteria
Give criteria for acceptance.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
  - [ ] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [ ] Estimate is updated for the work item issues.
  - [ ] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2A-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by nathanstitt** [comment]
Readings and Homework's have the ecosystem id that they were created under.

We should use that to load the sections for the old ecosystem and then use that when displaying  the related parts with the builder.

However this means that a reading can get really outdated.  Consider the case of one that was created 3 semesters ago and then copied between the courses.  It'll continue to use old book content, which will not match the reference view.

**Comment by Dantemss** [comment]
tutor-server automatically tries to update cloned assignments when they are created (cloned): https://github.com/openstax/tutor-server/blob/2bcf7e867ff389191ab90114c5e98b1f42a7b141/app/controllers/api/v1/task_plans_controller.rb#L128

**Comment by nathanstitt** [comment]
this should be working after the recent assignment editor work

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging as well as the fix for loading the old assignments in student view.

**Comment by Brooke-Fail** [comment]
Verified in Production.
