### ISSUE TITLE
Spike: Investigate scope of getting BL-SPARFA online

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#26]
# Description: 

Dante will dig into the BL-SPARFA issue and 
1. Determine whether is assumptions/analysis here still hold: https://docs.google.com/document/d/1ztMvH5QFlYMDjz75zHEowzhWo7jgw10hkqqU4of7e04/edit#
2. Estimate the size and scope of the work to actually get BL- SPARFA online 

WOOHOO!

**Comment by carlycurran** [comment]
Dante estimates this will take about 2 months. Carly wants to give it 3 months :)

**Comment by Dantemss** [comment]
Card for work created
