### ISSUE TITLE
"Suggest a correction" from performance review screen in Teacher view does not pre-populate the subject in the errata form

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#262]
### Description
"Suggest a correction" from performance review screen in Teacher view does not pre-populate the subject in the errata form

https://tutor-staging.openstax.org/course/4074/metrics/27710
Teacher01

**To Reproduce**
1. Login as a teacher and go to student scores
2. Click Review link for any assignment
3. Performance  review screen for the assignment opens
4. Click on suggest a correction link

**Expected behavior**
The errata form should be opened and prepopulate the subject

**Screenshots**
I am talking about this screen
![Screen Shot 2019-01-29 at 10.52.51 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/9a8fba98-6b48-471b-a233-840bf32d9651)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
This is now working, we fixed it last release

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
