### ISSUE TITLE
Highlight summary icon not displayed in certain pages of the Reading

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#263]
### Description
Highlight summary icon not displayed in certain pages of the Reading

Happened in chrome, in this reading when I first started the reading: https://tutor-staging.openstax.org/course/3800/task/1404198
mn45+7887@rice.edu

**To Reproduce**
1. From student view, browse the book and highlight few lines in a reading assignment that has been created
2. Then start the reading. The summary icon at the top was missing. But it appeared when I did a back & forth couple of times

**Expected behavior**

**Screenshots**
https://drive.google.com/file/d/1aM4BGkkl6Ok-56MksZJPlkOrOqRF1CCJ/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
we investigated this and believe it's because the course wasn't active.  we have another card to relax that restriction https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/291

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
