### ISSUE TITLE
Logging in with deleted assignment link shows the page weird to the student without any buttons

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#269]
### Description
Logging in with assignment link after teacher deletes the assignment shows the page weird to the student without any buttons

**To Reproduce**
1. Teacher creates assignment and student gets the assignment links
2. Teacher deletes the assignmnt
3. Student logs in with the deleted assignment link and sees that:
For HW: the questions are still displayed with FR box but no answer/submit/next buttons
For Read: the first page/wherever the student had left earlier is displayed but with no next button

**Expected behavior**
Is this the expected behavior or should we get any messages

**Screenshots**
![Screen Shot 2019-02-06 at 11.58.14 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/613dfb2e-46ee-430a-9ab2-cd745ddb7eba)

![Screen Shot 2019-02-06 at 11.57.57 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/f6c35c1c-d7fc-4892-8d65-75d18a21eeff)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
