### ISSUE TITLE
Allow OpenStax to turn off intervention feature

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#275]
### Description
As OpenStax, I want to be able to turn this feature on or off so I can test it. 

Phase 1: We will build a feature flag so that OpenStax devs can turn off the entire feature. We'll build another feature flag that turns off the gibberish detection UI, but still records data. 

in Phase 2, depending on user reports/requests, we will evaluate enabling a checkbox on the user interface that allows instructors to turn this feature on and off. 

### Acceptance Criteria
- We can turn this feature off entirely and regression tests pass. 
- We can turn off the UI and still record gibberish detection data. Regression tests pass. 

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [ ] A high-level solution (development approach for the code change) is added to the issue

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [ ] Estimate is updated for the work item issues.
  - [x] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2A-CODE
  - [x] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

**Comment by nathanstitt** [comment]
In the admin panel under Settings, there's two new checkboxes near the bottom:
![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/ac16f6cc-b5eb-4fae-a809-b4174332b933)


![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/6a46eaf3-e827-4e73-9ac7-6aac5fbe3e67)

**Comment by Malar-Natarajan** [comment]
@nathanstitt 

https://tutor-qa.openstax.org/course/2471/task/378241/step/33 . student05

"Response Validation UI Enabled?" setting was turned off while doing the reading step above. No prompt was displayed for the gibberish FR as expected.

Spy mode shows all the data that was sent to the server as expected. I have a question with the last spy mode line "nudgeMessage: Rewrite your answer after reviewing section".

Does this line mean that nudge was prompted?

If yes, I think we have a bug because we cannot differentiate whether the nudge was displayed or not when the UI setting is turned off.

![Screen Shot 2019-04-11 at 1.02.43 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/ec106bc2-cd1b-474d-b6fa-770c11a0cfb5)

**Comment by nathanstitt** [comment]
yeah, that's a great catch.  The "nudgeMessage" was what would have been displayed but we shouldn't add it to the info since it wasn't actually shown.

**Comment by Malar-Natarajan** [comment]
@nathanstitt 

Similar issue in the following cases also:

1. when we do a re-answer. In this case for "attempt 1" the nudge message should either be null or something else  to indicate no nudge was displayed.

2. When we give a valid FR (valid = true in spy mode), the nudge message in spy mode should be either null or something else to indicate no nudge was displayed

On a similar note, when the "attempt = 1" are we still validating the free response?

![Screen Shot 2019-04-11 at 1.29.21 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/999024a4-32c3-4901-a504-ba50dcb35159)

**Comment by Malar-Natarajan** [comment]
@nathanstitt 

When the "Validation UI Enabled?" setting is turned off the spy mode now displays the nudge message as "null".

But I could have done a better job summarizing all the related issues in one comment. I added two more criteria for incorrect spy mode as a "separate comment" above with screenshots which probably you haven't looked at. So reopening this issue.

**Comment by nathanstitt** [comment]
I'm afraid I don't fully understand what you're suggesting.

This is what we're doing currently:

We submit the text to be validated each time if the submit button is clicked.  
  * This is why the spy mode shows two validations. 
  * On the second validation, we do not pause the UI instead we go onto the multiple choice, regardless of the text validation.

If the users clicks the "submit answer anyway" link, then we do not re-validate.  
* This will allow research to detect when the user clicks the text by looking at the attempts and if it has a length of only 1, we know they aborted.

**Comment by Malar-Natarajan** [comment]
My 2nd set of comments on Apr 11  are only based on the "Nudge line" in the spy mode..like if it should display null or the message on the scenarios that I have mentioned. I edited it to explain further and can explain in PL
