### ISSUE TITLE
Bug: LMS "already used" error 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#280]
### Description

LMS is re-using an id that we did not think it would re-use and causing an error for some students trying to log in. So far, we have seen this in Moodle. 

 We’re requiring each request to be unique but there’s no real reason for us to do so. We can allow that value to be re-used. Nathan did 2 things:

1) manually cleared the values so that student can continue, but then she may hit the same thing again later
2) make a PR to ~relax our validation, reviewed with JP~ log when this occurs

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**
Students do not get "already used" errors when launching from their LMS account

**Screenshots**
![OpenStax.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/f8fea7a0-5bf4-456b-be55-596a40cc8924)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
Made https://github.com/openstax/tutor-server/pull/1845 to add additional logging, but merged the pr to soon and now can't link it.

**Comment by carlycurran** [comment]
@nathanstitt we did not relax the validation here, right? We are just adding logging?

**Comment by nathanstitt** [comment]
That’s correct.   We’re now logging when this occurs and if it happens more than a few times per semester we’ll consider removing the check

**Comment by Malar-Natarajan** [comment]
Unable to test because we did not have Moodle test user & setup
