### ISSUE TITLE
Section objectives in Bio and Physics are showing up at the start of the chapter in the chapter intro

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#281]
### Description
Section objectives in Bio and Physics are showing up at the start of the chapter in the chapter intro

In Sociology, we send the objectives for each section to the start of the section itself in both reading and reference view.

![Screen Shot 2019-02-18 at 5.33.17 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/fdbdc9de-4481-4ef6-9ea4-398337cec671)

![Screen Shot 2019-02-18 at 5.37.40 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/9a213a4b-9a33-40a8-b7f4-78801a2bae46)

### Acceptance Criteria
Learning objectives are present at the section level of a reading assignment and in reference view, not in the chapter introduction. 

**To Reproduce**
Steps to reproduce the behavior are
1. Go to a reading assignment or reference view and look at the intro section for a chapter of Physics or Bio

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
I don't think this is a bug. Learning objectives should appear at the start of the chapter, right?

**Comment by carlycurran** [comment]
Well, in Sociology (and I think in unbaked Bio and Physics) we surface learning objectives at the section level of a reading assignment. And of course some also show up at the start of the chapter. But right now, for Bio and Physics _all_ the learning objectives show up at the chapter start and aren't distributed to sections.

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
