### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#282]
### Description
Error on course 4967: TypeError: Cannot read property 'id' of undefined
It looks like the student doesn’t have a task with that ID.  She probably got a URL for an assignment from a different student and tried to use it, not knowing that the URL’s are per-student.

The error should say: "It looks like this task doesn't exist."

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by carlycurran** [comment]
We should also give them a way/path back to their course dashboard.

**Comment by nathanstitt** [comment]
pretty sure this is the same bug that was recently fixed with "map of undefined"

**Comment by Brooke-Fail** [comment]
I havent seen this error while testing, ready for testing on staging.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
