### ISSUE TITLE
A student clicking on an event generates a TypeError

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#283]
### Description
Description

A student clicking on an event assignment generates a `TypeError: l is undefined`

**To Reproduce**
Steps to reproduce the behavior are
1. Log in as a student with an event
2. Click on the event

**Expected behavior**
no type error

**Screenshots**
![Screen Shot 2019-02-19 at 1.50.45 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/412d3935-82af-4a1c-a38b-e0f8fc0d26d8)
![Screen Shot 2019-02-19 at 1.50.23 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/a698cfdb-550f-4a45-b1c7-0aced62010a1)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 71

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by Malar-Natarajan** [comment]
@nathanstitt 
Tested in QA, the event click still generates an error

![Screen Shot 2019-03-04 at 4.14.22 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/aa620eac-4b2a-417d-8a28-d87d1293d18c)

**Comment by Malar-Natarajan** [comment]
Redeployed in QA and event click works

**Comment by Malar-Natarajan** [comment]
Verified in staging
