### ISSUE TITLE
Fix LMS help link 

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#284]
### Description
Description
The 'Which option is right for my course?' help link is broken.

**To Reproduce**
Steps to reproduce the behavior are
1. Go to https://tutor-qa.openstax.org/course/2404/settings?tab=0 under teacher05
2. Click on `Which option is right for my course?`

**Expected behavior**
user is taken to the help article
Article title:Student Access with Enrollment Link versus LMS sign-in for OpenStax Tutor Beta
Article link: https://openstax.secure.force.com/help/articles/FAQ/Student-Access-with-Enrollment-Link-versus-LMS-sign-in-for-OpenStax-Tutor-Beta-LMS-Pilots

**Screenshots**
![Screen Shot 2019-02-19 at 3.20.52 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/50111f7e-49fe-45e4-a073-2e36725a5cac)
![Screen Shot 2019-02-19 at 3.21.05 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/55cfd2a9-90ff-47fb-8b9d-c3367db7e000)

### Acceptance Tests

**title**: template  
**categories**: Navigation
> GIVEN that I am an instructor using OpenStax Tutor   
> WHEN I click on the link 'Which option is right for my course?' on the course settings page   
> THEN I go to https://openstax.secure.force.com/help/articles/FAQ/Student-Access-with-Enrollment-Link-versus-LMS-sign-in-for-OpenStax-Tutor-Beta-LMS-Pilots

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by carlycurran** [comment]
Bonne looking into this :)

**Comment by bonnebbrown** [comment]
It looks like this article got a new title and URL in the Help center on August 07, 2018.
Article title:Student Access with Enrollment Link versus LMS sign-in for OpenStax Tutor Beta
Article link: https://openstax.secure.force.com/help/articles/FAQ/Student-Access-with-Enrollment-Link-versus-LMS-sign-in-for-OpenStax-Tutor-Beta-LMS-Pilots

**Comment by Malar-Natarajan** [comment]
Verified in QA

**Comment by Malar-Natarajan** [comment]
Verified in staging
