### ISSUE TITLE
Exercises - Can't edit some exercises 

### ISSUE THREAD

**Issue by lwtchu** [openstax/tutor#285]
### Description
Description

For the following exercises, we can edit htem but we can't save. It errors out.

13038
13833
13138
13097
13016

**To Reproduce**
Steps to reproduce the behavior are
1. Go to exercises.openstax.org with openstax log in
2. Search for the exercise
3. Make a change and hit save - won't work.

**Expected behavior**
It should save

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: Vocabulary Exercises Edit test
**categories**: Book Content, Other
GIVEN an exercise originally based on a vocabulary import  
AND signed into exercises editor as the author of that exercise
WHEN searching for that exercise ID
THEN the displayed exercise search result has a  READ ONLY ribbon in the upper right corner, with the text "Vocabulary Exercise"
AND there is _no_ edit button 

### Checklist for Done
2-CODE
  - [x] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers. https://github.com/openstax/tutor-js/pull/2523
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by reedstrm** [comment]
On further investigation, all five of these examples _are_ vocabulary-based-exercises.

**Comment by reedstrm** [comment]
The attached PR does not make these editable - it properly tags them as READ ONLY, and does not allow getting to the edit page.

**Comment by Malar-Natarajan** [comment]
@nathan @reedstrm I am still not able to edit many exercises (I tried 16489, 15589, 16195, 15423, 15590, 2323) but was able to save 12222, 1276, 11023, 1500

**Comment by nathan** [comment]
> @nathan

You probably meant @nathanstitt 😄

**Comment by Malar-Natarajan** [comment]
Vocab exercises are now having the green label in the side panel and are editable and saves properly as long as it does not have the image.

These error 500 are related to images and we have a separate issue for that. So closing this issue since vocabs work as expected.

**Comment by Malar-Natarajan** [comment]
Verified in staging

**Comment by Brooke-Fail** [comment]
Verified in Production.
