### ISSUE TITLE
TOC numbering in AP physics is not matching cnx.org

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#286]
### Description
TOC numbering in AP physics is not matching cnx.org

**To Reproduce**
1. "Connection for AP courses" is not numbered in cnx.org but numbered in Tutor. So there is a duplicate numbering of first section in all chapters(eg. 2.1) but the content is sequentially numbered and causes a mismatch between TOC and book page

2. "Test for AP Courses" is not numbered in cnx.org but numbered in Tutor TOC & the book page

**Expected behavior**

**Screenshots**
https://drive.google.com/file/d/1MUXmYGdJ1PI57QYOjiNx2Nz0Pdk_yYVi/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
same cause as https://github.com/openstax/tutor/issues/264  Fixed in https://github.com/openstax/tutor-js/pull/2595

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
