### ISSUE TITLE
Don't allow null values (for ecosystems) in BL 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#287]
### Description

After the BigLearn critsit, reviewed in this postmortem doc: https://docs.google.com/document/d/1Q7Mzs5wuy_z3R4uvNHPXor-OPrNsFmdkEFMxUs4JIwU/edit#heading=h.nz1hmg96utf1, we found that *BL scheduler assumed that the courses would always have an ecosystem. However, BL API did not share that assumption; instead it is possible for the ecosystem to be null in Tutor. 

### Acceptance Criteria
It is impossible for a course to have a null ecosystem uuid and BigLearn API continues to function without errors.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-PRE DESIGN
- [x] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.

2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by steveburkett** [comment]
https://github.com/openstax/biglearn-api/pull/85

**Comment by Malar-Natarajan** [comment]
Forgot to reopen this card with the issue reported in QA on April 5th. https://openstax.slack.com/archives/C0F6Z1JUS/p1554494693214100

**Comment by nathanstitt** [comment]
this was completed in https://github.com/openstax/biglearn-api/pull/89

**Comment by Brooke-Fail** [comment]
I haven't seen this issue in testing while on QA. I'll keep a look out for it in Staging and while testing in general.

**Comment by Brooke-Fail** [comment]
Seems fixed in Staging.
