### ISSUE TITLE
Upgrade ruby/rails versions

### ISSUE THREAD

**Issue by nathanstitt** [openstax/tutor#288]
### Description

Currently we're running an unsupported version of ruby that has a minor security issue.

Additionally Rails 6 is right around the corner and once that is released Rails 4.x will be unsupported.

We should upgrade to Ruby 2.6 and Rails 5 or 6 if it's released soon.

### Acceptance Criteria

Code continues to pass all specs and there are no regressions.

**Comment by Malar-Natarajan** [comment]
Regression testing passed in staging
