### ISSUE TITLE
Change Request: Fix block quote styling

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#29]
*DESCRIBE THE DESIRED OUTCOME*
Styling is improved on blockquote after a figure.

Current Behavior
-----
In the APUSH demo materials, we had two blockquotes.  One occurred after a figure and looked wonky, as if it were part of the figure caption.  However, the blockquote looks fine on staging-tutor.cnx.org (where the content was written) and I cannot find a reason in the cnxml that the blockquote would look like it's part of the figure in Tutor.

cnxml for blockquote that is styled correctly in Tutor: 
<para id="eip-649"><quote id="eip-id1167066994348"> 
  "<emphasis effect="bold">Freedom now appeared, to disappear no more forever. It was heard in every sound, and seen in everything.</emphasis> It was ever present to torment me with a sense of my wretched condition. I saw nothing without seeing it, I heard nothing without hearing it, and felt nothing without feeling it. It looked from every star, it smiled in every calm, breathed in every wind, and moved in every storm.
"</quote></para>
from module: https://staging-tutor.cnx.org/contents/dc10e469-5816-411d-8ea3-39a9b0706a48@2.14:2/Frederick-Douglass-The-Respons

cnxml for blockquote that is styled incorrectly in Tutor: 
<para id="eip-807"><quote id="eip-id1167064875806"> 
  "I was determined to be used no longer."</quote>
</para>
from module: https://staging-tutor.cnx.org/contents/dc10e469-5816-411d-8ea3-39a9b0706a48@2.14:3/Douglass-struggles-against-sla

You can see that the styling looks good in both modules on staging-tutor.cnx.org.  The problem seems to be specific to Tutor.

-----
Desired Behavior
-----
The block quote should be styled consistently regardless of what content might be around it (paras, figures, etc.)

**Comment by nathanstitt** [comment]
I had a hard time finding the content but finally located it at: 
https://tutor-demo.openstax.org/book/44/section/1.1 and 
https://tutor-demo.openstax.org/book/44/section/1.2

However, it appears to be styled correctly so maybe this was fixed elsewhere?

![Screen Shot 2018-10-09 at 3.39.22 PM.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/f586ae1d-d2de-4be3-8c17-0f6a73e31030)

![Screen Shot 2018-10-09 at 3.39.37 PM.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/871e6dc4-7a32-4b70-9530-ea26cb184a93)

**Comment by carlycurran** [comment]
Cool, I talked to Alina and it looks like we can close this! Must have been from the previous prototype.
