### ISSUE TITLE
go back to course-specific reference view IDs 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#293]
### Description
Investigate going back to course-specific reference view IDs 

We're not sure why we went away from these -- if there was an important reason -- and we need to find out. 

Currently, a student may be in multiple
courses that refer to the same ecosystem.

When the view needs to load things for the users course it
looks at all the available courses.  it first tries to find
an active one, and then just the first match.

This affects things like notes that are linked to courses.
If a student is in only one course then all’s well but if
they’re in multiple courses that are active it’s hit-or-miss

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-PRE DESIGN
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
  - [ ] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [ ] Estimate is updated for the work item issues.
  - [ ] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by Brooke-Fail** [comment]
Switching courses without closing the notes tab for the previous course, will result in the wrong notes showing up for the new course. If the notes are closed before moving to a new course, the correct notes are show in the reference view. 

Video:
https://drive.google.com/file/d/1H-Q2YSITPBp_YMYCmJMpfAwDuXDIo-zY/view?usp=sharing

**Comment by carlycurran** [comment]
What a crazy scenario! Wow, @Brooke -- nice catch.

**Comment by nathanstitt** [comment]
I've investigated and it'll take a little work to fix this (1 day or so) I'm going to move this card over and ask that we file a separate bug for the notes so we can estimate that separately

**Comment by nathanstitt** [comment]
created https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/494 for the summary page issue

**Comment by Brooke-Fail** [comment]
This is verified in QA. The issue mention is documented in a separate card: 494.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
