### ISSUE TITLE
Bug when exercise has more than one image

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#295]
### Description
When creating an assignment, when an exercise has 2 images, we add exercises to the review table. After you click "next," we remove the images from them so they’re more compact. We have a bug when there is more than one image and the removal of the 2nd fails.

An instructor, Ross Burrows, is receiving the following error when he tries to add a problem to a draft assignment:
I ran into a problem at https://tutor.openstax.org/course/4902/homework/45583# while using browser
 Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36.

The request details are:
undefinedThe request body was:
{
 "error": "TypeError: Cannot read property 'nextSibling' of undefined"
}.

The exercise with this issue is in Physics sec 17.5 - 15954@3

Additional multiple image exercises for testing: Bio sec 20.1 - 1628@5, 1568@5

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by Malar-Natarajan** [comment]
The exercise with this issue is in sec 17.5 - 15954@3

**Comment by Malar-Natarajan** [comment]
Verified in QA

**Comment by Malar-Natarajan** [comment]
Verified in staging
