### ISSUE TITLE
Error 500 when saving exercises with images

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#297]
### Description
Error 500 when saving exercises with images. I deleted the image, also deleted the reference to the image in the assignment and still getting error 500

![Screen Shot 2019-03-18 at 1.51.25 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/6d80f258-ce1a-4317-99ed-dc905b031f29)
**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by Malar-Natarajan** [comment]
These PR's were merged before adding to the issue. SO created new issue and here are the PR's:
https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/exercises/255

**Comment by Malar-Natarajan** [comment]
Verified in QA & staging. No errors are displayed if the images are on the same server and not pointing to production

**Comment by Brooke-Fail** [comment]
Verified in Production.
