### ISSUE TITLE
Page reload sometimes errors in console and needs a 2nd reload to display the page correctly

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#299]
### Description
Page reload sometimes errors in console and needs a 2nd reload to display the page correctly.

Noticed this issue intermittently since March 1 code freeze in these two pages:

1. Click on the "Browse the book" menu option
2. Update the scores page with late work or set new weights

When I do any one of the above and Reload the page, the page keeps reloading and there is an error in the console. Reloading the page again solves the problem though.

Please see video:
https://drive.google.com/file/d/1WzJaPRGhATzJ0rUXI4iC9kV6hg_K2cwu/view?usp=sharing

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [x] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
I can't seem to replicate this (I tested on QA).  I also used safari icognito as student01

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
