### ISSUE TITLE
Publish and Cancel buttons are disabled after getting the 422 error for a blank assignment name

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#300]
### Description
When creating a new reading, homework, events, or external assignment if the user gets the 422 error due to a blank assignment title, the Publish and Cancel button will be disabled. Save as Draft and the 'X' button at the top are the only active buttons.

**To Reproduce**
Steps to reproduce the behavior are
1. Log on to Tutor as an instructor
2. Click on an existing course
3. Add any type of assignment or event to the calendar
4. When creating the assignment, press the Space button in the assignment name field
5. Fill out the required information correctly 
6. Click Publish
7. There will be a 422 error that pops up for the space in the name, click OK
8. Remove the space and add a correct assignment title
9. Notice that the Publish and Cancel buttons are disabled even after the information has been fixed

**Expected behavior**
The Publish and Cancel buttons become active once all required information has been entered correctly.

User: teacher01
Course number: 2483 (can use any course)
Page issue occurs on: https://tutor-qa.openstax.org/course/2483/external/new?due_at=2019-03-22

Video Link:
https://drive.google.com/open?id=1TVvr_X325KGpjbR-QDeQJLdTUdkAEUg9

**Screenshots**
![Screen Shot 2019-03-20 at 4.06.26 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/7ca8a8d7-86f1-4c85-8174-55a4da67242f)

**Desktop (please complete the following information):**
- OS: macOS
- Browser: safari, chrome
- Version: 12.0.3, 73.0.3683.75 

**Smartphone (please complete the following information):**

**Additional context**
- Issue occurs for all assignments
- The issue only occurs if a space is inputted in the assignment name field. If the user leaves this field completely blank and tried to proceed, the issue does not occur. 

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by carlycurran** [comment]
2 bugs:
- you can attempt to publish an assignment that's invalid; FE should not give a 422, it should just prevent the save
- if we do get a 422, we shouldn't end up in an invalid state

**Comment by Brooke-Fail** [comment]
I similar error occurs for free-response questions in assignments. 
Steps:
1. Open a reading or homework free-response quesion
2. Input a space in the field 
3. If asked to re-answer with the response verification, input another space
4. Upon clicking Submit answer, there is a 422 error for a blank free-response answer

Screenshot of error:
![Screen Shot 2019-04-03 at 3.27.01 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/29367698-54a6-4b53-95b0-2c2508e8b4d3)

**Comment by Brooke-Fail** [comment]
This issue is still occurring after the fix in https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor-js/2585.
However, once I click Save as Draft, the error is thrown again, and I get a prompt to Refresh the page, but the page does not refresh when the button is clicked. 

![Screen Shot 2019-04-30 at 8.22.38 AM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/5a411f37-61db-42b5-bcf8-af06cd160bf8)

**Comment by carlycurran** [comment]
yikes, that's a lot of buttons on that bottom bar!

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2654

**Comment by Brooke-Fail** [comment]
Having a different but similar issue. I get a 422 error when clicking publish if I forgot to click add readings. See video:
https://drive.google.com/file/d/1pt7rS5yF3sDS3CyfWZoN2zylI9YCJgjN/view?usp=sharing

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
