### ISSUE TITLE
Publish/Draft/Cancel icon explanation flickering

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#301]
### Description
Description

The on hover for the "i" information flickers if the mouse cursor is on the right half of the icon (rapid fire on hover). Affects Firefox and Chrome.

https://drive.google.com/a/rice.edu/file/d/1Ztr4bpZHgJtlvz2jDicz97rqxBOyX5Ah/view?usp=sharing

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by carlycurran** [comment]
We us an svg, which is transparent, so if you move your mouse over just the right park of the icon, it flickers and gets in between cursor and icon -- hides and re-shows.

**Comment by nathanstitt** [comment]
I fixed this as part of the work on #300

**Comment by carlycurran** [comment]
YES!! Thanks, @nathanstitt

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
