### ISSUE TITLE
Overall and student course averages are blank on the student scores export 

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#302]
### Description
If you export the student scores, the course averages for both the students and overall, do not display in the export. 

User: tt02 (bf22+02@rice.edu)
Course number: 2492
Issue occurs in Export from this page: https://tutor-qa.openstax.org/course/2492/scores?tab=0

**To Reproduce**
Steps to reproduce the behavior are
1. Log into Tutor as an instructor
2. Click on the College Physics - 3.19 course
3. Click on Student Scores
4. Click the Export button towards the top right of the page
5. Open the Export
6. Notice that the Course Averages for the student and overall are blank and do not populate on the export

**Expected behavior**
All fields in the Student Score table are correctly exported, calculated, and displayed when exported.

**Screenshots**
![Screen Shot 2019-03-21 at 8.05.23 AM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/a710b956-604b-4bf8-b094-b03bdc496ad4)

File:
[https://app.zenhub.com/files/150623529/812df745-e6a6-42e1-a22f-cc858c51def0/download](https://app.zenhub.com/files/150623529/812df745-e6a6-42e1-a22f-cc858c51def0/download)

**Desktop (please complete the following information):**
- OS: macOS
- Browser: safari, chrome
- Version: 12.0.3, 73.0.3683.75

**Smartphone (please complete the following information):**

**Additional context**
All other information seems to export correctly, just the overall student and course averages are not exporting properly.
Tested in QA.

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by Brooke-Fail** [comment]
I was opening the export file with the default previewer that my Mac has. It says the type of file is a Spreadsheet.
@Malar-Natarajan was able to see all the data correctly in the export file when opening it via Microsoft Excel.

**Comment by nathanstitt** [comment]
We use formula's to calculate those numbers which preview doesn't seem to support.

I see that `Numbers` does render the formulas though and it's a free download for Mac.

Since it'd be quite a bit of effort to rewrite the export I think we can just tell users to use Excel if they have it, or download Numbers if not.

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/a1c59962-716e-4a20-837f-9c74ea428eeb)

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by ejp3** [comment]
Verified in Production
