### ISSUE TITLE
Tutor sends course data to Salesforce

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#304]
### Description
Currently, we send Tutor enrollment data to Salesforce so the team and leadership can see what our semester-over-semester stats look like. Sometime before the start of last semester, the course information was changed to section information. GRR from Carly.

The section information is nice to have, and I anticipate it will be nice when we have more high school users. However, I would really like course information to easily compare data across semesters (since that is what we've always used) 

Here is the SF report:
https://na48.lightning.force.com/lightning/r/Dashboard/01Z0B000000WDEVUA4/view

### Acceptance Criteria

SF user can view Tutor data by course or by section. 
Other SF data from Tutor remains the same

### Acceptance Tests

**categories**: SF data transfer
> GIVEN That a course is created in Tutor by teacher A and it has C students  
> WHEN a user views the SF Tutor dashboard or report  
> THEN the user should see that teacher A has one course and the course has C students  

### Checklist for Done
1A-PRE DESIGN
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete

1B-DECOMP
  - [ ] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [ ] Estimate is updated for the work item issues.
  - [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [x] Distilled acceptance tests are added to the issue.
  - ~[ ] Automated testing criteria are added to issue.~
  - [ ] The solution is updated.

2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [x] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
There were two changes made that caused this.  the first was in the salesforce gem:
https://github.com/openstax/openstax_salesforce/pull/14

And then tutor was modified to use that:
https://github.com/openstax/tutor-server/pull/1776

**Comment by reedstrm** [comment]
@carlycurran You're going to have to walk me through the dashboard, to show me what dat is there and what data you expected. I'm not seeing the problem from a first look at the dashboard and reports behind it.

**Comment by reedstrm** [comment]
Checking w/ @carlycurran re: what exactly is missing. This _might_ be a @denvergreene issue, actually (I don't see _missing_ data, per se, perhaps a need to aggregate differently for some reports)

**Comment by reedstrm** [comment]
Seems it's going to be both @denvergreene and me, probably.

**Comment by reedstrm** [comment]
Deeper dive turned up that the course ID and course uuid _are_ stored in SF for each section/period record, as "External ID" and "External UUID". Some older records seem to be missing these values, we'll look into a data cleanup (getting those transferred in bulk), and reworking the dashboard queries to aggregate/count courses, rather than periods.

**Comment by reedstrm** [comment]
[course_period_uuids.csv.txt](https://github.com/openstax/tutor/files/3010628/course_period_uuids.csv.txt)
[course_period_uuids_no_name.csv.txt](https://github.com/openstax/tutor/files/3010630/course_period_uuids_no_name.csv.txt)

**Comment by reedstrm** [comment]
@denvergreene See above comment w/ csv versions of thre id and uuid. I also included the course name for sanity checking on thirst set. Note that there are a bunch of courses at the end w/ no periods attached - they seen to be concept-coach related, in most cases.

**Comment by Malar-Natarajan** [comment]
No code changes to tutor

**Comment by denvergreene** [comment]
@reedstrm I've updated Carly's dashboard. Not sure how to reflect that in this card
