### ISSUE TITLE
A training wheels tip for the dashboard will lead the user to a blank page if they click the X (close) or Next button.

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#307]
### Description
If a new or existing user goes through the training wheel page tips for the dashboard, eventually they will have the option to chose Next. When Next is clicked, the page after is completely blank. 

User: teacher01 (occurs with any new/existing instructor)
Course: Occurs with any course, including preview courses. 
Environment: Issue has been seen in QA, Staging, and Prod 

**To Reproduce**
Steps to reproduce the behavior are
1. Log into Tutor as an instructor
2. Click on any course (if no courses are available click a preview course)
3. In the Dashboard, clock the Help drop down and select Page Tips
4. A Dashboard training wheel page tip should pop up, click Next
5. Notice how the next page is blank

**Expected behavior**
All buttons the training wheel page tips have lead to the correct page that is fully populated. There are no blank pages or broken links.

Video:
https://drive.google.com/open?id=1H_rc5DYMG25m9EMe1qyr4z9KmF0pHEoZ

**Screenshots**
Blank Page:
![Screen Shot 2019-03-26 at 12.44.56 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/77ec1f9d-4256-420e-9364-de4774046974)

Page Tip that causes issue:
![Screen Shot 2019-03-26 at 1.01.49 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/b06f67ee-40ef-4519-a12a-2c3beb8cd099)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: chrome, safari, firefox
 - Version: 73.0.3683.75, 12.0.3, 66.0

**Smartphone (please complete the following information):**

**Additional context**
- This occurs for new and existing users.
- Once the issue occurs the only way to get the pages back are to Refresh the page, or type in the url link.
- Trying to go to the previous page only presents the user with another blank page. Continuing to click back will result in more blank pages until the user gets to the Tutor log in screen.

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [x] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by carlycurran** [comment]
@nathanstitt I know there is a ton of stuff going on, so I think we can hold this if needed. But if there is time, can you or BrittanyJ get this into this release?

**Comment by nathanstitt** [comment]
sigh.. I investigated this and it no longer does the "white page" behavior.  however there is a bug that's re-surfaced where the TW's that point to menu options are mis-aligned.  I meant to PL that in scrum and discuss if we want to re-use this card or make a new one for that

**Comment by carlycurran** [comment]
I just heard from Dani that she is seeing the white page behavior :(

**Comment by nathanstitt** [comment]
really?  What browser and user account?

**Comment by carlycurran** [comment]
LOL: Firefox, under email xwdwpkqm@sharklasers.com

**Comment by nathanstitt** [comment]
FIREFOX! :shake-fist:  ok, i'll take a look

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
