### ISSUE TITLE
Research: Give Research their own database without PII to query 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#31]
# Description

As a researcher, I want to be able to add a research label to any assigned task step, and I want these labels included in research data exports. I also want the one massive research export to add columns for protocol name, study name, cohort name, and research_identifier.

- T3.04.Mip.03 (in old epic doc)
- Initial hours estimate: (4/6/8)

# Acceptance

# Epic Doc

https://docs.google.com/document/d/1E2CzBNf__8O-pvpzaomUbwzndyCjJM95h3oYzda-d6g/edit#heading=h.l1dcs6g8r6ko

**Comment by nathanstitt** [comment]
Should the export include the task steps manipulated?  That'd make the export huge though, so maybe we shouldn't

**Comment by carlycurran** [comment]
@nathanstitt, research does want to know which task steps received a manipulation. And they are okay with a biggg export :)

**Comment by mmmcglone** [comment]
@nathanstitt @carlycurran just chiming in here... I think what we want to see if a label that would identify a task step as being part of a study. I'm not sure what our exact possibilities are.

**Comment by nathanstitt** [comment]
yeah, I can see that our study brain could add a flag to the step's JSON and then we'll add some FE code to see that flag and display and indicator on the steps.  Maybe a little icon at the top right like the "Personalized" steps have?

**Comment by nathanstitt** [comment]
@mmmcglone what's your preference for export format?  I see that surveys used CSV.  Do you have the capability to read sqlite files?  I find that's usually a better choice if you are planning to read the file with any kind of programming language.

**Comment by mmmcglone** [comment]
The files will be read in R by the research team. Are you thinking that this will be a separate export from the main Tutor data frame export? Initially, I think our preference was that these would just be labels added to the existing Tutor export, but it sounds like it needs to be it's own thing. It might be best to get you to speak with Phil or Drew directly about this so we all get on the same page.

**Comment by nathanstitt** [comment]
Waiting on https://trello.com/c/ucA5MwRt/178-periodically-dump-an-anonymized-tutor-db-to-a-research-server to implement periodic backups
