### ISSUE TITLE
APUSH on tutor-content fails to load exercises

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#314]
### Description

APUSH on tutor-content (which links to exercises prod), fails to load exercises 

Slack conversation on the issue: 
https://openstax.slack.com/archives/C1GEF8S0N/p1553707380033900

**To Reproduce**
Steps to reproduce the behavior are
1. Go to tutor-content.openstax.org 

**Expected behavior**

**Desktop (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
I remove the `openstax` default for collaborators and was able to import exercises successfully. https://github.com/openstax/tutor-server/blob/master/app/subsystems/content/routines/import_exercises.rb#L16

The question then becomes how to modify exercises to add openstax as a collaborator to the wise wire account,  and/or update all the exercises they've created to be owned by openstax.

**Comment by reedstrm** [comment]
Discussions w/ stake holders has lead to a two-pronged approach: do a in-DB update of the existing WW authored exercises to set Copyright-holder == OpenStax, to solve the immediate problem. To avoid it happening again in the future, make a change to exercises user model to have a "work-for-hire" account type, where the copyright-holder is != the user account, then set _that_ for WW (and other vendor accounts, as needed)
