### ISSUE TITLE
AP Physics - get the number of questions tagged to each chapter

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor#316]
### Description
AP Physics - get the number of questions tagged to each chapter

### Checklist for Done
1A-DEFINE
- [x] Description is complete

**Comment by nathanstitt** [comment]
The count for this is **0** - we don't have AP Physics as an option on the book selector

**Comment by nathanstitt** [comment]
chapter section exercise counts:
https://drive.google.com/file/d/1f_5w6oBI5pfWmH_hD7SjQGEbiiXAnm7K/view?usp=sharing

**Comment by Brooke-Fail** [comment]
Data has been collected and given to content team.
