### ISSUE TITLE
CZI Pilot: AP Learning Objectives Input, QA, and Editing

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#317]
### Description

We need a new AP Learning Objectives field to accept AP learning objectives for AP Bio and AP Physics (CZI Pilot books).

Additionally, we need a way to edit the _existing_ AP Learning Objectives tagged to the AP Bio assessments.  Let me know if this should be a separate card.

### Acceptance Criteria
- editors in Exercises (offshore production teams or content managers) can input and edit AP learning objectives in the following formats:
1. **AP Bio:** `#.#` or `#.##` (example: `2.4` or `4.25`)
2. **AP Physics:** `#.[letter].#.#` (example: `3.A.2.1`)

The numbers are always numerals (1-9) and the letters are always uppercase (A, B, C, etc.).

- learning objectives are added to the list of tags that display in the Question Library in Tutor.
-  In the display, learning objectives are prefixed with `aplo` so that instructors can easily identify what they are.
- editors in Exercises can edit or remove aplos currently tagged to (some, not all) AP Bio assessments.  They all have "aplo" in the tag.  They were applied via a spreadsheet in 2015 :-)
- We can assign multiple APLOs to each assessment.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-PRE DESIGN
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
  - [ ] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [ ] Estimate is updated for the work item issues.
  - [ ] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by openstaxalina** [comment]
#### Reference
AP Course and Exam Description documents that provide more information about learning objectives:
AP Bio: https://secure-media.collegeboard.org/digitalServices/pdf/ap/ap-biology-course-and-exam-description.pdf
AP Physics: https://secure-media.collegeboard.org/digitalServices/pdf/ap/ap-physics-1-course-and-exam-description.pdf

**Comment by openstaxalina** [comment]
Timeline: If we are going to input the APLOs onto the assessments by end of Q2, we need this available in the June 18 release.  cc @carlycurran

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
