### ISSUE TITLE
Book styling issues with 3/29/code freeze

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#318]
### Description
Book styling issues with 3/29/code freeze

1. The chapter & section titles are not displayed
2. The book used to display in a frame which is not now the case

See screenshots with QA & staging compared
https://drive.google.com/file/d/1Mhmc-Obvyncuh-0A0NlilUl3R8Z13Dhk/view?usp=sharing
https://drive.google.com/file/d/1guP5vjTyQTRfMg-YvgZmOP33CyzbNdi1/view?usp=sharing

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
Looks like this was fixed somewhere along the line. it now appears as the screenshot for me

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/7c39cc15-7439-4940-8606-b5c86c0c4bbd)

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
