### ISSUE TITLE
Bug: Exercise errors out when detailed solution is removed

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#32]
# SCENARIO 
Create a new exercise (open ended or multiple choice or true/false). Do not enter any value in the Detailed solution and click save. Exercise saves successfully.

Create a new exercise (open ended or multiple choice or true/false). Enter some value in the Detailed solution and click save.
Error 422 is displayed

Detailed solution is not a mandatory field and works fine if we never entered any value into it. But if we enter a value and then remove it, the error 422 is displayed.

# Steps to Reproduce the issue

Product
` [ ] ` Accounts ` [ ] ` BigLearn
` [X] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [ ] ` Tutor
` [ ] ` Highlight ` [ ] ` Web
User Type
` [X] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
Username 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [X] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [X] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**

**Comment by Malar-Natarajan** [comment]
Verified in QA
