### ISSUE TITLE
Difference in the size of the frame for the FR step vs the question step, as a result the back arrow button is offset a bit

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#325]
### Description
Difference in the size of the frame for the FR step vs the question step, as a result the back arrow button is offset a bit

![Screen Shot 2019-04-04 at 11.52.21 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/89f3b305-480f-44cf-99e2-89ba1ecf7058)

![Screen Shot 2019-04-04 at 1.38.48 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/f17fbce7-02d4-4abf-95b8-d0a424dfb37c)

![Screen Shot 2019-04-04 at 1.44.03 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/61d3360c-a2be-44f1-add4-1b6e466145da)

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
sorry @Malar-Natarajan I'd fixed this in https://github.com/openstax/tutor-js/pull/2557 I didn't know you were filing the card

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
