### ISSUE TITLE
Tag AP Bio and AP Physics questions with APLO metadata

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor#328]
### Description
Tags for AP assessments: 

https://docs.google.com/spreadsheets/d/10YJ8pMUAUUSgLJBtqI-XH98ejJg9DMcwY6PqqULBh-I/edit#gid=123315978

https://docs.google.com/spreadsheets/d/1XQ1bRwDCxEyjgU2zYG8MdJ6KKPgU6Vmzqugd9nhgz7g/edit#gid=123315978

### Acceptance Criteria
AP assessments are tagged according to the spreadsheets above. Tags can be edited in the exercises editor. 

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated

1C-DESIGN
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

**Comment by Brooke-Fail** [comment]
Verified in Production.
