### ISSUE TITLE
Bug: Sims scroll bar not working towards left side in reference view

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#33]
# SCENARIO
Sims scroll bar not working towards left side in reference view 
Refer screenshot. The scroll bar cannot be moved to the left side
Chapter 2.4 - Physics

# Steps to Reproduce the issue

- **Product:**
` [ ] ` Accounts ` [ ] ` BigLearn
` [ ] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [X] ` Tutor
` [ ] ` Highlight ` [ ] ` Web
- **User Type:**
` [X] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [X] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [X] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [X] ` Chrome ` [X] ` Firefox ` [X] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**
User cannot see left side images in reference view when the window size is small

----------------
**Images or Screenshots** (_attach below_)

**Comment by carlycurran** [comment]
![image.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/4fe69c14-2309-4be4-a9be-73fe98ed1266)

**Comment by Malar-Natarajan** [comment]
Verified in QA
