### ISSUE TITLE
PE & SPE badges (the small icons on top of the assignment) & the value prop cards (for PE & SPE) are not displaying in the assignments

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#339]
### Description
PE & SPE badges (the small icons on top of the assignment) & the value prop cards (for PE & SPE) are not displaying in the assignments

Badges not displaying in the existing users asssignments
https://tutor-qa.openstax.org/course/2424/task/378007/step/5 . student05

New student enrollment: Badges & value prop cards not displayed for PE & SPE
https://tutor-qa.openstax.org/course/2419 . mn45+7689@rice.edu

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
Based on my reading of the value prop card behavior in the behavior doc: https://docs.google.com/document/d/1So9OiQmbDDXVrbGnjgAQzuPFkZM7enCwlBmJduu9Mto/edit#heading=h.44f2y33fsba2 I believe the two-step info cards are supposed to only show up for users ONCE, and then not appear again.  However it's quite possible that that's not the correct rule

If you reset the user's settings by pasting the below into the console you'll see they do show up:
`_MODELS.settings._reset()`

**Comment by Malar-Natarajan** [comment]
@nathanstitt 

SPE badge & SPE value prop card is not displayed for reading/HW assignments. This is a brand new student.
https://tutor-qa.openstax.org/course/2471/task/378507/step/32 .  mn45+65787@rice.edu
https://tutor-qa.openstax.org/course/2471/task/378509/step/6 . mn45+65787@rice.edu

PE badges are displayed but PE value prop cards are not displayed. Please refer the same assignments/course in the above example links

![Screen Shot 2019-04-15 at 4.29.10 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/e9945080-c4fc-41bb-8fa7-7cfebea620e4)

**Comment by nathanstitt** [comment]
@Malar-Natarajan 

I see the personalized questions value prop breadcrumb and card displayed property 
![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/e84f1bd1-93d6-4b76-99c5-f0d06211cd8e)

However! I'm having trouble finding any spaced practice steps in an assignment.

Can you point me toward a student and assignment that has some?

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
