### ISSUE TITLE
Bug: Highlights made in Reading are not available in Reference view

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#34]
# SCENARIO

Highlights made in Reading are not available in Reference view

# Steps to Reproduce the issue

1. Login as student (eg. student15)
2. Start a reading assignment and highlight some content
3. The highlighted content is present in the Summary view.
4. Now, either immediately or logout and login in another private window and verify that the content highlighted in Reading view is present in the Reference view

Issue: The content highlighted in reading view is not available in the Reference view summary page or the book page 

- **Product:**
` [ ] ` Accounts ` [ ] ` BigLearn
` [ ] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [X] ` Tutor
` [ ] ` Highlight ` [ ] ` Web
- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [X] ` Student  ` [X] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [X] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [X] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**
User will data highlighted from reading view

----------------
**Images or Screenshots** (_attach below_)

**Comment by nathanstitt** [comment]
I'm unable to replicate this.  My guess is that it's something specific to the content that was highlighted. Please provide the chapter/section and exact phrase that was used.

![Screen Shot 2018-10-10 at 1.35.01 PM.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/ed5ac3ea-c512-4ef8-acee-1449faec74cf)

to:
![Screen Shot 2018-10-10 at 1.35.18 PM.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/74f8f681-9116-4bb4-86bc-d5941e6dcaef)

**Comment by Malar-Natarajan** [comment]
Unable to recreate.
