### ISSUE TITLE
Reading assignment has intermittent 422 and BL spaced practice issues

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#340]
### Description
Description
![Screen Shot 2019-04-08 at 12.15.40 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/da5b7526-0d9c-42b6-a0b4-940016540d48)

![Screen Shot 2019-04-08 at 12.16.45 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/9182f4c1-4641-4ec8-a67b-be964d2e7bf7) Go to '...'

![Screen Shot 2019-04-08 at 12.17.25 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/5dcaeb11-f76f-41ff-8146-f7eb4db515e1)

https://tutor-qa.openstax.org/course/2479
used student25 (but all of their assignments are now complete)
https://openstax.slack.com/files/U0F58C65R/FHT6L9T0E/untitled.mov

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
@itsgeraldwang @ejp3 will y'all please check into this and see if you can reproduce? Want to make sure this is not happening now or after SPARFA deploy :)

**Comment by ejp3** [comment]
I have not been able to reproduce this bug

**Comment by carlycurran** [comment]
Nathan thinks this was caused by a BE error with study brains code. 

Ross: an unreproducible bug in code that has changed significantly
