### ISSUE TITLE
Slow Updating when Adding Questions to Assignment in AP Physics

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor#344]
### Description
Slow Updating Time when Adding Questions to Assignment in AP Physics

**To Reproduce**
Steps to reproduce the behavior are
1. Create an assignment 
![image](https://user-images.githubusercontent.com/32039186/55750137-4972a880-5a08-11e9-80ee-dbae30de0d1e.png)
2. Click on the chapter to be assigned
![image](https://user-images.githubusercontent.com/32039186/55750416-d74e9380-5a08-11e9-9641-5e8519c6311f.png)
3. Scroll down to "show problems"
![image](https://user-images.githubusercontent.com/32039186/55750436-e6354600-5a08-11e9-8966-597530a954b7.png)
4. As I select a problem on the screen:
![image](https://user-images.githubusercontent.com/32039186/55750478-ffd68d80-5a08-11e9-85e9-99ffadadcad7.png)
selected; as one can tell from the "remove" botton as mouse hovers back to the problem
Notice that there is no update on the number of "my selection"
<img width="1009" alt="Captura de Pantalla 2019-04-08 a la(s) 2 04 14 p  m" src="https://user-images.githubusercontent.com/32039186/55750544-23013d00-5a09-11e9-8900-830eb92d765c.png">
5. Then, the feedback on the number of problems selected and the "next" button to proceed eventually shows up, but it takes more than 2 minutes from the previous screen to the current one:
<img width="1187" alt="Screen Shot 2019-04-08 at 1 47 31 PM" src="https://user-images.githubusercontent.com/32039186/55750713-7f645c80-5a09-11e9-86e2-92beaf66b78a.png">

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
@itsgeraldwang @Brooke-Fail can y'all check into this and see if there's still a problem here, please?

**Comment by Brooke-Fail** [comment]
@carlycurran I'm not getting this issue to occur. I think Nathan might have fixed is with the 10-15 second delay PR. I tried in multiple browsers too.

**Comment by carlycurran** [comment]
Great!! THanks for checking. I'm going to close this.
