### ISSUE TITLE
Intro part of the MPQ is not displayed in HW assignments for the student

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#347]
### Description
Intro part of the MPQ is not displayed in HW assignments for the student

https://tutor-qa.openstax.org/course/2419/task/378233/step/1 student10

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**
![Screen Shot 2019-04-10 at 9.52.49 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/18741e9c-8232-41b5-b6a7-27ec13f375ac)

![Screen Shot 2019-04-10 at 10.00.58 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/3e98108c-1d8a-4a9d-8693-352724dc5b99)
**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
