### ISSUE TITLE
SIM issues with reading

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#349]
### Description
1. SIM in reading step display as link instead of the SIM

2. Question library is not showing the "interactive" icon in the card view but in detailed view the sim is shown as link and not the SIM. If we assign the section in a reading, there is neither a sim link nor the SIM

https://tutor-qa.openstax.org/course/2419/task/378224/step/13 student10 (QA)

https://tutor-qa.openstax.org/course/2491/questions# . teacher02, exercise Id 12965

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

![Screen Shot 2019-04-10 at 11.49.34 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/532b94f4-a47c-4485-9003-80c6c2374967)

![Screen Shot 2019-04-10 at 3.20.40 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/b4df9082-c053-4193-97e6-f3771631b749)

![Screen Shot 2019-04-10 at 3.20.19 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/27db486e-3dcf-4442-9446-e38b607251fd)

![Screen Shot 2019-04-10 at 12.00.33 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/10bb1d75-9646-4793-b1a8-69e591556198)
**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
@nathanstitt  The Interactive Icon is still not showing up on cards in the questions library. 

Screenshot: Card View
https://drive.google.com/file/d/1COMZUOKgxlwqD5IVuCByZTNKMqoKZrH6/view?usp=sharing

Screenshot: Detail view
https://drive.google.com/file/d/1PJ7e2ttVgDcwQh0GnLBjGerJ7RbigGDR/view?usp=sharing

**Comment by carlycurran** [comment]
This question has been documented and excluded from OpenStax Tutor
