### ISSUE TITLE
Bug: assignments are getting added to the student history before the spaced practice is populated

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#35]
# SCENARIO

On staging some homework had this Biglearn spy info:

```
{"ecosystem_id"=>269, "ecosystem_title"=>"College Physics with Courseware (405335a3-7cff-4df2-a9ad-29062a4af261@6.220)", "history_type"=>"student_driven", "assignment_type"=>"homework", "exercise_algorithm_name"=>"local_query", "task_history"=>{"0"=>{"task_id"=>1386681, "task_uuid"=>"da579f41-30b1-48ab-861c-85cb2b93dad8", "cnx_page_uuids"=>["db8565be-8542-460c-86d4-096b505cac5a", "59467866-4818-476c-affa-f56028c78f0c"], "book_container_uuids"=>["1eb3384d-ae3d-4619-84df-01d4e0337907", "3544793c-d92b-474e-94f7-44b84b2765fd"]}, "1"=>{"task_id"=>1386677, "task_uuid"=>"c618947d-e7f1-48bc-bb30-b26272e8fdbe", "cnx_page_uuids"=>["1b79a450-f691-4301-aef3-d065268ab4a9"], "book_container_uuids"=>["7e41c92b-7b63-41a0-8a27-15ddde94c519"]}, "2"=>{"task_id"=>1386682, "task_uuid"=>"b03de5b0-fcd7-47a3-aed4-be2b99a71247", "cnx_page_uuids"=>[], "book_container_uuids"=>[]}, "3"=>{"task_id"=>nil, "task_uuid"=>nil, "cnx_page_uuids"=>[], "book_container_uuids"=>[]}, "4"=>{"task_id"=>nil, "task_uuid"=>nil, "cnx_page_uuids"=>[], "book_container_uuids"=>[]}, "5"=>{"task_id"=>nil, "task_uuid"=>nil, "cnx_page_uuids"=>[], "book_container_uuids"=>[]}}}
```

However, task 1386677 did not yet have Spaced Practice, even though it is in the student history above.
```
Tasks::Models::Task.find(1386677).spes_are_assigned
=> false
```

This is not the expected behavior. Also, the page uuid for task 1386682 in the spy info is missing.

# Steps to Reproduce the issue

- **Product:**
` [ ] ` Accounts ` [x] ` BigLearn
` [ ] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [X] ` Tutor
` [ ] ` Highlight ` [ ] ` Web
- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [x] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** student10
- **URL:**  https://tutor-staging.openstax.org/course/3946
- **Course number:**  3946
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [X] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**
Wrong spaced practice

----------------
**Images or Screenshots** (_attach below_)

**Comment by Dantemss** [comment]
Seems like having SPEs assigned is not necessary for tasks to be in the student history. According to the current code, assignments need to either be completed (except spaced practice questions in the assignment) or past-due to be added to the student history.

**Comment by Dantemss** [comment]
So it seems the scheduler algorithms are working as intended.

**Comment by carlycurran** [comment]
Here's the original scenario: 

HW01 - due Sep 21, 7 am - ch 1.2 - Not answered by the student10 (not even any student in the course)
Ch 1.2 is not in any other reading/HW
HW exclude (the one with 7 questions) - due sep 22 - has 1 SPE from ch 1.2

Why this is NOT a bug: 
Students _can_ get spaced practice from assignments that are past due, even if they did not complete them. If the skip a HW assignment, we think they should still get practice questions from that section, as it is being covered in class. 

Closing this bug.
