### ISSUE TITLE
Fix drop RoleUsers migration so it doesn't delete courses

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor#361]
### Description
All QA courses were deleted for existing users.

### Acceptance Criteria
Migration doesn't delete courses 

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else 

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items

**Comment by dkhowala** [comment]
Old research work: 

• https://docs.google.com/spreadsheets/d/1rT68_PaExPYIfhrxGyVPwu-c0hwlZRAIpH9ZI7haJBQ/edit#gid=1510798108

• https://docs.google.com/document/d/13fNavGQFSk9a4ZpXe_U1XNktZa6FyA8OB0B5WE_FyPU/edit

**Comment by dkhowala** [comment]
‘View as a Student’ - Instructor Interview planning doc: https://docs.google.com/document/d/1B6d19LEtqJpbojkmsMuXFdnIzqMCkqq316GMh8YPOpc/edit#heading=h.8imk8jnrq70a

**Comment by dkhowala** [comment]
https://drive.google.com/open?id=1B3UOcaI4LkhB4cT1pEN2uY8CQaQ5vjGx

The first draft for the Student view mode, You can leave your comments on the PDF if you want.
@carlycurran @nathanstitt

**Comment by Brooke-Fail** [comment]
All data is present, closing.
