### ISSUE TITLE
Extend exercises user model/workflow for work-for-hire

### ISSUE THREAD

**Issue by reedstrm** [openstax/tutor#362]
### Description
As a content vendor I want my account to reflect my "work for hire" status so that exercises I create have the proper Copyright holder, automatically.

### Acceptance Criteria
An administrator is able to mark an account to indicate that it is in fact used for creating content for another copyright holder, and assign that rights-holder
When that account is used to create exercises, they have the correct copyright holder, by default.

- Vendors must be able to edit their assessments throughout content production (could go 18-24 months)
- Vendors must be able to QA their assessments in a Tutor production-like instance (tutor-content.openstax.org) throughout content production
- At the end of vendor assessment creation, we want to take over ownership of the assessments (done at the book level, en masse) so that vendors can’t make any more edits (and OpenStax can)
**Decision: We will add two authors (OSX and vendor) and remove vendor when they are done. Will add a screen where you can drop an author for an entire account.** 

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Discussion Doc
**Decisions in bold**
https://docs.google.com/document/d/11IrMl7Y5_r9zzSqu0gbCmowAcLFcJlRAyW8gcTtD_NA/edit#

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [x] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by carlycurran** [comment]
@reedstrm is this covered in https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/366  ?

**Comment by carlycurran** [comment]
@Dantemss FYI, I added a link to our discussion doc (from last week with Alina) in this issue, and I also added the acceptance criteria we talked about with her!

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
After further testing and clarification, the only issue seems to be that the update permissions are not working. With that being the only issue, this card is good to be released. 

Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
