### ISSUE TITLE
Extend tutor import to allow designating allowable exercise owners

### ISSUE THREAD

**Issue by reedstrm** [openstax/tutor#363]
### Description
There exists a hard-coded filter, such the ecosystem import will only use exercises that have 'openstax' as a collaborator (author or copyright holder)

To resolve this, as a  tutor admin, when importing an ecosystem, I want to be able to specify acceptable exercise authors, in the ecosystem YAML file, to allow creating courses that draw from multiple exercise authors.

### Acceptance Criteria
Add a non-openstax author to an ecosystem YAML manifest, and import it. Exercises tagged for that book, by that author, are included.

### Acceptance Tests
**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
I think this was taken care of in another card, so closing here.
