### ISSUE TITLE
LMS launch error (BB at KU)

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#365]
### Description
Blackboard users at KU cannot launch from their LMS. 

KU cloned their production Blackboard system, and may be causing the LMS to report two different tool consumer ids.  A “tool consumer” is what an LMS system is called.
   - When we attempt to create an LTI context,  it fails with “course keys already in use” error, since it finds that an LTI context for that ID already exists.
   - To support the multiple tool consumer situation, we’re going to lift the restriction that only one LMS context (that’s usually a course on the LMS side, but sometimes a section) can point to a single tutor course. Now it will be possible for multiple LMS sections to point to a single tutor course, though we are NOT going to change our guidance for teachers right now.

**To Reproduce**
Not reproducible on our system

**Expected behavior**
Students can launch from BB without receiving course in use error.

### Acceptance Tests
- LMS user (previous) can launch from LMS into Tutor course
- teacher can launch from LMS into Tutor course 
- Teacher can sync scores
- New teacher can integrate multiple LMS courses or sections with one Tutor course

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [X] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [X] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- ~If UI changes, UX reviews and verifies.~ 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by bonnebbrown** [comment]
Work around for students who are unable to log in to Tutor because they forgot their password and are not receiving the password reset email to their KU email address. CS asks for an alternative email, we add it to their account profile in accounts and then ask them to click on the reset email link again.

**Comment by Malar-Natarajan** [comment]
Verified in staging
