### ISSUE TITLE
Phet sim not pulling into exercise

### ISSUE THREAD

**Issue by oscryan** [openstax/tutor#367]
### Description
The simulation is not pulled into https://exercises.openstax.org/exercise/12314 despite correct cnxmod and feature id tags.

**To Reproduce**
Steps to reproduce the behavior are
1. Go to https://exercises.openstax.org/exercise/12314
2. Notice no phet simulation visible.

**Expected behavior**
embedded phet

**Screenshots**
<img width="1344" alt="Screen Shot 2019-04-12 at 4 02 14 PM" src="https://user-images.githubusercontent.com/1895432/56066091-5fe86f00-5d3c-11e9-8e7a-113a7e11d247.png">

**Additional context**

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
Looks like this is not showing up in exercises preview -- exercises doesn't have the book content to bring it in for a preview. 

@oscryan, I think you need to review in tutor-content. (Question Library or assignment builder)

Is this tagged for the right page and does the page have a sim? We don't see that sim on the page it's tagged to. 

To add an assessment for a sim not in the content, you'd have to embed the sim directly in the exercise.

**Comment by oscryan** [comment]
Looks like this is one of the jar sims. I tried to embed it, but there doesn't seem to be an html version. Not sure what to do. I can embed the screenshot/download option, but people will still be confused because the .jar must be downloaded to use the sim.

**Comment by oscryan** [comment]
It is in here, which it is tagged to: https://cnx.org/contents/QFM1o3z_@7.3:JJvbX5Ax@5/11-6-Gauge-Pressure-Absolute-Pressure-and-Pressure-Measurement

And it's in the question here https://tutor-content.openstax.org/qa/542/11.7

**Comment by carlycurran** [comment]
@carlycurran  will get an intern to see if there's an HTML 5 version of this sim.

**Comment by oscryan** [comment]
@carlycurran there is not, or I would have replaced it in the book already.

**Comment by oscryan** [comment]
https://phet.colorado.edu/en/search?q=gauge+pressure

**Comment by carlycurran** [comment]
we've excluded questions with .jar sims
