### ISSUE TITLE
notes aren't showing up on the highlight print preview

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#369]
### Description
Description

When printing the highlights/annotations, the user-entered notes aren't showing up. The paragraph (note) element after the block quote (highlight) is empty.

**To Reproduce**

make an annotation
view the highlights summary page
click the 'Print this page' button

**Expected behavior**

highlights and notes are displayed on the print preview/printed page

**Screenshots**

![Screen Shot 2019-04-15 at 4.20.34 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/28f529dc-103c-4a98-8add-e7fc5782098b)

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
