### ISSUE TITLE
Bug: Clicking "Preview Only" before saving an assignment for the first time leads to this error.

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#37]
## SCENARIO
Clicking "Preview Only" before saving an assignment for the first time leads to this error. A simple fix would be to disable the preview button until you save.

Identified by Dante during regression testing

## Steps to Reproduce the issue

- **Product:**
` [ ] ` Accounts ` [ ] ` BigLearn
` [X] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [ ] ` Tutor
` [ ] ` Highlight ` [ ] ` Web
- **User Type:**
` [X] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [X] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by carlycurran** [comment]
![image.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/7a3c556e-1bd7-4a84-85a0-fb16a452d9df)

**Comment by Malar-Natarajan** [comment]
Preview button is removed from nav bar. So this issue is not applicable now.
