### ISSUE TITLE
The Training Wheels that point to menu options are mis-aligned

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#370]
### Description
Description
The training wheels for the teacher and student dashboard menu options are mis-aligned and point to the wrong spot on the page when they pop up. This is also happening with any preview course.

User: Occurs with any teacher account (tt02)
Page: any Teacher Dashboard (https://tutor-qa.openstax.org/course/2486/t/month/2019-04-15)

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor as an instructor
2. Click on any course
3. If the training wheels do not pop up, click on the Help drop down and select Page Tips
4. Click Next 
5. Notice how the first tip is mis-aligned before is snaps to its proper position 

**Expected behavior**
All the training wheels and tips are aligned and point to the correct part of the page the tip is referring to.

**Screenshots**
![Screen Shot 2019-04-16 at 9.18.06 AM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/165d4be0-f5ba-4b5d-8b65-073cf51137db)

Video:
https://drive.google.com/file/d/1COy7JP6kvzyz52irHd9tIdLiI8d11lS3/view?usp=sharing

**Additional context**
- Occurs on all browsers (Chrome, Safari, Firefox, including Incognito and regular viewing)
- Occurs every time the training wheels are triggered

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
This issue also occurs with the training wheels for students. 

Video: 
https://drive.google.com/file/d/1RmGbP2baqYcEmc-44FNYn6T5ezzn2Eya/view?usp=sharing

**Comment by itsgeraldwang** [comment]
This might be occurring because the popup is set to be on top of the object before it's animated to a different location. So, for example, the first error on the video the reason for that is prob because it populated the training card onto the object as the object was sliding into view. I assume the object had a hidden tag or something then unhides it as it's slid into view.

**Comment by gregfitch** [comment]
![Screen Shot 2019-06-10 at 4.40.37 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/7ccb33d7-7a29-45eb-b6a3-3ff2c63abe5c)

New course wizard completion

**Comment by nathanstitt** [comment]
This is somewhat better but the menu's are still not quite right

**Comment by Brooke-Fail** [comment]
Training wheels throw errors. There are a lot of route errors, which can be tracked here:
https://github.com/openstax/tutor/issues/606.
Will verify this card when 606 is fixed.

**Comment by Brooke-Fail** [comment]
There is a problem while closing the preview and create a course tips. Also the preview course modal stays even after the page tips are completed.

video:
https://drive.google.com/file/d/1nVcGOju0jjeLbX1eKrDqxH9x9NO3iUI4/view?usp=sharing

**Comment by Brooke-Fail** [comment]
The preview course and new course page tips are still triggering again after all the tips have been completed.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
