### ISSUE TITLE
reading steps have extra white space between title and on-page elements

### ISSUE THREAD

**Issue by nathanstitt** [openstax/tutor#373]
![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/6903899e-5119-418f-b28c-69d3a55e5c68)

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/e6eff121-06d0-48e1-98ed-8293b54d2fd2)

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
