### ISSUE TITLE
For new enrollments, SPE value prop card appears and then throws "Step unavailable" error and none of the assignment has SPE questions

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#374]
### Description
For new enrollments, SPE value prop card appears and then throws "Step unavailable" error. If we reload or navigate back to dashboard the steps load fine.

Please enroll new student in https://tutor-qa.openstax.org/enroll/419551/Biology-2e-0517-copy-Spring-2019 if you want to see the behavior. I did assignments in this order. Read0410-1, HW & HW01 with these students mn45+567676@rice.edu & mn45+7546@rice.edu. When I do HW, the error appears.

More interesting is, I did not get any SPE's in any of the assignments. Why is k-ago always zero for al the assignments?

Both these videos are the same issue. One is reload from assignment page another goes to the dashboard and comes back to the assignment.

https://drive.google.com/file/d/1cB9bagVFrI7AgKJMf4SzE6k2efhOF3a-/view?usp=sharing

https://drive.google.com/file/d/1_0CfL6UpREfQ67sCwA0DyhgM4lnvupL7/view?usp=sharing

I enrolled student02 for the same course and did assignments in this order HW, HW01. I still get the error on HW and got PE after refreshing the page. And got SPE when I did HW01.
See video https://drive.google.com/file/d/1ykBGKYqdcy3nja_6xRyRdmJxQKT6a4ea/view?usp=sharing

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
per Nathan - re-fetch the entire assignment when it gets to a placeholder step.

**Comment by Malar-Natarajan** [comment]
the issue still happens in staging (step unavailable for SPE) . You can enroll new student in https://tutor-staging.openstax.org/enroll/660713/Biology-2e-03080-copy-Spring-2019 and do assignments in this order Read, HW02, HW01. I got the error while doing HW02. I have been trying to replicate this with different type of assignments and only when I re-did the same pattern as in the zenhub issue description I got this error again...HW01 & HW02 have questions from  overlapping sections

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
