### ISSUE TITLE
Change link color to #027EB5 from #337EB5. #337EB5 fails AA compliance.

### ISSUE THREAD

**Issue by dkhowala** [openstax/tutor#376]
### Description
Description
All links on tutor are in the color  #337EB5 which failed AA compliance. We need to change the global link color on Tutor to #027EB5 to make it in sync with the OS pattern library and pass AA.

**To Reproduce**
See any link on Tutor

**Expected behavior**
All links should pass AA compliance for color contrast

**Screenshots**
![Screen Shot 2019-04-18 at 2.27.24 PM.png](https://images.zenhubusercontent.com/5c12c502ea8fd844ba2fce8c/7aa0e155-07f1-4dc1-9d7a-a2d97bc21556)

**Additional context**
Please check that the link hover and active color follows the pattern library

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified on Staging

**Comment by ejp3** [comment]
Verified in Production
