### ISSUE TITLE
Noticed `undefined` in the progress column for an assignment while closing sessions that was inactive for a long time (may be 18 hrs)

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#377]
### Description
Noticed `undefined` in the progress column for an assignment while closing sessions that was inactive for a long time (may be 18 hrs).
Re-login displayed the progress correctly though.
https://tutor-qa.openstax.org/course/2549 . student02

**Developer notes:** As per Nathan "we’re not setting a default for the progress so if the BE ever fails to send that, probably because of a network timeout or something, it’d show the `undefined`"

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**
![Screen Shot 2019-04-19 at 9.15.24 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/a9ee0db5-1f04-4694-9027-d223db3efd1d)
**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
I think this might be fixed, I haven't gotten it to re-occur after leave the dashboard sitting open overnight

**Comment by Brooke-Fail** [comment]
I havent been able to reproduce this, looks verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
