### ISSUE TITLE
Cannot navigate backwards with the arrow key in reading assignment if there is no forward arrow displayed on the page

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#383]
### Description
Using the arrow keys, the user can navigate through a reading assignment. However, the user can not navigate to the previous page via the left arrow key if there is no forward arrow present on the page. 

User: Student10
Page: https://tutor-staging.openstax.org/course/4101/task/1405041/step/119

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor-staging.openstax.org as a student
2. Go to any incomplete reading assignment 
3. Navigate through the reading with the arrow keys, going forward and back every now nad then
4. Using the arrow keys, go to the very end of the reading. Notice how you can not go back with the arrow key since there is no option to go forward.

**Expected behavior**
The user can navigate to the previous and next pages with the arrow keys as long as the corresponding arrow is present on the page. 
EX. If the page only has a forward arrow showing, the right arrow key should work, but the left should not. 

**Screenshots**
Video:
https://drive.google.com/file/d/1mK-_Xtzz58sOuzvto9q4P82CKo8fgUu9/view?usp=sharing

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by itsgeraldwang** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production
