### ISSUE TITLE
Typing in a space is counted as a re-answer. Continuing with a blank answer will result in a 422 error.

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#384]
### Description
Typing in a space as a free response re-answer will allow the re-answer to be accepted and a 422 to be triggered once a letter answer is submitted. 

user: student10
Page: https://tutor-qa.openstax.org/course/2547/task/378635/step/8

**To Reproduce**
Steps to reproduce the behavior are
1. Log into Tutor QA as a student
2. Go to an assignment that has a free response question
3. Type in a space for the answer and click submit
4. Upon re-answer, type in another space and click re-answer
5. Notice how the re-answer is accepted
6. Choose a letter and click answer
7. Notice the 422 error 

**Expected behavior**
The free response re-answer should only accept text input answers. If the re-answer was fixed, the 422 error would not be thrown.

**Screenshots**
https://drive.google.com/file/d/1UJvtqRr6WF-ng2iYaGd3jkMj3IHW4Aor/view?usp=sharing

Video:
https://drive.google.com/file/d/1zZeEH468etj8Z9vaGrjycvtvJDAFHVcp/view?usp=sharing

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
We also want to track the 422 errors we get. Are all 422s caused by blank space?

**Comment by Brooke-Fail** [comment]
@carlycurran 
The ones that I have come across have been due to blank spaces. This is a link to another blank space/422 error:
https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/300

**Comment by carlycurran** [comment]
@nathanstitt plan: a check in Tutor so it’ll treat a space as “empty” meaning it won’t enable the Submit button until non space characters are typed

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
