### ISSUE TITLE
Ability to Add APLO Tags for APUSH

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#385]
### Description
As a production team member working in Exercises, I want to be able to assign AP US History Learning Objective tags to each assessment so that instructors can see these tags (and perhaps Research will run analyses using them).

### Acceptance Criteria
1.  On the Tags tab of the Exercises editor, the exercise editor can add **any combination** (including 2+ HTS, 2+ RP, etc.) of the following learning objectives:

**Historical Thinking Skills**
- HTS-1 Developments and Processes
- HTS-2 Sourcing and Situation
- HTS-3 Source Claims and Evidence
- HTS-4 Contextualization
- HTS-5 Making Connections
- HTS-6 Argumentation

**Reasoning Processes**
- RP-1 Comparison
- RP-2 Causation
- RP-3 Continuity and Change

2. The tags display on the assessment in Tutor (in the Question Library) exactly as shown above, for example: _RP-1 Comparison_.  

_Suggestion: when APUSH is selected as the book, new fields for HTS and RP pop up, each with a dropdown.  HTS would have numbers 1-6 and RP would have number 1-3.  This would be similar to how the DOK and Blooms values are currently assigned._  

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- ~If UX design is needed then the UX label is added~
- ~If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue~
- ~A development approach for the code change, prototype code, or tech brief is done and added to the issue~

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [x] Estimate is updated
- [x] Release is selected

1C-DESIGN
- ~The UX HiFi Design is complete, approved by the Product Manager, and added to the issue~
- [ ]Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by openstaxalina** [comment]
@carlycurran FYI on the above!  I plan to ask on the Friday call whether we are expecting these to show for the fall 2019 pilot.

**Comment by openstaxalina** [comment]
Timeline: Per discussion in scrum, we are targeting the May 21 release for this.

**Comment by nathanstitt** [comment]
## Decomp:

- [ ] HTS & RP fields are added to  exercise editor on the tags tab
    - fields only appears for APUSH book
    - fields have options from list above
    - field contents are saved to server as tags
- [ ] Ensure Tutor server imports the HTS & RP tags (should already do this)
    - Tutor server sends the tags to the front-end along with the exercise (likewise, should work)
- [ ] Tutor front-end displays the tags ONLY in question library and QA view
    - This implies that they're hidden in HW builder and review screens

**Comment by carlycurran** [comment]
@nathanstitt 
1. Thanks, you're the best. 
2. Can Tutor display the tags in the HW builder, too? I missed that. What is the review screen? I think tags should be teacher-facing, not student-facing. That would have been a better way for me to say that.

**Comment by nathanstitt** [comment]
@carlycurran the review screen is the assignment review, I don't think we show tags there.  I updated to add "teacher facing" requirement.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
