### ISSUE TITLE
There is a 10-15 second delay before selected  homework questions are counted in Firefox when making an assignment

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#386]
### Description
When selecting the first questions for a homework assignment, the counter at the top tracking the total number of instructor selected questions does not update the number count until 10-15 seconds after the first questions is selected. This only occurs in the Firefox browser.

**To Reproduce**
Steps to reproduce the behavior are
1. Log into Tutor as an Instructor
2. Click on any course
3. Create a homework assignment
4. Click Select questions
5. Select a question or two
6. Notice how the selected questions counter at the top is not updating the selected questions count
7. Wait 10-15 seconds
8. Notice that the selected questions are tracked now

**Expected behavior**
Selected questions are tracked, counted, and updated in real time when creating an assignment. 

**Screenshots**
https://drive.google.com/file/d/1cXWw3OpTrlX5E-REdFdlnRGggGaWFbnO/view?usp=sharing

**Additional context**
- only occurs in Firefox
- does eventually count the selected questions
- once it catches up, it will count the selected questions in real time 

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
This changes how math is rendered quite a bit behind the scenes.  when testing it we should:
 * Test everywhere math is visible. RefView, QL, Homeworks/Readings, HW Builder
 * Test HW creation with lots of sections selected in all browsers

**Comment by itsgeraldwang** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
