### ISSUE TITLE
Sociology video in assessment 12068@3 is not playing on Tutor, but does play in Exercises. 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#387]
### Description
Sociology video in assessment 12068@3 is not playing on Tutor, but does play in Exercises. 

**To Reproduce**
Steps to reproduce the behavior are
1. Go to Sociology text on QA. Go to QL.
2. Click on Section 10.2
3. Scroll down to assessment 12068@3  

**Expected behavior**
Video plays in Exercises, but not in prod

**Screenshots**
![Screen Shot 2019-04-26 at 9.01.26 AM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/7c359a32-f3a5-4d0c-a611-5d2b6f1d6658)

**Additional context**

### Acceptance Tests
- video plays 

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN that I am a student or teacher viewing this assessment 
> AND I am in the QL or working an assignment  
> WHEN I click play on this video  
> THEN the video plays

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
They've since published version 4 and it appears to play.  12068@4

**Comment by carlycurran** [comment]
Hallelujah. I'm closing this card!
