### ISSUE TITLE
Handle error messaging for task step loading problem

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#388]
### Description
We are getting more errors in loading task steps. We want to show a better error message and encourage students to reload the page. 

**To Reproduce**
Steps to reproduce the behavior are
1. Go to a task step with a free response text box
2. Enter a space in the text box
3. Click submit

**Expected behavior**
If an error comes up, the user gets a page with an explanation and a reload message. 
OpenStax logs the error. 

**Screenshots**

![image (1).png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/9e44e604-6265-4f48-ab4f-a8fd4746c495)

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: OpenStax error logging
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN that a student gets an error message  
> WHEN trying to complete a task step
> THEN OpenStax logs the error in Sentry  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Verified in QA, the way to verify this was a bug that has now been fixed. Will try to see if I can get an error to occur to get this message in Staging.

**Comment by Brooke-Fail** [comment]
Seems to be working in Production.
