### ISSUE TITLE
Bug: Printing math in highlight summary page results in math being in MathML

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#39]
**SCENARIO** _Briefly describe the issue._

When math is highlighted and we print the page, the math shows up as MathML

9/20 MN: 
As per results from regression testing Nathan wants to review if this has to be fixed. So moved this card from some low priority column to here to revisit.
"...yeah that’s a low-pri bug that we have listed somewhere.  However we didn’t know it looked that bad.  The bug we had just had a few tags showing.  @Malar we may want to file a new higher-pri one for that"

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
` [ ] ` Accounts ` [ ] ` BigLearn
` [ ] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [ ] ` Tutor
` [x] ` Highlight ` [ ] ` Web
- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [x] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  https://tutor-dev.openstax.org/book/117/section/3.4
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [ ] ` staging
` [x] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [x] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [x] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by carlycurran** [comment]
![image.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/027011b7-e31a-42dd-a6e6-b1750a63821e)

**Comment by Malar-Natarajan** [comment]
Tested in QA. Most math get highlighted. But there is still some that displays as math processing error.
Refer screenshots from firefox, safari & chrome

**Comment by carlycurran** [comment]
@Malar-Natarajan Did you attach new screenshots to this card? Sorry if yes -- still getting used to Zh.

**Comment by Malar-Natarajan** [comment]
https://drive.google.com/file/d/1uvt9V93jHEIgiSpRnRraKBUADjRaoaUh/view?usp=sharing
https://drive.google.com/file/d/1vBsg-X5C2-0Jv8Yk1nsciOWKKgTaKkil/view?usp=sharing
https://drive.google.com/file/d/1gARnnS-uHPAqTeOrbnBNEAGOM6ld-uOk/view?usp=sharing

**Comment by Malar-Natarajan** [comment]
As per discussion in scrum closing this issue since most math is displayed. The issues noted in screenshot could be isolated highlighting issues
