### ISSUE TITLE
Run a base set of tests against micro server

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#391]
### Description
As OpenStax, I want to understand how the validation server performs at the smallest size, so that we know which instance size is necessary. 

### Acceptance Criteria
- We see test result data
- We can estimate which server size we need for production and what changes we need to make to the algorithm to ensure that student responses are reviewed, data is sent back to Tutor, and Tutor displays a nudge (or not) in less than 2 seconds.  

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- ~If UX design is needed then the UX label is added~
- ~If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue~
- ~A development approach for the code change, prototype code, or tech brief is done and added to the issue~

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items
  - [x] Estimate is updated
  - [x] Release is selected

1C-DESIGN
  - ~The UX HiFi Design is complete, approved by the Product Manager, and added to the issue~
  - [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
  - [ ] Automated testing criteria are added to issue
  - [ ] The development approach is reviewed/updated

2A-CODE
  - [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
  - [ ] The change has been approved by other developers
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] The acceptance tests are finalized
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
  - [ ] If UI changes, UX reviews and verifies on -dev or -qa
  - [ ] PDM reviews and verifies

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
