### ISSUE TITLE
 Make the response validator repo package-able and deployable

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#393]
### Description
As a devops engineer I want response-validator  to be packaged using best practices, so that it integrates easily with our standard deployment systems.

### Acceptance Criteria
The response-validator package exists, and is tagged and deployed like any other part of the openstax software suite. (1-3 required, 4-5, nice-to-have, stretch goals)
     1. standard (setuptools) based python packages
     2. integrated test suite (functional and unit tests) with acceptable (>90%) levels of code coverage
     3. continuous-integration (CI) support (travis-ci.com)
     4.  versioned and tagged (since its a python package, versioneer is desirable)
    ~~5. Automation of deployment to public repo (pypi)~~

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- ~If UX design is needed then the UX label is added~
- ~If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue~
- [x] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [x] Estimate is updated
- [x] Release is selected

1C-DESIGN
- ~The UX HiFi Design is complete, approved by the Product Manager, and added to the issue~
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by reedstrm** [comment]
How to test if the validator was properly deployed:

access (via brower, or curl or wget or …)

https://validator-qa.openstax.org/validate

That should return:
```
{
"bad_word_count": 1,
"common_word_count": 0,
"computation_time": 0.00034737586975097656,
"domain_word_count": 0,
"inner_product": -3,
"innovation_word_count": 0,
"num_spelling_correction": 0,
"processed_response": "no_text",
"remove_nonwords": true,
"remove_stopwords": true,
"response": null,
"spelling_correction": "auto",
"spelling_correction_used": true,
"tag_numeric": "auto",
"tag_numeric_input": "auto",
"uid_found": false,
"uid_used": null,
"valid": false
}
```
(Though you need a plugin to get formatted JSON like that - the raw line looks like:
`{"bad_word_count":1,"common_word_count":0,"computation_time":0.00034737586975097656,"domain_word_count":0,"inner_product":-3.0,"innovation_word_count":0,"num_spelling_correction":0,"processed_response":"no_text","remove_nonwords":true,"remove_stopwords":true,"response":null,"spelling_correction":"auto","spelling_correction_used":true,"tag_numeric":"auto","tag_numeric_input":"auto","uid_found":false,"uid_used":null,"valid":false}`

Add parameters, like `response`:

https://validator-qa.openstax.org/validate?response=This+is+my+respones

`{"bad_word_count":0,"common_word_count":1,"computation_time":0.0016360282897949219,"domain_word_count":0,"inner_product":0.7,"innovation_word_count":0,"num_spelling_correction":1,"processed_response":"response","remove_nonwords":true,"remove_stopwords":true,"response":"This is my respones","spelling_correction":"auto","spelling_correction_used":true,"tag_numeric":"auto","tag_numeric_input":"auto","uid_found":false,"uid_used":null,"valid":true}`

Or adding `uid` to get question (and book) loaded:

https://validator-qa.openstax.org/validate?response=This+is+my+respones&uid=1000@2

or uid plus some words that are in biology, plus forcing spell correction:

https://validator-qa.openstax.org/validate?response=This+is+my+respones+biology+chemotaxis&uid=1000@2&spelling_correction=True

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
