### ISSUE TITLE
Fix old broken migration in Tutor

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor#397]
### Description
One of our old migrations (`db/migrate/20170208182122_add_uuid_and_group_uuid_to_content_exercises.rb`) is not working as intended (it is not creating one of the indices it is supposed to). Not really a problem except for devs or when creating a new server to deploy to.

### Acceptance Criteria
Fix the migration so it creates the missing index on `"content_exercises"."uuid"`

### Acceptance Tests
`db/schema.rb` includes the missing index after running `rake db:drop db:create db:migrate db:seed` locally

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [x] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [x] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [x] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.

**Comment by Brooke-Fail** [comment]
Verified in Production.
