### ISSUE TITLE
reference book fails to load when selected from user menu

### ISSUE THREAD

**Issue by nathanstitt** [openstax/tutor#399]
the reference view has an error when it is loaded with the course id from the user menu.

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/673d89dd-ef67-4039-b9d9-4017a9600235)

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
