### ISSUE TITLE
Multiple errors when a student tries to view or work on past-due Hw assignments

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#402]
### Description
There seems to be a few errors when trying to view or complete past-due assignments.
- Double-clicking on a past-due assignment will give an error (occurred in Edge browser)
- Error while reviewing a past assignment
- Error while completing an assignment that changes to past-due (the way this is handled sounds like it is intended)

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor as a student that has past-due assignments
2. Double click on the past due assignment
3. A possible error will occur here
4. In the past-due assignment try to change answers while reviewing it
5. A possible error occurs
6. Try to complete an assignment that will change to past-due mid completion
7 An error will pop up prompting the student to refresh the page, no longer being able to change answers

**Expected behavior**
No errors are present and any prompts triggers direct users to refresh the page to continue progress.

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
