### ISSUE TITLE
Build admin page for BigLearn-SPARFA

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#404]
### Description
As an OpenStaxer testing Tutor and BigLearn-SPARFA, I want an admin page for BigLearn-SPARFA so that I can switch LQC to SPARFA outside of the dev console. This will give us a safety valve (turn of BL-SPARFA if something goes wrong) and it simplifies deployment if we need to make a change.

### Acceptance Criteria
User with permissions can log into admin page and see if Tutor is using LQC or SPARFA. 
User with permissions can turn LQC or SPARFA on for Tutor.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- ~UX design is needed then the UX label is added~
- ~If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue~
- ~A development approach for the code change, prototype code, or tech brief is done and added to the issue~

1B-DECOMP
  - [ ] The work is broken into reasonable and consistent work items
  - [x] Estimate is updated
  - [x] Release is selected

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
  - [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
  - [ ] Automated testing criteria are added to issue
  - [ ] The development approach is reviewed/updated

2A-CODE
  - [x] A pull request is opened and linked to an issue. The automated pull request checks pass
  - [x] The change has been approved by other developers
  - [x] The pull request is merged into master, and the change branch is deleted.
  - [ ] The acceptance tests are finalized
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
  - [ ] If UI changes, UX reviews and verifies on -dev or -qa
  - [ ] PDM reviews and verifies

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.

**Comment by Dantemss** [comment]
Oops I linked the PR for this to #71

**Comment by Dantemss** [comment]
Solved by updating the current settings page, instead of making a new one.

**Comment by Brooke-Fail** [comment]
Verified QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
