### ISSUE TITLE
Automate deployment notification banner

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#405]
### Description
As an OpenStax Tutor user, I want to know when downtime is planned, so that I can plan my work around that time.

We want to add a banner that appears 24 hours before every planned Tutor deployment, telling students and teachers that Tutor will be down for a brief upgrade between 8:30 AM and 9:30 AM CT. 

Can we automate this?

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by nathanstitt** [comment]
@carlycurran 

Notifications have a From/To date/time.  Is that not working, or maybe this wants Tutor to somehow know that a deployment is scheduled?

let's PL to discuss after scrum

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/e923524f-2718-4808-8007-4c177b7214d0)

**Comment by carlycurran** [comment]
I was thinking that, since we are pretty consistent with deployments, we could get this to automatically show up from Tuesday morning - Wednesday morning every other week, but I'm actually not sure if we are consistent _enough_ to warrant this. 

Maybe this just needs to be a calendar reminder that I do it when we will have a deploy?

**Comment by nathanstitt** [comment]
Yeah, I'd suggest we go in and pre-populate the notices for the next 3 or whatever deployments, rather than coding something that we then might need to change if we ever cancel a deployment like we occasional have to.,

**Comment by carlycurran** [comment]
cool - I'll go do that now :)
