### ISSUE TITLE
identical page title appears before and after splash images

### ISSUE THREAD

**Issue by nathanstitt** [openstax/tutor#407]
![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/9803af58-dcc8-4407-81e4-2c8e37b20625)

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
