### ISSUE TITLE
APUSH: Allow scaled-down and scaled-down-30 classes to dictate art sizing

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#409]
### Description

As a content reviewer for APUSH, I want the classes `full-width`, `scaled-down` and `scaled-down-30` on figures to be recognized and scale the art accordingly, so that I have some predictability in terms of image sizing.

### Acceptance Criteria

-when the class `scaled-down` is present on the `<figure> `(on figures), Tutor should display the image at 60% of the viewport.
-when the class `scaled-down-30` is present on the `<figure> `(on figures), Tutor should display the image at 30% of the viewport.
-when the class `full-width` is present on the `<figure> `(on figures), Tutor should display the image at 100% of the viewport.

There is sample content here: 
Figure 1.2 here has the `scaled-down` class (screenshot of markup below): https://content05.cnx.org/contents/CmIfJ6vh:4_mJkwz1
https://tutor-content.openstax.org/book/88/section/1.2

`scaled-down` class screenshot of markup:
<img width="1021" alt="Screen Shot 2019-05-08 at 9 15 25 AM" src="https://user-images.githubusercontent.com/7863733/57382114-ed6b8300-7171-11e9-8491-8eb2ceea648a.png">

Figure 1.8 has the `scaled-down-30` class
https://content05.cnx.org/contents/CmIfJ6vh:4_mJkwz1
https://tutor-content.openstax.org/book/88/section/1.2

[Alina will get a sample of a figure with` full-width` class]

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by openstaxalina** [comment]
@carlycurran FYI - I have a recommended priority on this, but we should discuss timeline, etc...

**Comment by openstaxalina** [comment]
New display rule in Tutor: Figure followed by another figure is set to 50% width so they go side by side.

One figure that is by itself and **not** the first image in the section is displayed at 60% and centered.  

First image in the chapter goes full-width; if a section starts with an image, it goes full-width.

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
