### ISSUE TITLE
APUSH:  In-text figure reference for first figure in each individual section is missing

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#410]
### Description

We link to figures frequently, and this typically works in Tutor.  However, WiseWire alerted us that in APUSH, links to the first figure in a section (chapter-section, like 1.1, 1.2...) do not work.  Below you will find screenshots showing the link and anchor text auto-generating on content05, but nothing displaying when viewed in Tutor:

![FigureLinksCNX](https://user-images.githubusercontent.com/7863733/57383102-d463d180-7173-11e9-8250-2e4a1c7f3465.png)
![FigureLinksTUtor](https://user-images.githubusercontent.com/7863733/57383119-d9288580-7173-11e9-9c08-c62748abde79.png)

(Link to content on content05: https://content05.cnx.org/contents/CmIfJ6vh:4_mJkwz1)

@oscryan could you supply a link to the problematic content in tutor-content?

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by openstaxalina** [comment]
@carlycurran I put a suggested priority, but open to discuss.

**Comment by oscryan** [comment]
This happens in every module, but the one from the screenshots is here: https://tutor-content.openstax.org/book/88/section/1.2

**Comment by openstaxalina** [comment]
@nathanstitt investigating as a bug.  Tutor sets the numbers, so something may be failing with that process.

**Comment by CaptainXep** [comment]
Verified in QA

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
