### ISSUE TITLE
APUSH: Do not add traps to art (?)

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#411]
### Description

Wisewire alerted us that Tutor appears to sometimes add "traps" (borders or lines) to art that was not rendered with these lines.  Is the border serving a function?  If not, could this be removed?

See Figure 1.17 here in CNX: https://content05.cnx.org/contents/CmIfJ6vh:uI3AY2OD

Vs. in Tutor: https://tutor-content.openstax.org/book/88/section/1.6

Screenshot from CNX:
<img width="922" alt="Screen Shot 2019-05-08 at 9 46 07 AM" src="https://user-images.githubusercontent.com/7863733/57384399-286fb580-7176-11e9-9900-0ef1f52e520a.png">

Screenshot from Tutor (ignore alt text hover; this is not an issue)
<img width="765" alt="Screen Shot 2019-05-08 at 9 46 13 AM" src="https://user-images.githubusercontent.com/7863733/57384386-23ab0180-7176-11e9-964a-b16878b2c798.png">

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by openstaxalina** [comment]
Shows in both QA view and course (reference?) view.  @nathanstitt is investigating this as a bug.

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
