### ISSUE TITLE
APUSH: Teacher Note styling has changed; needs adjustments

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#413]
### Description

Teacher Note styling has changed (before/left, after/right) and now titles are falling outside of notes.  The teacher content doesn't display in CNX, so I cannot verify what platform is driving the changes.  It would be helpful to discuss this with the Tutor team.

<img width="872" alt="Screen Shot 2019-05-08 at 4 06 39 PM" src="https://user-images.githubusercontent.com/7863733/57408434-486d9c00-71ab-11e9-8130-78ce49fe2ca9.png">

https://tutor-content.openstax.org/book/88/section/1.17

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by openstaxalina** [comment]
@nathanstitt will investigate why these are not getting the normal Teacher Note styling.

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
