### ISSUE TITLE
APUSH: Serif versus Sans Serif Fonts in Tables

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#414]
### Description

We noticed that content set in tables is sometimes displaying in a sans serif font, other times with a serif font.  We would like all content set in tables to be output in a sans serif font for space-saving and legibility.

Sample of table with sans serif:
https://content05.cnx.org/contents/CmIfJ6vh@11.6:dQ_-VIsc@5/%F0%9F%93%8E-Inquiry-Organizer
https://tutor-content.openstax.org/book/88/section/1.1

Sample of table with serif font:
https://content05.cnx.org/contents/CmIfJ6vh@11.6:rYtSijjh@4/1-11-%E2%9C%92%EF%B8%8F-Columbus-s-Letter-to-Ferdinand-and-Isabella-of-Spain-1494
https://tutor-content.openstax.org/book/88/section/1.12

### Acceptance Criteria
Give criteria for acceptance.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by openstaxalina** [comment]
@nathanstitt thinks this is a bug; will look into this.

**Comment by nathanstitt** [comment]
@openstaxalina - the cause of the differing fonts is that the sans font (HelveticaNeue) is Tutor's default font.

However in book content (reading steps, reference view) `p` tags are set to use the Merriweather  serif font. 

The table that's using serif has the content in each cell wrapped in a `p` tag, while the other does not.

**Comment by openstaxalina** [comment]
@oscryan is it possible to encode these tables without `para` tags?

**Comment by oscryan** [comment]
I don't think we should. It's a whole document with actual paragraphs in it that need line returns, and brute-forcing it with the newline tag (which often has unexpected results on different platforms) is non-semantic.

**Comment by openstaxalina** [comment]
@nathanstitt is it possible to give `para` content in tables the same treatment as other content in tables?

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
