### ISSUE TITLE
APUSH: Byline tables are crashing with the Learning Objectives above them

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#415]
### Description
As a content review for APUSH, I want the byline to be separated from the Learning Objectives so that the content doesn't crash and the appearance is better.

![BylineCrashing](https://user-images.githubusercontent.com/7863733/57408911-89b27b80-71ac-11e9-8698-cac3b61873f7.png)

Link to relevant content: https://tutor-content.openstax.org/book/88/section/1.3

The content is marked up as an unnumbered, unstyled table. 

### Acceptance Criteria
Give criteria for acceptance.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by openstaxalina** [comment]
Per @nathanstitt, this is in the current sprint and should be re-tested on tutor-qa.openstax.org after code freeze.  (Re-test the week of 5/13.)

Need to work with @Brooke-Fail to import APUSH content to tutor-qa to test.

**Comment by openstaxalina** [comment]
(Also test the Learning Objectives/column display against options here: https://github.com/openstax/tutor-js/pull/2600)

**Comment by nathanstitt** [comment]
Was fixed in https://github.com/openstax/tutor-js/pull/2608

**Comment by CaptainXep** [comment]
Verified with QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
