### ISSUE TITLE
APUSH: Standardize Teacher Note Width

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#417]
### Description
As a content creator for APUSH, I want Teacher Notes to be the same width so that they look more professional and parsable.

Discussed in APUSH Collaborators meeting today.  Devika and Carly agreed width should be standardized.

Some examples: 
https://tutor-content.openstax.org/book/88/section/1.14
![Screen Shot 2019-05-10 at 3 41 57 PM](https://user-images.githubusercontent.com/7863733/57555568-44bc4f80-733a-11e9-9ec5-6eebed80c0da.png)

https://tutor-content.openstax.org/book/88/section/1.15
![Screen Shot 2019-05-10 at 3 43 19 PM](https://user-images.githubusercontent.com/7863733/57555596-5a317980-733a-11e9-9c49-42f33d2345e8.png)

https://tutor-content.openstax.org/book/88/section/1.17
![Screen Shot 2019-05-10 at 3 41 57 PM](https://user-images.githubusercontent.com/7863733/57555620-6cabb300-733a-11e9-8998-644218c6c652.png)

### Acceptance Criteria
Give criteria for acceptance.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by nathanstitt** [comment]
This was fixed in https://github.com/openstax/tutor-js/pull/2608

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
