### ISSUE TITLE
APUSH: Discard ap-practice sections so they aren't duplicated in Tutor

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#418]
### Description
As a content creator for APUSH I want sections with the class `ap-practice` to be discarded because these questions are being encoded into Exercises so I don't want them to display twice.

### Acceptance Criteria
-Sections with the class `ap-practice` do not display in Tutor.

[Content team to provide sample content for testing.]

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by nathanstitt** [comment]
@carlycurran @openstaxalina - I'm unclear on what you mean by "Do not display in Tutor".  

If we don't want to display them, then why are we creating them in exercises?  Seems to me like we can just not add them there and we're good.  

HOWEVER, maybe you mean that they shouldn't be displayed in the question library or something like that?

**Comment by openstaxalina** [comment]
Hey @nathanstitt - thank you for asking about this!

We have devised a system so that we can encode assessments into Exercises and align them to the section content in two ways: with the module UUID, and with the nickname.

Tutor uses the module UUID to align the assessment with a section. With Tutor, due to the personalization/machine learning/spaced practice, the assessment just needs to be aligned to the  section (or rarely, a feature within the section) - it is a given that different students will see different assessments, and the specific numbering of the assessments isn't expected to be the same each time.

However, for any PDF or printed product, we need to be able place the assessment in an _exact_ location.  We need Review Question # 1 to always be #1, Review Question #2 to always be #2, etc.  

The sections with the classes `ap-practice` and `review-questions` use the nickname system so that, if needed, we will be able to generate a PDF/printed product that guarantees the placement of each assessment.  The assessments are pulled into the content on content05.cnx.org via the nickname, and then when that content is pulled into Tutor, it effectively means that the questions are displaying twice -- once via the module UUID (which is what we want) and a second time, statically, because of the nickname (which we don't want).

I apologize for the long-windedness.  It is a really important question and I'd be happy to join a scrum or talk about it another way if easier.

(One other tidbit - I believe we are already doing this type of thing with the other books currently in Tutor.  Tutor is suppressing end of chapter and maybe also end of section questions.  The only difference here is that those have usually been encoded in the XML and then _re-encoded_ in Exercises, whereas here, we are gaining efficiency by only encoding in Exercises.)

**Comment by nathanstitt** [comment]
NP!  Thanks for the long-windedness 😁   @Dantemss what do you think about ^^^?

I'm leaning toward adding a new tag that would mean "don't display in content", that would allow Tutor to identify and skip displaying exercises with that tag in reference view.

Possibly you see a simpler method?

**Comment by openstaxalina** [comment]
Just one note - the class should be on the `section` tag where the exercises are contained, not on each `exercise`.

**Comment by openstaxalina** [comment]
@carlycurran we've added the `ap-practice` and `review-questions` classes back into chapters 1-3 and have instructed Wisewire to use these classes on future chapters.

Do you have an estimate for when Tutor will use the classes to not display these questions in the static content in Tutor? cc @oscryan

**Comment by Dantemss** [comment]
These are already in the APUSH reading processing instructions: https://github.com/openstax/book-manifests/blob/master/High%20School/Sample%20Books/APUSH/APUSH%20September%20Pilot.yml

Which were created based on https://docs.google.com/spreadsheets/d/1BcdrwaXIt5VGJGOZhfqEYeF4mKYyk2HrGpBnK4AbQBA/edit#gid=0

However, I noted that the os-teacher row was added to the spreadsheet after the manifest was made, so it needs an update to also exclude the os-teacher class.

**Comment by nathanstitt** [comment]
@openstaxalina do we need to exclude the given sections in reference view as well as readings?  

@Dantemss investigated and we can remove them from readings pretty easily by changing the import files, but to exclude from reference view will require a code change.

**Comment by openstaxalina** [comment]
@nathanstitt I am 90% sure that they do **not** need to be excluded in reference view.

**Comment by openstaxalina** [comment]
@nathanstitt would you be able to just double-check with Carly when she is back?

**Comment by nathanstitt** [comment]
yes, we'll double check next week when she returns.  Thanks!

**Comment by openstaxalina** [comment]
@carlycurran @nathanstitt please note that I have updated this -- right now we **only want to discard `ap-practice`** (not `review-questions`).

**Comment by openstaxalina** [comment]
This has been resolved in the following way:

AP Practice Questions do not display in readings assignments
AP Practice Questions do display in Browse the Book.  

This is the behavior in existing Tutor courses - content cannot be suppressed in Browse the Book, but can be suppressed reading assignments.  

@carlycurran and others may want to use part of the Sep 6 APUSH call to confirm that this issue has been satisfactorily resolved and can be closed.

**Comment by carlycurran** [comment]
DECISION on 9/5 APUSH COLLABORATOR'S CALL: 

Review and AP Practice questions will live in the reference/browse-the-book view. They will not live in the Reading assignments. 

Markup and manifest need to support this, but this is standard Tutor behavior, so closing this card.
