### ISSUE TITLE
homework assessment reordering isn't working correctly

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#419]
### Description

The resort options for assessments aren't showing up correctly.

![Screen Shot 2019-05-10 at 4.05.19 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/51234d16-c923-425b-b473-64dd2389c811)

1) should have a down arrow as it's the first in the list
2) should have both a down and and up arrow as it can move in either direction
3) should have an up arrow as it's the last in the list

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [x] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified on Staging

**Comment by ejp3** [comment]
Verified in Production
