### ISSUE TITLE
Subheading of figures that start a section not wrapping properly on half screen

### ISSUE THREAD

**Issue by itsgeraldwang** [openstax/tutor#421]
### Description
The subheading of each figure at the beginning of each section goes past the white page and onto the grey background (i.e. not wrapping back onto the white).

https://tutor-qa.openstax.org/book/2559/section/18.3
(teacher04)

**To Reproduce**
Steps to reproduce the behavior are
1. Log in as a teacher
2. Click on Physics and go to any chapter with an intro figure
3. Go to half-screen

**Expected behavior**
The text should wrap around to the next line properly.

**Screenshots**
![Screen Shot 2019-05-14 at 10.40.46 AM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/5e86df90-d685-469d-95ee-e45eb0349328)
**Additional context**
This only occurs on half-screen but with any figure that starts a chapter section.
### Acceptance Tests
Additional acceptance tests that are required by this bug fix. The appears to be a problem in all textbooks.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by CaptainXep** [comment]
Headers on AP Physics book going off the page when on half-screen. It works when you zoom out but doesn't wrap as you make the screen width smaller.
Example:
![Screen Shot 2019-05-15 at 11.44.02 AM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/80142910-b4a8-4c88-92e8-d021e9308c1f)

Zoomed out:
![Screen Shot 2019-05-15 at 11.44.26 AM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/56968d71-564f-4716-a493-8399d98e7c10)

Account: teacher04

**Comment by itsgeraldwang** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
