### ISSUE TITLE
APUSH: Link to Question Takes User Too Far Down the Page

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#422]
### Description
 
We noticed that links to an exercise further down the page pulls the user _too far_ down the page, beyond the linked exercise.  

**To Reproduce**
Steps to reproduce the behavior are
1. Go to 'https://tutor-qa.openstax.org/book/2558/section/1.12#fs-idm387987568'
2. Click on 'That in the said island there shall be founded three or four towns, situated in the most convenient places, and that the settlers who are there be assigned to the aforesaid places and towns.'
3. Notice that the screen jumps one exercise too far, to "What cultural purpose of colonization did Columbus highlight here?" instead of "How were towns to be populated in Columbus’s plan for colonies?"

**Expected behavior**
The expected behavior is that the link jumps to the linked question, not a question below it.

**Screenshots**
Please see the screengrab video here: https://drive.google.com/file/d/1ly11DlTOqN_v_6Geb90RjN__Uhmzshzu/view?usp=sharing

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
this affects any content that is linked to.  the code scrolls to the location, but doesn't take the navbar into account so the top is hidden.  it needs to scroll +100px down the page or something like that

**Comment by itsgeraldwang** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by ejp3** [comment]
Verified in Production
