### ISSUE TITLE
404 and Contact Us error when trying to view students in student scores page

### ISSUE THREAD

**Issue by itsgeraldwang** [openstax/tutor#423]
### Description
Description
There seems to be a couple errors when trying to view students in the student scores page. A sorry a 404 error occurs when the student hasn't done the reading and a contact us when they did.

Account: teacher04

**To Reproduce**
Steps to reproduce the behavior are
1. Log in as teacher04 and go to Alicia College Physics
2. Click on Student Scores
3. Try viewing a student under the Overall column

**Expected behavior**
There shouldn't be an error when trying to click on the student.

**Screenshots**
![Screen Shot 2019-05-15 at 10.15.18 AM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/84e87c19-d4d9-4898-82cd-75bf3c946587)
![Screen Shot 2019-05-15 at 10.15.36 AM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/1d4ad39d-5323-46bf-a873-5f95cbc36ffc)
**Additional context**
This happens on teacher04 Alicia College Physics on every student.

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
this was fixed in https://github.com/openstax/tutor-server/pull/1866

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
