### ISSUE TITLE
APUSH Assessments (from Exercises) Not Showing Up in Tutor-Content

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#426]
### Description

Wisewire encoded several assessments for APUSH over the last few weeks.  However, when we import the APUSH ecosystem on tutor-content, no exercises show.  

**To Reproduce**
Steps to reproduce the behavior are
1. Go to 'https://tutor-content.openstax.org/course/88/questions#'
2. Select all sections
3. Notice that no assessments populate
We confirmed that the following assessments are properly tagged to page-module UUIDs in the book:
17580 (assigned to _Chapter Introductory Essay_)
17581 (assigned to _Chapter Introductory Essay_)
17495 (assigned to _Native People_)
17496 (assigned to _Native People_)

**Expected behavior**
1. Go to 'https://tutor-content.openstax.org/course/88/questions#'
2. Select all sections
3. The assessments listed above (and others) should populate

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
@openstaxalina, can you give us the name of the account WiseWire uses to create assessments?

**Comment by openstaxalina** [comment]
@carlycurran the email is `cmsupport@openstax.org`.

I believe the account name is `wisewire`.  It is the account that authored the questions above.

**Comment by carlycurran** [comment]
Okay, we need to manually give the new assessments the OpenStax copyright and prioritize the work to give WiseWire's account permissions that would allow every newly created question to have the OpenStax copyright.

**Comment by carlycurran** [comment]
@openstaxalina, we basically split this into three cards: 

This is the longer-term solution card https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/366

This is the short-term solution card: https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/437

This is the workaround for right now: https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/438

If you have anything to add to those, please do! And then I will close this one.

**Comment by openstaxalina** [comment]
@carlycurran thank you!  I reviewed, and all look good to me.  I'd like to be involved (perhaps as a reviewer) when you break down the longer-term epic card.  The workarounds and short-term solutions will be extremely helpful in keeping to our publication timeline for APUSH.
