### ISSUE TITLE
Assignments not loading properly when clicked on twice

### ISSUE THREAD

**Issue by itsgeraldwang** [openstax/tutor#427]
### Description
Description
If you click on an assignment, go back, and click on another assignment it can sometimes load indefinitely until you hard refresh the page. It can also happen if you click the same assignment twice.

**To Reproduce**
Steps to reproduce the behavior are
1. Log in as student02
2. Click on SPARFA course
3. Click on an assignment, use the back button, and click on another or the same assignment

**Expected behavior**
It should load normally

**Screenshots**
https://drive.google.com/file/d/1Sz4c4s5zOZ2CYFbfyZcE5FZBT1oUrvLv/view?usp=sharing
**Additional context**
This happens on pretty much any account and any assignment.
### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
This does happen in prod, just not as frequently as it happened in QA. 

Needs to go in 5/22 release.

**Comment by carlycurran** [comment]
If Tutor loads a task and you go back into assignment before it's finished loading, the task never registers that it finished loading.

**Comment by ejp3** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by ejp3** [comment]
Verified in Production
