### ISSUE TITLE
Bug: potential time zone issue: Cannot destructure property offsets of 'undefined' or 'null'."

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#428]
### Description
Hello!
I ran into a problem at https://tutor.openstax.org/course/4899/t/month/2019-11-01 while using browser Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36.

The request details are: undefinedThe request body was: {"error": "TypeError: Cannot destructure property offsets of 'undefined' or 'null'."}.

Case 32895, course 4899

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by itsgeraldwang** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
