### ISSUE TITLE
Learning objective in AP Physics is misaligned

### ISSUE THREAD

**Issue by itsgeraldwang** [openstax/tutor#429]
### Description
The learning objective bullet points are too low and almost touch the bottom line separating them from the text.

**To Reproduce**
Steps to reproduce the behavior are
1. Go to AP Physics
2. Click on any chapter with learning objectives
3. See error

**Expected behavior**
The learning objectives should be evenly spaced in between the two lines

**Screenshots**
![Screen Shot 2019-05-20 at 10.33.15 AM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/418da6c5-f9bd-44e1-a0ec-e9ef6cb088d7)
**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
this was fixed in https://github.com/openstax/tutor-js/pull/2628 - didn't know we had a card for it at the time, sorry

**Comment by itsgeraldwang** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
