### ISSUE TITLE
Bug: Trying to uncheck the multiple parts checkbox (convert button) does nothing

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#43]
**SCENARIO** _Trying to uncheck the multiple parts checkbox (convert button) does nothing.

Removing the second question works though and automatically unchecks the checkbox

Identified by Dante during regression testing

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
` [ ] ` Accounts ` [ ] ` BigLearn
` [X] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [ ] ` Tutor
` [ ] ` Highlight ` [ ] ` Web
- **User Type:**
` [X] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [X] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [X] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by carlycurran** [comment]
![image.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/aba68d92-1e54-483a-a38c-d1ddb36c537d)

**Comment by nathanstitt** [comment]
PR: https://github.com/openstax/tutor-js/pull/2394

**Comment by Malar-Natarajan** [comment]
Tested in QA. Clicking the convert button removes all questions except Q1. On publishing the changes, the search preview still shows the Introduction. Refer video

https://drive.google.com/file/d/1ZiGyYCcQV4eEicpdpd8ts8dgTKk0wbWh/view?usp=sharing

**Comment by nathanstitt** [comment]
fixed; introduction is cleared in https://github.com/openstax/tutor-js/pull/2406

**Comment by Malar-Natarajan** [comment]
Verified in QA
