### ISSUE TITLE
OpenStax Tutor reference view URL has misleading section numbers

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#431]
### Description
The OpenStax Tutor reference view URLs have section numbers that do not match with the actual book section. 

It sounds like the underlying problem is that, with assignable webview, some sections that were previously numbered are now no longer numbered, which is throwing our counts off. 

**To Reproduce**
Steps to reproduce the behavior are
1. Go to an AP Physics course. 
2. Click on Browse the book.
3. Click on Chapter 6, section 4. 
4. See URL

**Expected behavior**
URL either matches section numbering or does not include section numbers that are wrong.
**Decision:** We cannot match URL and section, so we will use page ID. Section URLs will redirect to new page ID urls. 

**Screenshots**
![Screen Shot 2019-05-21 at 1.37.02 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/6bd77d10-bc31-47c4-868a-027e4f684c95)

**Additional context**

### Acceptance Tests
Intra-page links in the book are not broken. (Might need to ask a content manager if they know of any examples offhand) 

Old URLs (with section numbers) still work and redirect to URLs with page IDs.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by itsgeraldwang** [comment]
Verified in QA.

**Comment by carlycurran** [comment]
@nathanstitt are we going to run into any linking problems with this change? are all pages going to have new URLs?

**Comment by nathanstitt** [comment]
I hope not.  We added code that will still allow chapter.sections to be used.  it'll redirect to the page id if they're present.

**Comment by carlycurran** [comment]
nice. I tried typing the URL in my screenshot above into my browser and got to the original page with a new URL :)

**Comment by carlycurran** [comment]
@itsgeraldwang @ejp3 You might want to do a little bit of regression testing around my comments above. I'll add to acceptance tests.

**Comment by nathanstitt** [comment]
whew!  then it sounds like it's working 😁

**Comment by ejp3** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
