### ISSUE TITLE
"Browse this chapter" link not working from HW builder

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#432]
### Description
The "Browse this chapter" link not working from HW builder

**To Reproduce**
Steps to reproduce the behavior are
1. Go to course 2561 as Teacher01 
https://tutor-qa.openstax.org/course/2561/t/month/2019-05-21

2. Click "add homework." 
3. Click "select problems"
4. Click "Browse this chapter" (any of the links) at the right
5. See the error

**Expected behavior**
"Browse this chapter" link takes user to the referenced chapter in reference view

**Screenshots**
![Screen Shot 2019-05-21 at 10.15.41 AM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/7d57d3ff-d4ae-455e-825d-66420318b1e4)

![Screen Shot 2019-05-21 at 10.15.46 AM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/f8faf019-db48-413f-b72e-e6b3688d7a21)

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
this was fixed by https://github.com/openstax/tutor-js/pull/2623

**Comment by ejp3** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by ejp3** [comment]
Verified in Production
