### ISSUE TITLE
Can't cancel or close out of window to delete a saved draft for an assignment

### ISSUE THREAD

**Issue by ejp3** [openstax/tutor#433]
### Description
When you click on the delete button on a saved draft of an assignment, clicking the cancel button or the x in the corner does nothing, only the delete button works.

user: teacher02

**To Reproduce**
Steps to reproduce the behavior are
1. Open a saved draft of an assignment
2. Click on 'Delete'
3. See that clicking on 'Cancel' or the 'x' does nothing.

**Expected behavior**
Clicking on 'Cancel' or the 'x' should close out of the window without deleting the draft

**Screenshots**
https://drive.google.com/file/d/1qUWZzx1FhnBDQ5UWpjx_DIuErfQPBRUW/view?usp=sharing

**Additional context**
You can close out of the window without deleting the draft by hitting escape or refreshing the page. 

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
might be related to the bug - attempting to save with a blank name.

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2654

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by Brooke-Fail** [comment]
Verified in Production.
