### ISSUE TITLE
APUSH: Make the "scale" classes the highest priority for art sizing

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#434]
### Description
As a content creator and reviewing for APUSH, I want the `full-width`, `scaled-down`, and `scaled-down-30` classes to set the widths on art (at 100%, 60%, and 30%, respectively) so that I have predictability in art sizing which lets me determine which class to apply to each piece of art.

### Acceptance Criteria
-when the class `full-width` is present on the `<figure> `(on figures), Tutor should display the image at 100% of the viewport.
-when the class `scaled-down` is present on the `<figure> `(on figures), Tutor should display the image at 60% of the viewport.
-when the class `scaled-down-30` is present on the `<figure> `(on figures), Tutor should display the image at 30% of the viewport.

Figure 1.2 here has the `scaled-down` class (screenshot of markup below): https://content05.cnx.org/contents/CmIfJ6vh:4_mJkwz1
https://tutor-content.openstax.org/book/88/section/1.2

`scaled-down` class screenshot of markup:
<img width="1021" alt="Screen Shot 2019-05-08 at 9 15 25 AM" src="https://user-images.githubusercontent.com/7863733/57382114-ed6b8300-7171-11e9-8491-8eb2ceea648a.png">

(Alina asking Matt West with WiseWire to tell us the location of art pieces with the other two classes for testing.)

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by itsgeraldwang** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
