### ISSUE TITLE
Manually add OpenStax as copyright holder to new WiseWire assessments for APUSH

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#438]
### Description
As OpenStax and WiseWire I want to see the new assessments I've added to exercises in Tutor-content so that I can QA the book I'm producing.

We confirmed that the following assessments are properly tagged to page-module UUIDs in the book:
17580 (assigned to Chapter Introductory Essay)
17581 (assigned to Chapter Introductory Essay)
17495 (assigned to Native People)
17496 (assigned to Native People)

Expected behavior
1. Go to 'https://tutor-content.openstax.org/course/88/questions#'
2. Select all sections
3. The assessments listed above (and others) should populate

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [x] Estimate is updated
- [x] Release is selected

1C-DESIGN
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

**Comment by Dantemss** [comment]
Added OpenStax as copyright holder to:

```
17494
17495
17496
17497
17498
17499
17500
17501
17502
17503
17504
17505
17506
17507
17508
17509
17510
17511
17512
17513
17514
17515
17516
17517
17518
17519
17520
17521
17522
17523
17524
17525
17526
17527
17528
17529
17530
17531
17532
17533
17534
17535
17536
17537
17538
17539
17540
17541
17542
17543
17544
17545
17546
17547
17548
17549
17550
17551
17552
17553
17554
17555
17556
17557
17558
17559
17560
17561
17562
17563
17564
17565
17566
17567
17568
17569
17570
17571
17572
17573
17574
17575
17576
17577
17578
17579
17580
17581
```
