### ISSUE TITLE
Bug: No way to tell that image is highlighted

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#44]
**SCENARIO** _Note added while highlighting images are not displayed in the page but displayed correctly in the Summary page. Refer video

----------------
**Steps to Reproduce the issue:** _Highlight an image and add a note. Summary page displays the note but not the book page

Identified by Kim during regression testing

- **Product:**
` [ ] ` Accounts ` [ ] ` BigLearn
` [ ] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [] ` Tutor
` [ ] ` Highlight ` [ ] ` Web
- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [X] ` Student  ` [X] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [X] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [X] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by carlycurran** [comment]
video: https://drive.google.com/file/d/1tDMtmdL_RoxhwTfRxujHFoeRXduDaZ0f/view?usp=sharing to this card

**Comment by carlycurran** [comment]
no visual indication that the image is highlighted. 
clicking the view button will work when the library is imported.

**Comment by nathanstitt** [comment]
After discussing with unicorn team, we're going to add a slight padding so a blue border shows up when an image is highlighted

**Comment by carlycurran** [comment]
@Malar-Natarajan When you test, will you make sure this doesn't displace any content

**Comment by nathanstitt** [comment]
https://github.com/openstax/tutor-js/pull/2425 adds the highlighted color border around an image when it's highlighted

**Comment by Malar-Natarajan** [comment]
Verified in QA
