### ISSUE TITLE
Unable to type letters in APLO field for AP subjects

### ISSUE THREAD

**Issue by rosemaryyang** [openstax/tutor#441]
### Description
In the Tags tab of Exercise Editor, if AP Bio is first selected as the tag for Books, and then switched to the AP Physics tab, letters are unable to be typed into the APLO field. The APLO also displays #.##

**To Reproduce**
Steps to reproduce the behavior are
1. Go to 'Tags' on the Exercise Editor.
2. Select 'Biology for AP Courses' under the 'Book' tag.
3. Then change the tag to 'College Physics for AP Courses' under the 'Book' tag.
4. See error in the APLO field.

**Expected behavior**
When AP Physics is selected as the tag in Book, letters should be able to be typed into the APLO field. The APLO field should also display #.[A-Z].#.#

**Screenshots**
![BUg](https://user-images.githubusercontent.com/50595077/58262198-6efd0c80-7d3f-11e9-9d9a-28ab4357b829.gif)

**Additional context**
This bug does not occur when AP Physics is selected first. 

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by openstaxalina** [comment]
@carlycurran FYI - Rosemary found this while updating the Exercises editor documentation with the APLO field changes 💪

**Comment by carlycurran** [comment]
original card: https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/317

**Comment by openstaxalina** [comment]
(Note that this specifically happens when you switch books.)

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
The original issue is fixed but the error is displaying the wrong format when switching books:

![Screen Shot 2019-05-29 at 3.46.08 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/b0e5ef9a-0f31-47fd-9b19-cf98cc899d7a)

**Comment by Brooke-Fail** [comment]
The error is fixed, but now I can’t select the AP LO when switching books.
Video:
https://drive.google.com/file/d/1kd4f_dZ_RYG1GbgyxE1Fuf8iQdIzDf-J/view?usp=sharing

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
