### ISSUE TITLE
[HOLD] APUSH: Do not suppress the preface

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#442]
### Description
As OpenStax, we want to be able to see the APUSH Preface in Tutor, so that we can meet our contractual obligations to attribute content in the appropriate manner (attribution information is included in the preface).

You could use the U.S. History collection and preface in testing if that would be helpful: https://cnx.org/contents/p7ovuIkl:suXm_00r

The preface module has a class on it just inside the content tag:
![Screen Shot 2019-05-23 at 1 54 33 PM](https://user-images.githubusercontent.com/7863733/58278750-52be9700-7d62-11e9-9654-e3135990ddd3.png)

### Acceptance Criteria
- The APUSH Preface displays in Tutor, anywhere that the full book can be viewed (Browse the Book...anything else?)
- I don't think the Preface should be available as an assignable section.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by openstaxalina** [comment]
@carlycurran please review when you get the chance (esp. the acceptance criteria - curious about your thoughts there?).

**Comment by nathanstitt** [comment]
@openstaxalina I don't see this in the content that we're importing from.  I'm looking specifically at https://archive-content05.cnx.org/contents/0a621f27-abe1-4c17-8f1c-d80d07958977@11.4 which is the latest import as far as I can see

**Comment by openstaxalina** [comment]
@nathanstitt correct - the APUSH content doesn't have a preface.  In the description above, I suggested that we could test with U.S. History in the meantime.  If this would not work, we could create a mock-up preface for that APUSH collection.  Please let me know what you think!

**Comment by nathanstitt** [comment]
Sorry, I'd mis-read that and thought that US History and APUSH was the same book.  yeah we can try to import US History and see what happens

**Comment by openstaxalina** [comment]
@nathanstitt no worries - we are starting to have the problem with history that we already have with physics (too many books!).

I'm not sure how/where a book-level change like this is implemented.  If it causes problems to test with a different book, please let us know and we will figure out a plan.

**Comment by nathanstitt** [comment]
I think your suggestion is a good way to test the preface, but I'd expect quite a bit of the other parts not to render correctly.  That's fine though since we'd only be interested in the preface for this. 

I'll try to put it up somewhere soon

**Comment by nathanstitt** [comment]
Testing with US History suggests that the preface is not shown :( 

It's imported at https://tutor-qa.openstax.org/qa/464

@Dantemss do you know any reason why we'd not import that?  The content that was imported is:
https://archive.cnx.org/contents/a7ba2fb8-8925-4987-b182-5f4429d48daa@9.3

**Comment by openstaxalina** [comment]
If it's any help, all of our published books, including the ones currently in Tutor (_College Physics_, _Introduction to Sociology 2e_, _Biology 2e_) have prefaces.  However, I believe that Tutor does not ever display the preface. I'm not sure if this is some kind of global setting?

**Comment by carlycurran** [comment]
We ignore anything that's not in a chapter. All pages must have a chapter as a parent. To change this would require a change to the database schema. 

@openstaxalina  Is there any other place to bring this information in? Other than a standard preface?

**Comment by openstaxalina** [comment]
@carlycurran, are you also ignoring appendices in Tutor?  These (like the preface) are not in a chapter.

I would suggest reviewing options on the next APUSH Collaborators call, to get feedback from BRI.  Some options I can think of to handle content that would usually be included in the Preface:

- upload this as a document to the course (similar to the proposal for the Instructor Solution Manual)
- include this in the first page in the first chapter
- ...if I think of others, I'll add here.

**Comment by carlycurran** [comment]
We are also not bringing in top-level reference material (appendices). 

I'll chat with BRI on the next call about other options. Thanks for those ideas!

**Comment by carlycurran** [comment]
@openstaxalina are we good to close this card, given that WW liked the preface placement you showed last week?

**Comment by openstaxalina** [comment]
@carlycurran yes, closing.  We did also note that the module needs to start with the word "Introduction" for Tutor to unnumber it.  Discussion here: https://openstax.slack.com/archives/C3PLC5NP7/p1566921067061400

I will flag to share this information on Thursday's call.

**Comment by openstaxalina** [comment]
Link to call note confirming placement works: https://docs.google.com/document/d/1Ycu-zM887S-f9cG8ETJ_ZeCNw8sD4fdESPR4d5nyoAM/edit#bookmark=id.27kap3e70iou
