### ISSUE TITLE
multipart questions do not load all parts automatically

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#444]
### Description
Description

When loading a multipart question, the first unanswered question is displayed, but any subsequent parts show the loading 4 gray until (a) the unanswered question is completed or (b) the user clicks on the specific step icon. Previous behavior displayed all questions within a multipart.

![Screen Shot 2019-05-30 at 12.33.19 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/b984d577-323e-4127-9b9b-47d58c979a71)

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
Because current step is not loaded, placeholder displays. 

Possible fix:
If multi-part, logic needs to read ahead IF multi-part and populate it.

**Comment by ejp3** [comment]
Verified in QA

**Comment by ejp3** [comment]
Verified in Staging

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
