### ISSUE TITLE
Send existing ghost student roles to front end

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#447]
### Description
BE sends existing ghost student roles that have been created to FE

### Acceptance Criteria
Teacher can go back to student view and see data they’ve entered (problems worked) and teacher does not have to wait for BL the second time they enter student view

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
https://docs.google.com/document/d/1eCgJafsZKsQPxkArHiC7_qFGLtWEHzYxZugzJ37mOVI/edit#

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items
  - [ ] Estimate is updated
  - [x] Release is selected

1C-DESIGN
  - [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
  - [ ] Automated testing criteria are added to issue
  - [ ] The development approach is reviewed/updated

2A-CODE
  - [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
  - [ ] The change has been approved by other developers
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] The acceptance tests are finalized
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Will verify in production once this feature is turned on and visible to users. Closing this card since the code is released.
Card to track verification is:
https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/519

**Comment by Brooke-Fail** [comment]
Verified in Production.
