### ISSUE TITLE
Change Request: Distinguish enrolled students from dropped students on the student scores page in Tutor. 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#45]
## Summary:
-----

Make distinction between dropped students on the student scores page

## Current Behavior:
----
Currently, dropped students show up as regular students on the student scores page. The student shows as dropped in the scores export. The student shows as dropped in the course roster. 

*****

## Desired Behavior:
-----
As an OXT instructor, I want to be able to easily tell which students have been dropped from my course when I look at the Student Scores page or view the scores export. If I am using LMS integration, I don't want the drop to affect my score sync. 

Dropped student scores should not affect course averages. 

Student name/ID should go to bottom of the list.

*****

## Acceptance Criteria:

- [x] Instructor can tell, by looking at the Student Scores page or the scores export, if a student has dropped the course. 
- [ ] Instructor does not get error message when clicking on the performance forecast for a dropped student. 
- [ ] Dropped students' scores do not affect the course average.
- [ ] Dropping a student does not affect LMS integration.

**Comment by carlycurran** [comment]
Question for @nathanstitt: Do you know what currently happens when a teacher who has a dropped student syncs with her LMS? 

If we deactivate a dropped student visually and remove his scores from course avgs, what will happen when a teacher syncs with LMS? 
Will they get the error that not all students were able to sync? What if that teacher re-adds the student? 
Will that screw up the LMS connection? 

Fun things to think about :)

**Comment by dkhowala** [comment]
*Instructor can still add student back to course if he/she wishes (this functionality is currently available in course roster, and we want the same thing to happen on the student scores page.*

Enabling the 'add back to roster' functionality in the 'student scores' page would mix up the usage of the 'student roster and 'student scores' page. In my opinion, the ability to add/drop any student should be confined to the 'Student Roster' page. What do you guys think?

**Comment by nathanstitt** [comment]
yes, I agree, adding a student back to the course should only be possible from the roster.  If we do want to make it easier we could add a link to the roster page from the scores.  Maybe a small link above the dropped list, saying "[restore students from roster page]" or something like that

**Comment by carlycurran** [comment]
Yea, I just meant we want that functionality to remain. Sorry, not clear! I’ll update the card.

**Comment by carlycurran** [comment]
![Student Scores_01042019.jpg](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/7697e6e1-6c0d-4e6a-899d-a9c4121bb0bc)

**Comment by dkhowala** [comment]
[https://app.zenhub.com/files/150623529/ec29a924-2cc1-4390-ab2f-03f6ec15cb78/download](https://app.zenhub.com/files/150623529/ec29a924-2cc1-4390-ab2f-03f6ec15cb78/download)

**Comment by nathanstitt** [comment]
I'd suggest we either don't scroll the dropped list, or scroll it if there's more than say 5 students.

**Comment by carlycurran** [comment]
Yea, that makes sense. More importantly though, what happens if there are 100 students in the main active list. Will that window shrink to like 1-2 rows?

**Comment by dkhowala** [comment]
I noticed that the overall page scroll on the student's scores page behaves differently than the scroll on other pages. @nathan , If I can share my screen with you, you can probably understand my issue and explain better. This would help me to figure out ways to make the scroll more user-friendly. Let me know 10 quick minutes when I can disturb you.

**Comment by dkhowala** [comment]
![DroppedStudent ScoresComments_Tutor_01092019_DK.jpg](https://images.zenhubusercontent.com/5c12c502ea8fd844ba2fce8c/06fc1dff-88c8-4f55-82b5-11d5d556ee0e)

![DroppedStudentScores_Tutor_01112019_DK.jpg](https://images.zenhubusercontent.com/5c12c502ea8fd844ba2fce8c/a35434e1-8113-40b7-abbe-04265a299582)

I think the second option would help to address the scroll-related concerns. @nathan Let me know what you decide to work on.

**Comment by Malar-Natarajan** [comment]
Verified in Staging
