### ISSUE TITLE
Add lock icon

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#453]
### Description
Add lock icon to My Courses in the main menu and make this link unclickable and change the cursor to denied. 

Add lock icon to Manage Payment in the main menu and make this link unclickable and change the cursor to denied 

(font awesome icon)

### Acceptance Criteria
An instructor cannot click My Courses in student view mode
The instructor cannot click Manage Payment in student view mode
On hover, the cursor changes to denied 

### Acceptance Tests

derive these from "Acceptance Criteria" during the "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
https://docs.google.com/document/d/1eCgJafsZKsQPxkArHiC7_qFGLtWEHzYxZugzJ37mOVI/edit#

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- [x] If UX design is needed then the UX label is added
- [x] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [x] Release is selected

1C-DESIGN
- [x] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by dkhowala** [comment]
Redlining for the dashboard button: https://invis.io/PCSAXGQVZ59

To login and view: https://projects.invisionapp.com/d/main?origin=v7#/projects/prototypes/17676177

InVision Share Link
Click here to view the project Tutor_StudentView
Student View: Dashboard Button
InVision

@nathanstitt @carlycurran

**Comment by dkhowala** [comment]
Feature behavior List: https://docs.google.com/spreadsheets/d/1vx_zYQe8qi-uAeftsvXJpsJVTo_T38ks7oImByrUnNM/edit#gid=0

**Comment by nathanstitt** [comment]
implemented in https://github.com/openstax/tutor-js/pull/2616

**Comment by ejp3** [comment]
Verified in QA

**Comment by ejp3** [comment]
Verified in Staging

**Comment by Brooke-Fail** [comment]
Will verify in production once this feature is turned on and visible to users. Closing this card since the code is released.
Card to track verification is:
https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/519

**Comment by Brooke-Fail** [comment]
Verified in Production.
