### ISSUE TITLE
Instructor can choose which section/period to view as a student

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#454]
### Description
If there is one section in course, we drop instructor in that section
If there is more than one section, we can use a standard dropdown menu and let him/her pick which section 

### Acceptance Criteria
- Instructor with a course that only has one section does not have a choice of where to go. S/he goes directly to student view mode on click of "View as student" button. 
- Instructor with a course that has multiple sections sees a small down arrow on the "View as student" button. 
- When an instructor with a course that has multiple sections clicks the "View as student" button, s/he gets a dropdown with the section names and can click on any of them to view the corresponding section as a ghost student

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- [x] If UX design is needed then the UX label is added
- [x] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [x] Release is selected

1C-DESIGN
- [x] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by nathanstitt** [comment]
We've decided not to do this for v1.  Instead the button will simply choose the first active period.

**Comment by carlycurran** [comment]
@nathanstitt this part (selecting section/period for the ghost student) is still in phase 1, last we talked. Phase 2 has the assignment preview in it. 

Did anything come up with the section selection that's proving problematic?

**Comment by nathanstitt** [comment]
I got confused sorry @carlycurran - I actually came here to quietly delete the comment and then saw you'd already noticed.   I was looking at the mockup for the "single period" case

**Comment by carlycurran** [comment]
hahaha! "quietly delete the comment" 

ZH doesn't let me move columns -- or accidentally delete cards!! -- without an obvious trail :)

**Comment by nathanstitt** [comment]
implemented in https://github.com/openstax/tutor-js/pull/2616

**Comment by itsgeraldwang** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by Brooke-Fail** [comment]
Will verify in production once this feature is turned on and visible to users. Closing this card since the code is released.
Card to track verification is:
https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/519

**Comment by Brooke-Fail** [comment]
Verified in Production.
