### ISSUE TITLE
[draft, not ready for work] In Exercises, remove old APLO tags from AP Bio questions

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#455]
### Description
As an instructor in the CZI pilot or a member of OpenStax's research team, I want the old APLO tags removed from AP Bio questions, so that I can clearly see the current APLO tag and not be confused by the two tags.

![OldAPLOFormat](https://user-images.githubusercontent.com/7863733/58883598-5d532780-86a4-11e9-832c-692db9d4e6e2.png)

### Acceptance Criteria
- tags with the format `apbio-ch#-s#-aplo-#-#` have been removed from all assessments in exercises
- only tags with the format `aplo:stax-apbio:1.14` remain on the questions.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by openstaxalina** [comment]
@carlycurran I opened this per our discussion.  I suggest that we do this in July, after all the new tags back been assigned.  I think that we should look at this one more time once we have the new tags, just to make sure we want to remove the old ones.

**Comment by carlycurran** [comment]
@openstaxalina -- Dante did this during his APLO tag work

**Comment by openstaxalina** [comment]
thanks @Dantemss!  closing cc @carlycurran
