### ISSUE TITLE
Add UUID tie-breaker to assignment history order

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#456]
### Description
Add UUID tie-breaker to assignment history order

### Acceptance Criteria
Manually set up assignment in Tutor db because time is a tie-breaker down to the microsecond. 
Not clear there would be a visible change here. 

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [ ] Acceptance criteria are complete

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items
  - [ ] Estimate is updated
  - [x] Release is selected

1C-DESIGN
  - [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
  - [ ] Automated testing criteria are added to issue

2A-CODE
  - [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
  - [ ] The change has been approved by other developers
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] The acceptance tests are finalized
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
  - [ ] If UI changes, UX reviews and verifies on -dev or -qa
  - [ ] PDM reviews and verifies

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.

**Comment by Brooke-Fail** [comment]
This has passed regression testing on QA.

**Comment by Brooke-Fail** [comment]
Seems good in Staging too.

**Comment by Brooke-Fail** [comment]
Verified in Production.
