### ISSUE TITLE
HTML showing up in some exercise reading page titles

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#458]
### Description
Description

![Screen Shot 2019-06-05 at 12.53.34 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/9c13bbf1-594b-49e7-a26b-7b4d55231d11)

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
in the tab title

**Comment by nathanstitt** [comment]
The title is set on the BE on the tasked-tasked-exercise model where it sets the title for the exercise.  That probably needs some code to strip HTML out

**Comment by nathanstitt** [comment]
This is no longer being set so HTML is not an issue
