### ISSUE TITLE
new course sections and student estimate oddity

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#469]
### Description
Description

If someone inputs 0 for course sections or 0 for the student estimate during the new course wizard, the error talks about the number exceeding the maximum.

![Screen Shot 2019-06-10 at 3.52.48 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/649e23b1-e706-4c12-a5db-084b22100a48)

![Screen Shot 2019-06-10 at 3.52.34 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/8bc4c4c6-d0b7-4613-a07c-62fe1aac8ae3)

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by itsgeraldwang** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by ejp3** [comment]
Verified in Production
