### ISSUE TITLE
Teacher-as-a-student view: bookmarks and back button fixe

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#474]
### Description
- Don't throw an error when a user hit the back button right after clicking "view as student"
- Don't throw an error when a user bookmarks the teacher view and opens that bookmark in the student view

### Acceptance Criteria
- Allow a user to exit student view by clicking browser's back button.
- A bookmark works, in either view. 

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [x] Release is selected

1C-DESIGN
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by itsgeraldwang** [comment]
Still throws an error when hitting back button
![Screen Shot 2019-06-24 at 2.47.09 PM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/2575a7fe-6f95-4940-9237-32bca1687ca7)

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by Brooke-Fail** [comment]
Will verify in production once this feature is turned on and visible to users. Card to track verification is:
https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/519

**Comment by Brooke-Fail** [comment]
Verified in Production.
