### ISSUE TITLE
APUSH: Set key terms to appear bold but not italic

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#476]
### Description
Set key terms to appear bold but not italic

### Acceptance Criteria
Key terms should be bolded, but not italicized. If markup specifies italics, then the term should be italicized. 

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [x] Release is selected

1C-DESIGN
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by nathanstitt** [comment]
It looks to me like this has already the case, I tested as teacher01 at https://tutor-qa.openstax.org/book/2751/page/100825

I see them all bold with no italic.   Please link to a different example where they're incorrect if you know of one.

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/14b65d5f-2762-4543-87a4-cde66f3006da)

**Comment by openstaxalina** [comment]
@nathanstitt I got more information on this - this is referring to items in the content marked as < term >.  These should be bold, but not italic:

![termsbold](https://user-images.githubusercontent.com/7863733/62729676-10613980-b9e4-11e9-95cb-b2e66a7f5e35.png)

Source:
https://tutor-content.openstax.org/book/88/page/92304
which is pulling from
https://content05.cnx.org/contents/CmIfJ6vh:WzapCAyk

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
