### ISSUE TITLE
Error message displays in dashboard for few seconds after making payment from assignment link and also there is a delay in loading performance forecast

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#48]
1. Make a payment on course past the trial period using the assignment link. Once payment is successful, dashboard loads but the error with refresh button is still displays in Dashboard for few seconds
2. Once the error goes away, it takes few seconds to load the performance forecast section

Please see attached video for the time delay in QA

https://drive.google.com/file/d/1-jjdT2QMmmf3kp6gAbU78iU5PpU59gG7/view?usp=sharing

**Comment by carlycurran** [comment]
change: the modal will stay open until the page reload -- will hide error buttons and messages behind it. It will reload current page.

**Comment by Malar-Natarajan** [comment]
This scenario does not occur any more.
1. When the trial period is expired the expiry modal is displayed and making payment - displays the dashboard without any errors
2. When the trial period is expired and making payment via assignment link - takes to the assignment directly
3. Making payment using pay now button when the trial period is active - displays dashboard without any errors
