### ISSUE TITLE
APUSH: APLO Tags Not Displaying in Question Library

### ISSUE THREAD

**Issue by openstaxalina** [openstax/tutor#481]
### Description

Production teams can now add AP Learning Objectives to APUSH assessments -- woohoo!

These tags should display in the Question Library so that instructors can use them to select an assign assessments.  Currently they are not displaying.  This may hold up production and QA efforts.

**To Reproduce**
Steps to reproduce the behavior are
1. Go to 'https://tutor-content.openstax.org/course/88/questions#'
2. Get assessments for all sections, or at least 1.2
3. Review assessment ID 17564 and note that no APLO tag displays
(APLO tags start with HTS or RP)
4. Note that assessment ID 17564 is tagged with two HTS and one RP in Exercises.  (You can do this by searching by UID 17564 in Exercises: https://exercises.openstax.org/search)

**Expected behavior**
The HTS and RP tags should display, as they do on the assessment in Exercises:
![APUSHAPLOTags17564](https://user-images.githubusercontent.com/7863733/59804425-e9c03580-92b3-11e9-86af-1807da774ceb.png)

**Additional context**
Original card to implement APLO tags in APUSH: https://github.com/openstax/tutor/issues/385

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Currently can not verify in production since there are no AP courses released yet. Will reopen if there are any issues.
