### ISSUE TITLE
Teacher as Student View when clicking on scores results in an error

### ISSUE THREAD

**Issue by itsgeraldwang** [openstax/tutor#482]
### Description
On teacher01, course physics-dk, when you are in student view and click on any of the sections and click scores it will result in the following error:

![Screen Shot 2019-06-24 at 2.53.29 PM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/454692ee-1d35-46e7-870b-2c753ce4d423)

**To Reproduce**
Steps to reproduce the behavior are
Go to '...'

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
Going to scores in the menu

**Comment by ejp3** [comment]
Verified in QA

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Issue occurs in Production. It does not seem to happen all the time, I can reproduce it the easier with a new sociology course. 

https://tutor.openstax.org/course/5640/t/month/2019-08-05

user:
tt15

Click student view and click scores. Try this more than once, notice the error occurring.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
