### ISSUE TITLE
404 error when opening a reading assignment

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#483]
### Description
When opening a reading assignment as a student or when a teacher is viewing as a student, the user gets a 404 error. 

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor-qa.openstax.org as a student (or teacher)
2. Click on a course with a reading assignment
3. Open any reading assignment (in progress or have started)
4. Observe that there is a 404 error once the reading assignment loads

**Expected behavior**
The assignment loads with no errors.

**Screenshots**
![Screen Shot 2019-06-24 at 4.11.20 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/50ebc467-8e21-47c3-8f27-c3858a889d8a)

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by ejp3** [comment]
Verified in QA

**Comment by ejp3** [comment]
Verified in Staging

**Comment by ejp3** [comment]
Verified in Production
