### ISSUE TITLE
Individual review questions constantly switch between being loaded and loading

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#484]
### Description
When clicking on an individual review question that has not yet populated, the question will load at first then go back to loading and stay in a constant back and forth between loading and being loaded. 

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor-qa.openstax.org as a student
2. Click on any course that has individual review questions 
3. Click on a homework assignment (preferably one that is next in line to be due)
4. Click on any individual review question
5. Notice that the question is loaded and then starts loading again

**Expected behavior**
If BL has not loaded the question, a prompt to complete more will be shown and stay loaded. 

**Screenshots**
Video:
https://drive.google.com/file/d/1I35fpHhHFHl7JEP57cyDJ2vhckBc92wd/view?usp=sharing

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
