### ISSUE TITLE
Disable Tutor logo in student preview

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#486]
### Description
As a OpenStax I want the Tutor logo disabled in student view so that clicking the logo doesn't log the instructor out of student view.

### Acceptance Criteria
In student view, clicking the Tutor logo does nothing.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by carlycurran** [comment]
@nathanstitt I don't think I previously made a card for this. Sorry!

Does this make the most sense. Is disabling the logo in one specific view error prone?

cc @dkhowala

**Comment by ejp3** [comment]
Verified in QA

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
