### ISSUE TITLE
Remove student preview videos from Tutor

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#487]
### Description
As OpenStax  I want teachers to use the new student preview function and clear up the teacher interface so that the way to get a student preview is obvious and so that the interface remains uncluttered. 

Remove from: 
- Help menu
- HW builder
- RD builder

### Acceptance Criteria
No student preview videos live in Tutor. (They don't die there either. They're just gone. LOL)
- No video link in the Help menu
- No video button in the HW builder
- No video button in the RD builder

![Screen Shot 2019-06-25 at 4.34.31 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/ddcd8161-fa13-4eb1-997f-4ae6fc1685b2)
![Screen Shot 2019-06-25 at 4.34.55 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/508bd7a4-a8fb-4824-b36f-3d8a0574b268)
![Screen Shot 2019-06-25 at 4.35.20 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/bf5833dd-b964-47e6-bf7f-74e51d10f9ad)

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete

1B-DECOMP
- [] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [x] Release is selected

1C-DESIGN
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
