### ISSUE TITLE
APUSH: Keep parentheses with the content they enclose

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#488]
### Description
As an APUSH user, I want content within parentheses not to break, so that I can read dates, asides, etc. easily.

### Acceptance Criteria
A single parenthesis doesn't break to the next line. 

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by nathanstitt** [comment]
@carlycurran after investigating this some more this will be very difficult to do.

It's actually not anything we're doing, it's how the content is arranged, and CNX has the same issue.

To prevent this we'd need to include the () inside the `a` tag, or wrap it all in another tag like `span`

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/7901d848-085f-419a-8582-73ad1955478e)

**Comment by carlycurran** [comment]
ah, this is interesting. @openstaxalina, what do you think?

**Comment by openstaxalina** [comment]
@nathanstitt I think that this should be treated the same way that a single word would be, since there is no space between the open parenthesis and the link (I think).  Is there code that prevents single words from breaking across lines?   I'm wondering because I can't recall us having this issue with open parenthesis being allowed to break from their content on CNX.  CNX seems to be treating these cases like it would a single word.

[Example on CNX](https://content05.cnx.org/contents/CmIfJ6vh:4_mJkwz1):
![Screen Shot 2019-08-09 at 11 30 23 AM](https://user-images.githubusercontent.com/7863733/62794232-267d0180-ba99-11e9-8630-880254da9710.png)

[Same content on tutor-content](https://tutor-content.openstax.org/book/88/page/92251):
![Screen Shot 2019-08-09 at 11 30 01 AM](https://user-images.githubusercontent.com/7863733/62794247-34cb1d80-ba99-11e9-9d2b-b089f201d3db.png)

**Comment by Brooke-Fail** [comment]
This issue is still occurring in QA.

<img width="889" alt="Screen Shot 2019-08-13 at 1 29 09 PM" src="https://user-images.githubusercontent.com/48449285/62967387-72e47c00-bdce-11e9-9add-250d5ed7f199.png">

**Comment by nathanstitt** [comment]
@Brooke-Fail can provide the login and link to that content please?

**Comment by Brooke-Fail** [comment]
@nathanstitt  
teacher01
Course 2803
https://tutor-qa.openstax.org/book/2803/page/105410

**Comment by nathanstitt** [comment]
@Brooke-Fail @carlycurran and @openstaxalina - the content that Brooke found seems to be impervious to style changes.  I removed our `inline-block` style to match what CNX does, and that fixed quite a few spots but it still happens occasionally.

**Comment by openstaxalina** [comment]
Maybe we can release as-is and ask Wisewire to help us define any type of pattern in the spots where this still occurs...?

I looked at the markup, but I don't think there is a leading space or anything that could be causing that Figure 1.8 instance to break.

**Comment by carlycurran** [comment]
That sounds good to me, @openstaxalina. Finding a pattern would be helpful!

**Comment by nathanstitt** [comment]
yes, there's no space or anything between the ( and <a> tag.  it's also somewhat browser dependent, for instance I couldn't get safari to break like chrome did in the screenshot.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
