### ISSUE TITLE
Making payment from the assignment link loads student dashboard and not the assignment

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#49]
On a course past the trial period, make a payment using payment modal from assignment link. Once payment is made, student dashboard is displayed instead of the actual assignment via which student made the payment

Refer video

https://drive.google.com/file/d/1-jjdT2QMmmf3kp6gAbU78iU5PpU59gG7/view?usp=sharing

**Comment by nathanstitt** [comment]
Fixed in https://github.com/openstax/tutor-js/pull/2391 but can't link to this issue because it's linked to another one

**Comment by Malar-Natarajan** [comment]
Verified in QA
