### ISSUE TITLE
Reading assignments don't have breadcrumbs and gives an error when clicking the next arrow.

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#490]
### Description
Reading assignments do not have any breadcrumbs present and if the user is trying to complete the assignment, they get an error when clicking either Answer or the Next arrow.  

**To Reproduce**
Steps to reproduce the behavior are
1. Login as a student on tutor-qa
2. Click a course that has a reading assignment
3. Click on a reading assignment (in-progress or not started)
4. Notice that there are no breadcrumbs at the top
5. Try and click the next arrow or answer a question
6. Notice that an error is given

**Expected behavior**
Reading assignments have breadcrumbs and do not have any error when trying to complete the assignment. 

**Screenshots**
![Screen Shot 2019-06-26 at 4.53.57 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/a74c541d-ee24-4571-8f46-b9d0f03fb2a5)

Video:
https://drive.google.com/file/d/1ZfW2uoOrt6AvmzG6Vj8ZiLNXvRkm6Rpt/view?usp=sharing
**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
I get the same error for trying to complete a homework assignment as well.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
