### ISSUE TITLE
[Teacher View] "Tell us how you are using this course" nag shows up when clicking student view

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor#493]
### Description
If the teacher previously clicked on "I don't know yet" in this nag, it will show up when clicking to enter the student view.

**To Reproduce**
Steps to reproduce the behavior are
1. Login as a teacher
2. Create a new course and use/reload it until it displays the nag above, or find an existing course that displays the nag
3. Click "I don't know yet"
4. Click student view
5. The nag will show up again, even though it should never show for students

**Expected behavior**
The nag should not show up at all in student view.

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
