### ISSUE TITLE
Research Analytics link is available for all tutor users

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#495]
### Description
Research Analytics link should only be available for teachers with AP bio and AP physics courses. It is currently available for all teachers and students, including non-verified teachers. 

Accounts-
student:
bf22+71@rice.edu

teacher:
bf22+70@rice.edu

**To Reproduce**
Steps to reproduce the behavior are
1. Logon to tutor qa as teacher or student
2. Make sure the accounts does NOT have any AP courses
3. Click the Menu dropdown
4. Notice thats the uses has the Research Analytics link above Manage Payments

**Expected behavior**
The Research Analytics link is only available for teachers with AP bio or AP physics courses.

**Screenshots**
Unverified Teacher:
![Screen Shot 2019-06-27 at 2.13.34 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/7f5f2630-4cf6-4ca5-a81e-50a523f89d0e)

Student:
![Screen Shot 2019-06-27 at 2.14.40 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/5b2bdc4d-cefa-43aa-ac26-068e6dc97553)
**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Verified in QA!
Only teachers who have AP bio and AP physics courses can access the Research Analytics.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
