### ISSUE TITLE
Refreshing during an assignment in Student View will remove the exit Student View UI

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#498]
### Description
In teacher as student view, if the teacher is in the middle of completing an assignment and refreshes the browser, the UI for exit student view disappears. 

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor as a teacher
2. Click on a course with assignments 
3. Click on View as Student
4. Click on an assignment
5. When in the middle of an assignment (like a free response question), click refresh
6. Notice that the Exit Student View UI has disappeared and the teacher is still in student view able to continue with the assignment

**Expected behavior**
The user is either kicked back to the teacher dashboard and out of student view, or the UI is still present and the teacher is still in student view. 
(Expected Result needs to be decided)

**Screenshots**
![Screen Shot 2019-07-02 at 2.24.59 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/9a9bba9e-4448-436f-8bdf-b04f8b4375a0)

Video:
https://drive.google.com/file/d/1acvVLJcQUkKwJxMcZt_wG7fJdR7c6yFy/view?usp=sharing

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
Reason: teacher has permissions to see students assignments, but they have exited student view.  if they refresh. 

@carlycurran to look at decisions doc.

**Comment by nathanstitt** [comment]
We could either:
 * leave as-is, technically there's nothing wrong with a teacher viewing a student's assignment
 * leave them in student view
 * take them out of the HW back to teacher dash

**Comment by carlycurran** [comment]
Decision is to keep the teacher in the student view.

**Comment by dkhowala** [comment]
@nathanstitt @Dantemss @carlycurran 

"Additional context

You can exit the student view with the UI gone by clicking the Back to Dashboard button towards the bottom of the assignment"

This sounds wrong, on clicking on the 'Back to dashboard'  button in student view, the teacher shouldn't logout but should be taken to the student dashboard in the student view.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Getting this error when replicating the bug:
![Screen_Shot_2019-07-29_at_11.21.10_AM.jpg](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/e94bf6a2-9578-4e1f-948e-096faaff7817)

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
