### ISSUE TITLE
AP Bio - Learning objectives doubled

### ISSUE THREAD

**Issue by lwtchu** [openstax/tutor#499]
### Description
Looks like `BY THE END OF THIS SECTION, YOU WILL BE ABLE TO:` is hard coded into the template and the content. Therefore it appears duplicated. It should be removed from the AP Bio template.

**To Reproduce**
https://tutor-content.openstax.org/book/102/page/79066
It's on every page

**Expected behavior**
It doesn't duplicate

**Screenshots**
![Screen Shot 2019-07-03 at 10 40 23 AM](https://user-images.githubusercontent.com/11299125/60605415-188fde80-9d7f-11e9-9763-6d3a15190564.png)

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by Brooke-Fail** [comment]
Verified in Production.
