### ISSUE TITLE
Change Request: Provide test endpoint for Tutor assignments

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#50]
Stretch for end of Q4
or do in Q1

## Summary:
-----

It would be helpful, from a testing standpoint, to have the ability to create assignments and work assignments using an API endpoint.

## Current Behavior:
----

Use the UI to create an assignment (very slow and error-prone as a missed step in the process breaks the creation). Creating a past-due assignment means using the UI and assigning a due date to be very close to now (also error-prone). Working an assignment means using the UI for each student to submit answers.

*****

## Desired Behavior:
-----

Able to send a JSON package to a test endpoint specifying the setup for the assignment and allow for relaxed validation of start and due dates/times. For homeworks, allow a random selection of assessments from sections (eg 3 from 2.1, 4 from 2.2, and 3 Tutor-selected). For student work, send a JSON specifying the number correct (eg 2 correct from 2.1, 4 correct form 2.2, 1 correct from Tutor-selected).

This will be required for load testing the UI views.

*****

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
  - [ ] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [ ] Estimate is updated for the work item issues.
  - [ ] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2A-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by Dantemss** [comment]
I think we can use the existing API and just add a parameter that disables due date validation. That way we are also testing the real thing (minus the validation).

**Comment by Dantemss** [comment]
We decided to allow the user to specify the current time instead for this request (on qa/staging but not production).

**Comment by Brooke-Fail** [comment]
I keep getting multiple errors when trying to create a user, course, assignment ,etc.
