### ISSUE TITLE
Question formatting in AP Bio

### ISSUE THREAD

**Issue by theresamasciale** [openstax/tutor#500]
### Description
Some questions in AP Bio have odd formatting:

1. Number 4 in AP Bio Chapter 1 Review Questions has double spacing in its answer choices. This problem doesn't occur in other questions in this chapter nor does it occur in webview.
2. Numbers 20 and 21 in Chapter 1 Test Prep for AP Courses have the question start on the same line as the image. This does occur throughout the book, if the question has a figure in it.

**To Reproduce**
Steps to reproduce the behavior are
1. Go to 'Chapter 1: The Study of Life'
2. Click on 'Review Questions'
3. Scroll down to 'Question number 4'

1. Go to 'Chapter 1: The Study of Life'
2. Click on 'Test Prep for AP Courses'
3. Scroll down to 'Questions 20 and 21'

**Expected behavior**
Questions shouldn't be double spaced or have forced line breaks. It should have the same line spacing as other Q&As in this section.

Questions should also start on a new line from the figure. 

**Screenshots**
<img width="799" alt="Screen Shot 2019-07-03 at 11 08 24 AM" src="https://user-images.githubusercontent.com/47189012/60608247-a02c1c00-9d84-11e9-9779-376fb9d272eb.png">

<img width="792" alt="Screen Shot 2019-07-03 at 11 22 59 AM" src="https://user-images.githubusercontent.com/47189012/60608603-73c4cf80-9d85-11e9-923c-1c3ea7ff4d84.png">

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: AP Bio  
**categories**: formatting

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
looks like the double spacing is because `p` tags are used and reference view adds margin to the bottom of `p` tags so the normal para tags look better

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/8b01e578-063a-491f-9cb8-84fa4c15f545)

**Comment by carlycurran** [comment]
@theresamasciale will you into the figure on exercises? Is that formatted that way?

Also, for question 4, it looks like there are P tags in the question.

**Comment by carlycurran** [comment]
@theresamasciale 
Question 4 in the screenshot is Ex 6 v4. 
There is a dupe that's 4619 -- it does NOT have the p tags. 

Exercises should allow you to add an image , we allow some attributes. We are sanitizing some parts of the style. 

Can put a diff or a p-tag around the images, and that will force them to be block.   (v 17.13 of the book has this update)

**Comment by nathanstitt** [comment]
For the inline images:
 * AP Bio with the issue has version `17.12` 
 * In version `17.13` the images were wrapped in `p` tags which fixed the issue.

**Comment by theresamasciale** [comment]
For double-spaced issue: double spaces will be fixed by the content team in exercises. As for the duplication issue, the "duplicate" is not tagged AP Bio (it's tagged to concepts of bio).

For images in question issue: the version is correct; however, it's pulling in the exercise from exercises and each question with an image will need to be fixed by the content team.

Solution: the content team will go through all exercises in the book next.
