### ISSUE TITLE
Learning Objectives Header Missing AP Phys

### ISSUE THREAD

**Issue by marcjeannott** [openstax/tutor#501]
### Description
Each Learning Objective found at the start of every module is missing. The text "By the end of this section..." correctly shows. It just needs it's header. 

**To Reproduce**
Steps to reproduce the behavior are
1. Go to 'https://tutor-content.openstax.org/book/101/page/79494'
2. Scroll down to 'text right after the splash image'

**Expected behavior**
Header Learning Objectives appears.

**Screenshots**
![Missing Learning Objectices](https://user-images.githubusercontent.com/33228728/60609362-22b5db00-9d87-11e9-9f6b-a4c2aa2fbead.jpg)

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
On cnx the content has a h3 learning objectives text: https://cnx.org/contents/jQSmhtXo@23.4:L4pdOADV@7/1-1-Physics-An-Introduction

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/670ad51c-465a-47ff-a52d-55eda70603bf)

but there's no h3 tag with the text on the tutor import

**Comment by theresamasciale** [comment]
Note from Alina: it's OK that AP Phys has "Learning Objectives" header and AP Bio does not. So the header should be placed in to AP Phys only to match the book on CNX.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
