### ISSUE TITLE
Double Titles in Tables need reformatting [AP Bio]

### ISSUE THREAD

**Issue by theresamasciale** [openstax/tutor#503]
### Description
Tables with double row titles are not formatted correctly in Tutor. The main title comes through as italic text, without an indention so it appears as if it belongs to the paragraph before. 

**To Reproduce**
Steps to reproduce the behavior are
1. Go to 'Tutor Content > AP Bio > "Structure and Function of Plasma Membranes"'
2. Click on '5.1 Components and Structure https://tutor-content.openstax.org/book/102/page/79108'
3. Scroll down to 'Table 5.1'

**Expected behavior**
Both title rows should be formatted the same. In this particular case, the top title, "The Components and Functions of the Plasma Membrane" should not be floating italic text but rather bold, aligned to the other rows, and appear to go with the table.

**Screenshots**

![Screen Shot 2019-07-08 at 1.53.47 PM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/8eeb2b99-4d47-4159-a753-1d9a2938f35a)

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: AP Bio  
**categories**: Book Content
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
