### ISSUE TITLE
Large Splash Images AP Physics

### ISSUE THREAD

**Issue by marcjeannott** [openstax/tutor#504]
### Description
All the splash images in AP Physics are very large and square. Splash images are usually rectangle and not square, but more importantly the large image size distorts a lot of the smaller splash images from CNX

**To Reproduce**
Steps to reproduce the behavior are
1. Go to 'Section 15.4 in Tutor'
2. See error

**Expected behavior**
See CNX

**Screenshots**
![2019-07-09_10-32-17](https://user-images.githubusercontent.com/33228728/60903758-90568100-a237-11e9-8906-a6b5beba7915.jpg)

**Additional context**
We may need to change the template to make the images less big, or find new splash images. 

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
note that the image shown in AP Physics  15.4 still looks a little pixelated after the fix.  that's be because the content.  The image has a "width" attribute set to 400px but the image itself is only 375

**Comment by ejp3** [comment]
Verified in QA

**Comment by itsgeraldwang** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
