### ISSUE TITLE
Salesforce is not getting (some) data from Tutor

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor#508]
### Description
Salesforce is not getting some data from Tutor. In particular, data about courses created within 1 minute of a new account being created is not being sent due to a bug.

This happens because when a new account is created, Tutor does not set the salesforce_contact_id field. Instead, that field is only set when the accounts sync about 1 minute later.

Additionally, due to another bug, Tutor is not sending emails about certain salesforce errors to tutor-notifications@openstax.org

**To Reproduce**
SF data:
1. Create an account in Accounts. Do not login to Tutor.
2. Mark the account as college and faculty in the SF sandbox (or Accounts itself)
3. Wait until around 10 seconds after the next minute to give you maximum time.
3. Login to Tutor and quickly create a new course (or preview course).
4. Error is sent to Sentry. No data about the course is sent to SF.

SF errors:
1. Ask devs to figure out a way to cause a Salesforce error manually...
2. Errors should show up in Sentry

**Expected behavior**
SF data:
SF gets the data.
Sentry does not get an error.

SF errors:
SF errors show up on Sentry

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [x] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Dantemss** [comment]
Connected PR is https://github.com/openstax/accounts-rails/pull/78
Can't actually connect it because that repo belongs to BIT I think
Once approved, merged and released, another PR will have to be created for Tutor.

**Comment by Brooke-Fail** [comment]
Will test this in Staging. The QA environment is not working in SF sandbox to verify.

**Comment by Brooke-Fail** [comment]
Verified in staging.

**Comment by Brooke-Fail** [comment]
This will need to be verified in staging.

**Comment by Brooke-Fail** [comment]
Dante is still seeing errors after this has been deployed to Production.
