### ISSUE TITLE
Exercises: Drop an author and take ownership of assessments

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#511]
### Description
At the end of vendor assessment creation, OpenStax wants to take over ownership of the assessments (done at the book level, en masse) so that vendors can’t make any more edits (and OpenStax can)

An account can have two authors (OSX and WW) and an exercises admin can remove a vendor (WW) when the assessment production process is done.  When WiseWire is dropped from the account, they no longer have authorship over the assessments built in that account. 

### Acceptance Criteria
OpenStax can take over authorship of assessments created by a vendor, en masse. 

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [x] Release is selected

1C-DESIGN
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by carlycurran** [comment]
@Dantemss, I'm curious about how this will work, in terms of the authorship of all the assessments changing when one account holder is dropped?

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
The dashboard for this feature is working, closing based on Staging testing success.
