### ISSUE TITLE
Opening Student view for a course or a section for the first time will result in an unsuccessful redirect.

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#514]
### Description
When opening a course or section of a course for the first time, student view will not launch correctly. If it is the first time using Student view on a course or course section, the user will have to click student view again for it to launch properly. The first click instance results in a failed redirect. 

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor as an instructor with an AP BIo or AP Physics course 
2. Click on an AP course (or course section) that has not used teacher as student view before
3. Click the view as student button 
4. Notice that the page is not redirected to student view
5. Click the view as student button again
6. Notice how the second click will work and bring the user into the student view

**Expected behavior**
Clicking on view as student button redirects to student view on the first click.

**Screenshots**
Video for course section:
https://drive.google.com/file/d/1Wa-4n4bjrIYtb7YfMU0iKNrufVpHVhvi/view?usp=sharing

Video for course:
https://drive.google.com/file/d/1z2dtWMunmT3LKxgdEsUnMWAqeNIHqYmU/view?usp=sharing

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
I think this is probably a dupe of an earlier bug that we've fixed.  moving to verification so we can re-test

**Comment by Brooke-Fail** [comment]
This is still occurring on QA @nathanstitt

**Comment by nathanstitt** [comment]
Fixed in https://github.com/openstax/tutor-js/pull/2670

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
