### ISSUE TITLE
step issues when a reading has multiple interstitial cards

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#516]
### Description
Description

https://openstax.slack.com/files/U0F58C65R/FLFU0HRFE/reading_falling_back.mov

michelle.terrell.1ef@restmail.net
https://tutor-qa.openstax.org/course/2746/task/380684/step/17

causing the maze game question to be used twice?

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
seems like it only happens with brand new students who have not seen interstitial cards yet

**Comment by carlycurran** [comment]
looks this is fixed (green bar going back and forth) without clicking too fast. 

The clicking too fast will be fixed in 590.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
