### ISSUE TITLE
Some CLUes never get processed by biglearn-sparfa-server under certain conditions

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor#518]
### Description
After a student changes their answer to a problem, biglearn-scheduler may ask biglearn-sparfa-server for CLUes based on their old + new answers. Sparfa-server only keeps track of the newest answer (based on the answers' trial_uuid), so it thinks it has not received the (old) answer yet and punts on calculating the CLUe until that is received. It doesn't know that it already received the old answer and that got overwritten by the new answer, so it will never process those CLUes.

**To Reproduce**
Run biglearn-sparfa on production (or staging data). Really no better way to reproduce this.

**Expected behavior**
biglearn-sparfa-server should (eventually) process all CLUes.

### Checklist for Done
2-CODE
  - [x] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
CLUes are processed in QA and are 90% in Staging.

**Comment by Brooke-Fail** [comment]
Will close if there are any hangups or slowdowns.
