### ISSUE TITLE
It is possible to get multiple nudges on the same question when there should only be one.

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#521]
### Description
Submitting a free response with gibberish words will trigger a nudge. If the user navigates away from that question before submitting an answer and then goes back, another nudge could be triggered if they have another gibberish response. 

Launching spy mode, you can see the nudge stays on the question until an answer is submitted. It is possible for the user to continue to trigger nudges until the submit an answer. 

Account:
bf22+18@rice.edu (production)

Course:
5507

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor as a student
2. Click in the bottom left corner and enable spy mode
3. Click on and course that has an assignment
4. Go to a question that has a free response 
5. Input a gibberish answer to trigger the nudge
6. When the nudge is triggered, navigate away from the question (by using the back button, going to course menu, or going to a different question)
7. Go back to the question from before
8. Notice that the spy mode nudge results are still present and the user has another chance to input a gibberish response, resulting in another nudge for the same question. 

**Expected behavior**
Only one nudge is triggered per question. 

**Screenshots**
Video attached:
https://drive.google.com/file/d/1FzEN0olCqTz-cQtLFiE--aCDRoILpehn/view?usp=sharing

**Additional context**
- Occurs for homework and readings 
- Does not occur with a page refresh

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
I think this has been fixed by the recent bug fix on steps.  I'm unable to replicate it now, so let's retest.

**Comment by Brooke-Fail** [comment]
This seems to still be occurring. 
Video:
https://drive.google.com/file/d/18bzjujb3PXpeNRiVJV2LM4GPB5-rgl0u/view?usp=sharing

**Comment by Dantemss** [comment]
The current behavior is that we validate the answer twice, display the message once as long as they answer twice in a row. If they reload or move back and forth we reset this so they will get the message again. We have discussed and decided that the current behavior is pretty good and we'll keep it, so this is a "won't fix".
