### ISSUE TITLE
Can not open an assignment that has been saved as a draft

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#523]
### Description
When creating an assignment you can save it as a draft. When trying to open an assignment that has been saved as a draft, the url says invalid%20date and the page will eventually ask for you to wait or kill the page. Eventually you will have to close the browser and relaunch. The assignment can't be opened even if the browser has been closed and reopened. 

Course:
https://tutor-qa.openstax.org/course/2750/t/month/2019-07-23

Account:
Teacher01

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor as an instructor
2. Click on a course
3. Start creating an assignment and save it as a draft
4. Once the draft is saved, click on the assignment
5. Notice that the page will ask if you want to wait or kill it. Eventually resulting in the assignment that's saved as a draft o not be able to be opened. 

**Expected behavior**
All assignments can be edited successfully. 

**Screenshots**
Url the assignment shows when clicked:
https://tutor-qa.openstax.org/course/2750/t/month/Invalid%20date

https://drive.google.com/file/d/14DTqUV5yOdxhklrffOs8dHftsSgglZfe/view?usp=sharing**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
Fixed by https://github.com/openstax/tutor-js/pull/2670

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by Brooke-Fail** [comment]
Verified in Production.
