### ISSUE TITLE
Change: Baked books - Numbering is wonky

### ISSUE THREAD

**Issue by lwtchu** [openstax/tutor#53]
![Screen Shot 2018-10-11 at 12.50.19 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/34ff3e29-4efa-42d1-b2c1-8da1286db65e)

A few things happening here:
- The recipe already has a number. Hence the `<span os-number>` thing. Which is causing this weird double numbering.
- Therefore Glossary, Section Summary, Conceptual Questions, Problems & Exercises isn't double numbered because Chapter Review is collated. These should not be numbered or any other end of chapter section. 
- Introduction should also not have the 1.1 numbering prepopulated by tutor

**Comment by carlycurran** [comment]
Still seeing the introduction labeled with a 1.1
