### ISSUE TITLE
Remove "tell us how you are using this course" nag (and fix terms, tours, nags interrupting each other)

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor#539]
### Description
As a teacher I want less nags so that I can use the site more easily.

### Acceptance Criteria
Full-course nag (tell us how you are using this course) no longer appears.
Terms of use, nags and tours as teacher/student in full/preview courses do not interrupt each other.

### Acceptance Tests
**title**: Nags don't interrupt each other
**categories**: Interactive Component, Navigation
> GIVEN a new teacher and a preview course
> WHEN the teacher clicks the course for the first time 
> THEN the terms, tour and any nags show up in an orderly fashion and do not interrupt each other

**title**: No full-course nag
**categories**: Interactive Component, Navigation
> GIVEN a teacher and a new full course
> WHEN the teacher clicks the course for the first time 
> THEN the "tell us how you are using this course" nag no longer shows up

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [x] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [x] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [x] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by Brooke-Fail** [comment]
The only issue I found was that, for a new student, the terms pop up shows up after the student dashboard has been shown for a few seconds. 

Video:
https://drive.google.com/file/d/1Nik2tTb7XC_8cg2o1jTaMi6yMHL3tz0J/view?usp=sharing

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in production.
