### ISSUE TITLE
The user gets a error when trying to edit a copied over reading assignment before publishing

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#541]
### Description
When copying a course, assignment can be copied over and edited to that course. If an instructor tries to edit a copied reading assignment before it is publish, they get an error. 

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor as an instructor
2. Click on a copied course that has assignments to copy over
3. Copy over a reading assignment into the calendar
4. Before publishing, click Edit more assignment details
5. Notice that an error is triggered

**Expected behavior**
The instructor is not able to edit a copied reading assignment until it is published or they are able to edit a copied assignment before it is published. Expected behavior needs to be decided.

**Screenshots**
![Screen Shot 2019-08-12 at 11.31.17 AM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/8af1ba6a-ca4d-4466-b010-38382b953764)

**Additional context**
- The copied reading assignment can be edited and saved correctly if the assignment is published first. 

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
this is getting fixed in Wednesday's release
