### ISSUE TITLE
Review metrics 'Back to Scores' button hidden

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#544]
### Description
Description

When viewing the review metrics for an assignment, the toolbar with the 'Back to Scores' button and the assignment name disappear after begin displayed for a short time. The instructor would have to use the browser's back button or the menu to leave the screen.

**To Reproduce**
Steps to reproduce the behavior are
1. log in as an instructor
2. select a course with at least one homework or reading (preferably with student work)
3. view the scores page
4. click on the assignment 'Review' link
5. watch the top right of the metrics page as it's loading

**Expected behavior**

the secondary bar doesn't go away/get hidden

**Screenshots**

https://slack-files.com/T0F5B5PGQ-FM9Q4TL8M-35a6bcb467

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
