### ISSUE TITLE
422 error when the user has A LOT of courses 

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#546]
### Description
When a user reaches a certain number of courses, they will frequently get a 422 error when navigating through their courses in the teacher dashboard.

User:
teacher01

Course:
Any

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor as an instructor
2. Click on any curse
3. Navigate through the buttons in the teacher dashboard (like clicking the Ass Assignment menu)
4. Notice the 422 error that is triggered

**Expected behavior**
There is no error given or the use ris prompted to delete/archive older courses because they are reaching the limit. 

**Screenshots**
![Screen Shot 2019-08-15 at 10.49.25 AM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/3ec81437-3fd0-47f1-896e-b523c83f1b19)

**Additional context**
I've only had this issue happen with teacher01 in QA. Not sure if there are other accounts that have the same amount of courses and assignments. 
### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
could capture this error and truncate UI settings

**Comment by nathanstitt** [comment]
@bonnebbrown after you got the error, were you able to continue working or did it pop-up repeatedly?

**Comment by Brooke-Fail** [comment]
@nathanstitt you can continue working but it pops up after each button selection while in the teacher dashboard.

**Comment by gregfitch** [comment]
<img width="1308" alt="Screen Shot 2019-08-30 at 10 08 59 AM" src="https://user-images.githubusercontent.com/8904283/64031706-961d6400-cb0e-11e9-84ab-d64e57db7b1c.png">

```"{\"ui_settings\":{\"personalized-info-reading\":{\"taskId\":\"338439\",\"stepId\":\"5068484\"},\"two-step-info-reading\":{\"taskId\":\"338439\",\"stepId\":\"5068484\"},\"sessionCount\":1636,\"PL\":{\"2025\":true,\"2039\":true,\"2042\":true,\"2074\":true,\"2247\":true,\"2547\":true,\"2609\":true,\"2750\":true,\"2755\":true,\"2756\":true},\"DBVC\":{\"1\":3,\"3\":4,\"4\":1,\"249\":3,\"462\":1,\"485\":3,\"525\":1,\"566\":3,\"583\":1,\"592\":1,\"593\":1,\"610\":2,\"1764\":3,\"1780\":3,\"1798\":4,\"1800\":1,\"1816\":3,\"1831\":1,\"1833\":5,\"1849\":5,\"1852\":2,\"1865\":2,\"1893\":2,\"1936\":2,\"1962\":4,\"2003\":2,\"2004\":1,\"2022\":1,\"2024\":3,\"2025\":19,\"2036\":3,\"2037\":3,\"2039\":1,\"2042\":2,\"2043\":11,\"2052\":78,\"2053\":5,\"2054\":3,\"2073\":5,\"2074\":15,\"2075\":5,\"2076\":15,\"2078\":17,\"2079\":20,\"2080\":5,\"2082\":26,\"2083\":3,\"2117\":6,\"2118\":9,\"2119\":5,\"2120\":1,\"2121\":9,\"2122\":2,\"2123\":1,\"2124\":7,\"2125\":40,\"2128\":5,\"2129\":4,\"2133\":11,\"2135\":3,\"2136\":9,\"2140\":2,\"2141\":4,\"2142\":3,\"2143\":12,\"2144\":5,\"2147\":8,\"2151\":2,\"2157\":4,\"2158\":13,\"2159\":3,\"2166\":3,\"2170\":1,\"2172\":2,\"2174\":15,\"2176\":6,\"2177\":15,\"2178\":17,\"2184\":6,\"2185\":16,\"2186\":14,\"2205\":14,\"2209\":3,\"2217\":2,\"2220\":12,\"2221\":7,\"2237\":31,\"2240\":4,\"2243\":6,\"2244\":21,\"2245\":5,\"2246\":25,\"2337\":29,\"2340\":6,\"2341\":23,\"2345\":22,\"2346\":35,\"2348\":6,\"2349\":32,\"2353\":32,\"2354\":51,\"2355\":32,\"2369\":50,\"2372\":14,\"2373\":14,\"2375\":14,\"2376\":7,\"2377\":24,\"2378\":18,\"2388\":29,\"2389\":13,\"2392\":73,\"2396\":21,\"2397\":59,\"2400\":12,\"2401\":43,\"2402\":3,\"2403\":5,\"2411\":5,\"2415\":4,\"2420\":3,\"2421\":5,\"2422\":7,\"2423\":2,\"2426\":5,\"2427\":2,\"2428\":8,\"2429\":3,\"2430\":14,\"2432\":1,\"2433\":9,\"2434\":9,\"2435\":63,\"2456\":4,\"2469\":30,\"2475\":5,\"2476\":4,\"2477\":1,\"2478\":7,\"2479\":52,\"2480\":19,\"2481\":18,\"2482\":18,\"2483\":115,\"2485\":18,\"2504\":29,\"2543\":13,\"2548\":40,\"2550\":7,\"2551\":4,\"2552\":21,\"2553\":55,\"2557\":6,\"2558\":15,\"2561\":24,\"2573\":1,\"2577\":5,\"2578\":25,\"2581\":11,\"2584\":10,\"2586\":7,\"2587\":7,\"2588\":4,\"2589\":4,\"2590\":2,\"2591\":6,\"2592\":24,\"2607\":4,\"2608\":6,\"2609\":38,\"2646\":10,\"2653\":23,\"2668\":13,\"2669\":25,\"2686\":36,\"2692\":19,\"2696\":38,\"2709\":29,\"2710\":1,\"2723\":16,\"2747\":35,\"2750\":54,\"2751\":75,\"2753\":6,\"2754\":48,\"2755\":23,\"2756\":11,\"2757\":35,\"2758\":28,\"2802\":7,\"2803\":5,\"2805\":15,\"2809\":5,\"2810\":11,\"2813\":4},\"spaced-practice-info-homework\":{\"taskId\":\"348921\",\"stepId\":\"5175256\"},\"OBC\":{\"1816\":\"dn\",\"1852\":\"exc\",\"1893\":\"exc\",\"2003\":\"cc\",\"2004\":\"dn\",\"2024\":\"exc\",\"2025\":\"exc\",\"2036\":\"exc\",\"2037\":\"exc\",\"2042\":\"dn\",\"2043\":\"dn\",\"2052\":\"cc\",\"2053\":\"exc\",\"2073\":\"exc\",\"2074\":\"exc\",\"2075\":\"dn\",\"2076\":\"exc\",\"2078\":\"exc\",\"2079\":\"exc\",\"2080\":\"exc\",\"2082\":\"dn\",\"2083\":\"dn\",\"2117\":\"dn\",\"2118\":\"exc\",\"2119\":\"cc\",\"2120\":\"exc\",\"2121\":\"dn\",\"2122\":\"exc\",\"2123\":\"dn\",\"2124\":\"dn\",\"2125\":\"exc\",\"2128\":\"exc\",\"2129\":\"exc\",\"2135\":\"exc\",\"2140\":\"exc\",\"2141\":\"exc\",\"2143\":\"exc\",\"2144\":\"dn\",\"2147\":\"dn\",\"2151\":\"exc\",\"2157\":\"dn\",\"2158\":\"exc\",\"2174\":\"exc\",\"2176\":\"dn\",\"2177\":\"dn\",\"2178\":\"exc\",\"2185\":\"dn\",\"2186\":\"dn\",\"2205\":\"exc\",\"2209\":\"exc\",\"2217\":\"dn\",\"2220\":\"cc\",\"2221\":\"dn\",\"2237\":\"exc\",\"2240\":\"dn\",\"2243\":\"exc\",\"2244\":\"cc\",\"2245\":\"dn\",\"2246\":\"dn\",\"2337\":\"dn\",\"2340\":\"dn\",\"2341\":\"cc\",\"2345\":\"cc\",\"2346\":\"cc\",\"2348\":\"dn\",\"2349\":\"exc\",\"2353\":\"dn\",\"2354\":\"dn\",\"2355\":\"exc\",\"2369\":\"exc\",\"2372\":\"dn\",\"2373\":\"exc\",\"2375\":\"dn\",\"2376\":\"dn\",\"2377\":\"exc\",\"2378\":\"exc\",\"2388\":\"cc\",\"2389\":\"dn\",\"2392\":\"exc\",\"2396\":\"dn\",\"2397\":\"exc\",\"2401\":\"dn\",\"2402\":\"exc\",\"2403\":\"dn\",\"2411\":\"dn\",\"2415\":\"dn\",\"2420\":\"exc\",\"2421\":\"exc\",\"2422\":\"dn\",\"2426\":\"exc\",\"2427\":\"dn\",\"2428\":\"dn\",\"2429\":\"dn\",\"2430\":\"exc\",\"2433\":\"dn\",\"2434\":\"exc\",\"2435\":\"exc\",\"2469\":\"exc\",\"2477\":\"dn\",\"2479\":\"exc\",\"2480\":\"exc\",\"2481\":\"exc\",\"2482\":\"exc\",\"2483\":\"cc\",\"2485\":\"exc\",\"2504\":\"exc\",\"2543\":\"exc\",\"2548\":\"exc\",\"2550\":\"exc\",\"2551\":\"dn\",\"2552\":\"exc\",\"2553\":\"exc\",\"2557\":\"dn\",\"2558\":\"cc\",\"2561\":\"dn\",\"2577\":\"dn\",\"2578\":\"dn\",\"2587\":\"dn\",\"2589\":\"exc\",\"2591\":\"exc\",\"2592\":\"exc\",\"2607\":\"cc\",\"2608\":\"dn\",\"2609\":\"dn\",\"2646\":\"dn\",\"2653\":\"exc\",\"2668\":\"dn\",\"2669\":\"exc\",\"2686\":\"exc\",\"2692\":\"dn\",\"2696\":\"exc\",\"2709\":\"exc\",\"2710\":\"dn\",\"2723\":\"exc\",\"2747\":\"exc\",\"2750\":\"exc\",\"2751\":\"exc\",\"2753\":\"dn\",\"2754\":\"exc\",\"2755\":\"dn\",\"2757\":\"exc\",\"2758\":\"dn\"},\"OBNT\":{\"1816\":1526919495721,\"1852\":1529519591001,\"1893\":1529519655844,\"2003\":1527265240115,\"2004\":1526328300754,\"2024\":1532637256736,\"2025\":1525810250984,\"2036\":1529519916516,\"2037\":1529519861599,\"2042\":1529527957830,\"2043\":1525810104139,\"2052\":1527265224967,\"2053\":1529519904748,\"2073\":1529519890686,\"2074\":1526054928507,\"2075\":1531928322953,\"2076\":1529519836091,\"2078\":1529605741293,\"2079\":1530138874477,\"2080\":1529519847925,\"2082\":1531854165260,\"2083\":1529519816489,\"2117\":1526913827972,\"2118\":1529519802524,\"2119\":1527265277778,\"2120\":1529519778704,\"2121\":1533582731369,\"2122\":1529519768146,\"2123\":1527697037664,\"2124\":1530808960742,\"2125\":1527691643919,\"2128\":1532637240068,\"2129\":1529519744682,\"2135\":1529519725774,\"2140\":1529519702575,\"2141\":1529071930937,\"2143\":1530635666346,\"2144\":1530548133130,\"2147\":1529351434918,\"2151\":1529519673771,\"2157\":1531424023619,\"2158\":1541952943026,\"2174\":1529691377261,\"2176\":1530043700419,\"2177\":1533328527718,\"2178\":1533312441968,\"2185\":1530547979953,\"2186\":1533654511422,\"2205\":1531323802869,\"2209\":1532637268200,\"2217\":1531411572225,\"2220\":1533582561314,\"2221\":1548186948063,\"2237\":1533572135106,\"2240\":1531923847044,\"2243\":1557242630642,\"2244\":1532709884334,\"2245\":1533328512574,\"2246\":1535570435593,\"2337\":1535035565906,\"2340\":1535479106276,\"2341\":1535036224552,\"2345\":1536087883569,\"2346\":1536087895130,\"2348\":1538420565624,\"2349\":1539105359369,\"2353\":1543358656999,\"2354\":1543359386739,\"2355\":1543422987293,\"2369\":1541541545058,\"2372\":1543358596975,\"2373\":1557242630033,\"2375\":1552505351910,\"2376\":1543508917737,\"2377\":1543528708014,\"2378\":1543597409573,\"2388\":1543940252266,\"2389\":1549295591976,\"2392\":1547567370712,\"2396\":1548186948440,\"2397\":1547068298522,\"2401\":1547746920611,\"2402\":1548784022530,\"2403\":1548183795808,\"2411\":1553614836113,\"2415\":1560195977000,\"2420\":1550853066360,\"2421\":1560803595897,\"2422\":1555441954301,\"2426\":1557240402385,\"2427\":1551196947622,\"2428\":1552414331436,\"2429\":1557861137914,\"2430\":1557177919639,\"2433\":1560194789962,\"2434\":1552321321364,\"2435\":1553106562373,\"2469\":1553022576899,\"2477\":1556913555323,\"2479\":1556920152441,\"2480\":1553373221859,\"2481\":1557155581660,\"2482\":1557155582402,\"2483\":1557155582281,\"2485\":1556920152050,\"2504\":1555118061634,\"2543\":1555442169355,\"2548\":1559164007051,\"2550\":1557155582461,\"2551\":1557155582203,\"2552\":1558101433555,\"2553\":1557155582042,\"2557\":1560203959002,\"2558\":1558721969463,\"2561\":1558637578179,\"2577\":1559680647132,\"2578\":1560203959002,\"2587\":1559311912890,\"2589\":1560097265735,\"2591\":1563210838220,\"2592\":1561944295556,\"2607\":1561401497578,\"2608\":1561401564459,\"2609\":1563891337129,\"2646\":1561390371780,\"2653\":1562772351914,\"2668\":1563891288417,\"2669\":1562772436369,\"2686\":1561134755779,\"2692\":1561581662165,\"2696\":1562385083417,\"2709\":1562937910445,\"2710\":1561577124499,\"2723\":1562538174141,\"2747\":1564779495039,\"2750\":1563485650258,\"2751\":1564500999805,\"2753\":1564085477550,\"2754\":1564066847445,\"2755\":1564779481075,\"2757\":1564498430474,\"2758\":1565291334954},\"ox-notifications-accounts\":[],\"CSB\":{\"485\":true,\"1831\":true,\"2004\":false,\"2036\":true,\"2042\":true,\"2052\":true,\"2074\":true,\"2079\":true,\"2080\":false,\"2082\":true,\"2118\":true,\"2119\":true,\"2125\":true,\"2129\":true,\"2133\":true,\"2142\":false,\"2158\":true,\"2174\":true,\"2178\":true,\"2184\":true,\"2186\":true,\"2205\":true,\"2237\":true,\"2243\":true,\"2244\":true,\"2246\":true,\"2337\":true,\"2348\":true,\"2349\":true,\"2353\":true,\"2354\":true,\"2355\":true,\"2369\":true,\"2372\":true,\"2375\":true,\"2376\":false,\"2377\":true,\"2378\":true,\"2389\":true,\"2392\":false,\"2397\":true,\"2401\":true,\"2402\":true,\"2403\":true,\"2415\":true,\"2423\":false,\"2435\":true,\"2469\":false,\"2478\":true,\"2479\":true,\"2480\":true,\"2481\":true,\"2482\":true,\"2483\":false,\"2504\":false,\"2543\":true,\"2548\":true,\"2553\":false,\"2557\":true,\"2558\":true,\"2561\":true,\"2578\":false,\"2581\":true,\"2584\":true,\"2586\":true,\"2589\":true,\"2592\":true,\"2646\":true,\"2653\":true,\"2668\":false,\"2669\":true,\"2686\":true,\"2692\":true,\"2696\":true,\"2709\":true,\"2723\":true,\"2757\":false,\"2758\":true,\"2802\":false,\"2805\":true},\"lmsv\":{\"2117\":\"canvas\",\"2142\":\"sakai\",\"2143\":\"d2l\",\"2144\":\"moodle\",\"2176\":\"sakai\",\"2433\":\"canvas\",\"2477\":\"blackboard\",\"2550\":\"blackboard\",\"2553\":\"canvas\"},\"sclp\":{\"2117\":\"2018-05-17T17:18:58.001Z\"},\"ox-notifications-tutor\":[],\"is_scores_averages_expanded\":true,\"sce\":{\"1764\":\"2018-07-13T15:19:33.003Z\",\"2349\":\"2018-09-13T17:59:58.001Z\",\"2353\":\"2018-09-17T20:08:56.001Z\",\"2354\":\"2018-09-17T21:47:18.002Z\",\"2355\":\"2018-09-21T16:00:22.007Z\",\"2392\":\"2019-02-04T22:49:27.002Z\",\"2411\":\"2019-01-29T22:27:17.001Z\",\"2435\":\"2019-03-12T22:22:47.011Z\",\"2504\":\"2019-04-26T14:47:22.000Z\",\"2548\":\"2019-06-07T15:23:34.428Z\",\"2553\":\"2019-05-14T19:52:35.000Z\",\"2591\":\"2019-06-10T19:29:44.428Z\",\"2609\":\"2019-06-12T16:41:52.014Z\"},\"vnamsg\":true,\"has-viewed-two-step-intro\":{\"taskId\":\"380947\"},\"has-viewed-personalized-intro\":{\"taskId\":\"381254\"}}}"```

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Teacher01 on QA was the only account having this issue. I will keep an eye for it in the future but this is fixed. Will close after this is live.
