### ISSUE TITLE
APUSH: Enlarged letter style in Lessons and Essay Activities

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#551]
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/book/88

Is it possible to remove the enlarged opening letter style in Lessons and Essay Activities? If so please remove per BRI feedback. 

![enlarged letter style](https://user-images.githubusercontent.com/19212926/63280707-4e2e4f80-c279-11e9-8707-2f0cea5d7761.JPG)

**Comment by carlycurran** [comment]
@dkhowala, when you get some time, can you help me out with this? Not sure why we have the enlarged letter, but it is in all books

**Comment by dkhowala** [comment]
@carlycurran Sure.

**Comment by carlycurran** [comment]
@mwest-WWprod 

The first paragraph in a new section starts with the big alphabet. If we have a heading class, the word "objectives" will not start with a big "O" (the same way that "Introduction" does not start with a big I)

![Screen Shot 2019-09-03 at 11.47.24 AM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/1d6a7537-9762-4571-bbc1-78601deefa1c)

**Comment by mwest-WWprod** [comment]
@carlycurran @lwtchu  CC @openstaxalina 

We are seeing this occur mid-module, so it may be a case where there is another rule governing the enlarged letter occurrence. See below in component 2.26.

https://tutor-content.openstax.org/book/88/page/93270

![EnlargedLetter_APUSH](https://user-images.githubusercontent.com/19212926/65541978-4c8d2280-dedc-11e9-9141-8fc09b81e57f.png)

**Comment by openstaxalina** [comment]
This module has the source markup from Matt's screenshot above. 
 There is a good amount of content above the enlarged letter: https://content05.cnx.org/contents/CmIfJ6vh@35.2:v8m0wvu6@4/2-26-%E2%9C%92%EF%B8%8F-Maps-Showing-the-Evolution-of-Settlement-1624-1755

"Vocabulary" is in a paragraph and bolding applied:
![Screen Shot 2019-09-24 at 2 08 01 PM](https://user-images.githubusercontent.com/7863733/65542409-bdc8d780-ded4-11e9-9011-b929e8f1a25b.png)

@carlycurran if this is a markup fix, could you confirm with the team what markup is needed to avoid the enlarged letter?

**Comment by oscryan** [comment]
This is the first uncontained paragraph in the module. Instead of using any of the header options, this word has the markup <para id="fs-idm414561600">
<emphasis effect="bold"><emphasis effect="italics">Vocabulary</emphasis></emphasis>
</para> which is just a bold and italicized paragraph orphaned outside any container, so the tutor format appropriate to the first paragraph is applied to it. If it were contained in a section or if it were the title of a section that contained the following material, this drop cap would not appear.

**Comment by lwtchu** [comment]
Content work around: Enclose the paragraph within a `<section>` (without a title).

Communicated that the first lone paragraph (paragraph without any nesting) will get drop cap treatment. If we do not want the drop cap treatment it will have to be nested in something.
