### ISSUE TITLE
CNX Module Not Saving on Exercises

### ISSUE THREAD

**Issue by marcjeannott** [openstax/tutor#552]
### Description
I've noticed that if I _add_ a CNX module ID to an exercise, when I save and publish it the CNX Module does not display. Even after a hard refresh. When I edit the exercise again I can see that another CNX Module was attempted to be added, but instead of the number it's just the default #####-### etc. I definitely know the UUID is not being pulled because it's still not appearing in the tutor question library. 

**To Reproduce**
Steps to reproduce the behavior are
1. Go to exercises.openstax.org
2. Click on Edit on an exercise, click Tags
3. Scroll down to CNX Module ID, add one then save and publish
4. See that it doesn't show up

**Expected behavior**
It should have the new CNX Module ID

**Screenshots**

**Additional context**
I discovered this while testing on exercises qa server, but I also confirmed the bug on production. 
### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Dantemss** [comment]
Cannot reproduce the bug for some reason.

**Comment by lwtchu** [comment]
I think it's fixed. Going to close.
