### ISSUE TITLE
APUSH: Question Library navigation bug

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#553]
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/course/88/questions

Navigating in 'Question Details', and then adding sections, automatically returns viewer to first question of first component with tutorized questions (Chapter Intro Essay).

It's difficult to provide screenshots for this issue - I will see if I can provide a video walking through and update this issue to include this as an example.

**Comment by mwest-WWprod** [comment]
@carlycurran This is marked as resolved on our tracker, but I didn't see any resolution here. Can you confirm?

**Comment by carlycurran** [comment]
@mwest-WWprod odd- maybe I accidentally marked it? This is definitely not resolved :)

**Comment by Brooke-Fail** [comment]
I you click the left or right arrow to navigate, there is a temporary page error.

https://drive.google.com/file/d/1YZETPHDwgFd2hcV-3R03nxKF_NHneCEd/view?usp=sharing

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.
