### ISSUE TITLE
APUSH: Question Library art appearing in 'cards', students will need to view full size

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#558]
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/course/88/questions

In Question Library, Homework questions have art that students will need to view at full size, or zoom in on if possible (in order to be able to answer the questions). As of now we can only view these in 'cards' and we're unable to zoom in or view full size (full page) as needed.

![HW question](https://user-images.githubusercontent.com/19212926/63368505-10e6c200-c34c-11e9-806b-92e66fdfc2e9.JPG)

**Comment by carlycurran** [comment]
The Question Library is a place where teachers can look through questions and decide what they want to assign, exclude, etc. 

So this view is essentially a better version of a thumbnail. It's not how students will see the art. They will see it either in a reading assignment or a HW assignment, attached to a question. 

If you want to see the art as a student would see it,  you can create an assignment with an art-based question and go to student preview.

**Comment by mwest-WWprod** [comment]
Thank you! This is helpful, I will add this note to our issue tracker and confirm that all looks good in student view. Once confirmed I'll close this.

**Comment by carlycurran** [comment]
cool - thanks, Matt!!

**Comment by mwest-WWprod** [comment]
Closing this issue, we have opened a separate issue based on our review of the student view (reading and HW assignments) and the art requirements and current display. Please refer to issue #585.
