### ISSUE TITLE
BUG: When assignment is due on current day but not open (time), there is no indication the assignment isn't open yet

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#559]
### Description
On the instructor dash, when assignment is due on current day but not open (time), there is no indication the assignment isn't open yet

![Screen Shot 2019-08-20 at 3.52.36 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/28680fd5-f6a1-4345-8809-e1ca11bb8f20)
![Screen Shot 2019-08-20 at 3.52.45 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/04c2c1fb-de29-4aa3-9d8b-48d6c4e58656)

### Acceptance Criteria
An assignment (on the instructor dash/calendar) does not appear open until the date and time it opens. 

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
