### ISSUE TITLE
Baked books - Impacts on figures

### ISSUE THREAD

**Issue by lwtchu** [openstax/tutor#56]
![Screen Shot 2018-10-11 at 1.37.12 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/b65aa6cd-e99d-41ce-9dc8-5d1211be243b)![Screen Shot 2018-10-11 at 1.37.32 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/08f65331-a64a-4333-bb54-6180c3894f6e)

- Figures are now numbered (yay? I thought we didn't like it to be numbered in the tutor. However..we no longer have "See Figure" as a anchor text)
- Figure captions and numbering does not have right formatting

**Comment by carlycurran** [comment]
I think figure caption is supposed to be italicized. The figure links in the text are also missing. (See blank between parenthesis in screenshot)
![Screen Shot 2018-11-27 at 2.28.17 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/97498e8e-b470-4a7e-a981-1a392d36c9cc)

**Comment by carlycurran** [comment]
Looks like formatting is updated, but we still have an issue with Anchor text and figure # that shows up there vs Figure number in the actual content

**Comment by nathanstitt** [comment]
these seem to be linked and working correctly now, probably fixed by some earlier change

**Comment by Malar-Natarajan** [comment]
The popup figures now are not displaying the figure number and description which is fine for this release as per Carly.

**Comment by nathanstitt** [comment]
fixed by https://github.com/openstax/tutor-js/pull/2456

**Comment by gregfitch** [comment]
Verified on QA
