### ISSUE TITLE
CHANGE: The number of questions in a HW assignment appears off to the instructor due to MPQs not being counted

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#561]
### Description
As an instructor, I want to see how many questions I am assigning my students, so that I can assign enough homework, know how much homework I am assigning, and not worry that something is wrong with the software.

Currently, in the homework builder, we show a multipart question as one question in an assignment, when it's really two, or even three. 
![Screen Shot 2019-10-03 at 1.55.02 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/17c10751-acea-4830-a04e-36344fdc1259)

### Acceptance Criteria
- In the homework builder, under the problem question table, each individual question is shown. In the screenshot above, there would be 6 teacher-selected questions and 3 Tutor-selected questions. Question 2 would be "What is the author of this letter ..." 

- The light blue header bar would reflect the number of questions referring to the same excerpt, so in the example case: 1-3. 

![Screen Shot 2019-10-03 at 1.55.02 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/eedc6db8-2e5b-4705-afac-d5d0c7b55470)

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by carlycurran** [comment]
will be dealt with in APUSH card that reflects same request

**Comment by nathanstitt** [comment]
@carlycurran I don't recall what you meant by:
> will be dealt with in APUSH card that reflects same request

I don't see a card about this, is there one?

**Comment by carlycurran** [comment]
oof - sorry, I was planning to use another card for this work, but then we scratched that card and I used this one. my bad 🙄

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
