### ISSUE TITLE
Baked Books - Orphaned equation numbering

### ISSUE THREAD

**Issue by lwtchu** [openstax/tutor#57]
![Screen Shot 2018-10-11 at 1.39.51 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/be191ba9-d68d-457c-8ff9-66113a2767b7)

Number for equation is orphaned

**Comment by nathanstitt** [comment]
I'm not sure what we should do with this, the 1.9 and 1.10 there is tagged as an "os-equation-number", but the number comes after the equation.  Should we hide them?

**Comment by nathanstitt** [comment]
yeah I think we can do that

**Comment by carlycurran** [comment]
Numbers are still looking like little orphan annie:
![Screen Shot 2018-11-27 at 2.06.43 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/7dabd083-fbe3-4c3b-b592-47750e3b8cc7)

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2449
