### ISSUE TITLE
Change Request: Improve LMS error messages

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor#571]
### Description
As a teacher/student I want better LMS error messages so that I know what the heck is going on.

### Acceptance Criteria
LMS error messages actually somewhat describe the error being encountered. In particular we need to address these errors:
- Reusing a nonce (for example: "your LMS system made a duplicate launch request...")
- Launch data not found (for example: "either your browser is clearing cookies (are you in an incognito window?) or the launch URL configured in the LMS is incorrect")
- Course has ended - this is currently not an error but causes user confusion.

### Acceptance Tests
**title**: LMS nonce error
**categories**: Errors
> GIVEN a Tutor course with LMS integration
> WHEN I launch Tutor via the LMS, record the url and attempt to launch it again  
> THEN I get the nonce error message we decided above

**title**: LMS cookie error
**categories**: Errors
> GIVEN tutor
> WHEN I visit tutor.openstax.org/lms/launch_authenticate or tutor.openstax.org/lms/complete_launch directly  
> THEN I get the cookie error message we decided above

**title**: LMS course ended error
**categories**: Errors
> GIVEN a Tutor course with LMS integration that already ended
> WHEN I launch Tutor via the LMS
> THEN I get the course ended error message we decided above

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [x] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [x] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
