### ISSUE TITLE
Teachers will get the new course tour again when creating their second course 

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#573]
### Description
If a new teacher creates a course, they are given a tour with some tool tips. Once they have got through all the tool tips, if they create another course, the new course tour will trigger again.

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor a new instructor
2. Create a course
3. Go into the course and complete the tour, select next on all the training wheels
4. Once the tour has completed, create another course
5. Go into the second course
6. Notice that the tour is triggered again eve after the instructor has already completed it

**Expected behavior**
The tour for a new course is only given once. 
New course tour should have 8 steps. 
New course tour comes AFTER terms and conditions and after welcome modal. 
Enrollment link tour should come up after terms, welcome and course tour. It should come up once for every new course.
No onboarding prompts for instructors should happen.  

**Screenshots**
Video:
https://drive.google.com/file/d/1eI30zGBdVIEvaIws3zGI8WiptirNE71e/view?usp=sharing

**Additional context**
Even after going through the tour twice, going into a preview course for the first time will also trigger the tour again. I am not sure if this is intended because it's a preview course, or if the tour should only be triggered once, either in a preview course or in a new one.

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
This can also be triggered if you have 1 course and go into it again.
The first tour given when a new course is created has 5 steps. The second tour has 8 steps. Preview courses have 9 steps. 

Video:
https://drive.google.com/file/d/1hmWI6bRk7AqUQONn9Q2xCuUnzjmnpjUA/view?usp=sharing

**Comment by nathanstitt** [comment]
This should no longer occur after the tour rework. I think we just didn't get this tagged

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production
