### ISSUE TITLE
ToU/Privacy pane shows up between the pay for course pane and Payments form for new students

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#576]
### Description
Description

For new students registering for a course, the Terms pane shows up after the student clicks the 'Buy access now' button and before the Payments pane is displayed. The Terms pane used to show up before the Buy Access/Trial pane.

https://slack-files.com/T0F5B5PGQ-FMS898KEK-1585bdd8dc

**Expected behavior**
Enrollment flow follows this path: https://openstax.secure.force.com/help/articles/FAQ/Student-enrollment?search=tutor%20enroll
1. "Welcome to OpenStax Tutor Beta" modal (per, Dante, this is coming from the back end)
2. Sign up or login 
3. If signing up, enter PIN 
4. Create password
5. Create account (name, school, etc)
6. Terms & Conditions
7. Student ID option
8. Buy access or free trial
9. If click trial - Free trial activated; if click pay - payment window
10. Welcome to OpenStax Tutor Beta modal (white background with Tutor info) 

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
The order is now correct in QA and the Terms show before the payment screen and after the student creates an account. However, there is a small issue where a gray screen is briefly displayed after the terms are accepted. This issue is being tracked here:
https://github.com/openstax/tutor/issues/589. Moving card to regression.

**Comment by Brooke-Fail** [comment]
Verified in Staging.
