### ISSUE TITLE
Wrong content displayed when you select "all past work" tab as a student and reload

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor#578]
### Description
When you select the "all past work" tab as a student and then reload, the tab stays selected but the content from "this week" displays instead.

**To Reproduce**
Steps to reproduce the behavior are
1. Login as a student
2. Enter a course
3. Select "all past work"
4. Reload
5. "all past work" is still selected but content from "this week" is displayed

**Expected behavior**
Either reset the selected tab or display the correct content.!

**Screenshots**
[Screen Shot 2019-08-27 at 3.29.12 PM.png](https://images.zenhubusercontent.com/5b05e41c4b5806bc2bd463b7/93415db0-62f5-4996-af4c-de1a2d9dc8f4)

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Video:
https://drive.google.com/file/d/1Cf3RrFvfZBMwJI1Q5bQWbtpn-XpAl3yh/view?usp=sharing

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
