### ISSUE TITLE
Baked Books - examples missing styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/tutor#58]
![Screen Shot 2018-10-11 at 2.29.30 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/2de10114-d091-4f5f-aa65-ba549de4fdab)

**Comment by carlycurran** [comment]
Examples aren't currently styled in Tutor reference view it looks like: 
![Screen Shot 2018-11-27 at 2.38.44 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/64dd2212-ab6e-4895-bcb5-a12105f7e808)

But they are on CNX:
![Screen Shot 2018-11-27 at 2.38.02 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/450578c3-418b-4486-b002-4d781d66bdfb)

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2449

**Comment by Malar-Natarajan** [comment]
Verified in Staging

**Comment by Malar-Natarajan** [comment]
The issue was with the equation numbers styling in this card
