### ISSUE TITLE
style teacher as student viewing non-open assignment bar

### ISSUE THREAD

**Issue by nathanstitt** [openstax/tutor#580]
update style for the little "only visible to instructors" banner to meet @dkhowala 's stylings.

this card was split from https://github.com/openstax/tutor/issues/492

it currently uses 12pt font and looks like:

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/55399aa4-edad-49eb-a73a-815a98aa34bc)

**Comment by dkhowala** [comment]
@nathanstitt 

Styling-wise, it looks good to go.

It should be inside the assignment row, not on top of it. 
And the date should be: Aug 28, 3:11pm to match the date format in the due column

![Screen Shot 2019-08-29 at 10.56.45 AM.png](https://images.zenhubusercontent.com/5c12c502ea8fd844ba2fce8c/aef749bf-ffb0-48c0-aabc-bbac9d7920c3)

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
