### ISSUE TITLE
APUSH: Art sizing in student view (HW/Reading Assignments)

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#585]
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/course/88/task/6982/step/1

In student-facing homework/reading assignments, art appears similarly to Teacher View. The students will need to either view the art at full size (art takes up full width of page, not contained in a 'card' view as is seen currently), or they will need to be able to zoom in on the art. Questions will in many cases require analysis by the student user. Below example is shown in student and teacher view for reference.

Student View
![student view_HW Art](https://user-images.githubusercontent.com/19212926/64196921-dfddb580-ce52-11e9-95e0-f442a751e4a4.png)

Teacher View
![teacher view_HW Art](https://user-images.githubusercontent.com/19212926/64196912-db190180-ce52-11e9-8f95-1ac1c7d505ad.png)

See issue #558 for original ticket, prior to student view being available.

**Comment by carlycurran** [comment]
Decided that we will not make changes to art sizing in question views. The art is sized as large as possible, and students can use browser to zoom. (In the case they do zoom, some of these images will become pixelated, FYI.) 

cc @openstaxalina I'm closing this card.
