### ISSUE TITLE
BUG: Problems when trying to highlight two sentences in the same paragraph

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#586]
### Description
A student reported "a glitch I found in the highlighting for OpenStax. The system sometimes didn't let me highlight certain passages.

For example, after I highlighted a sentence in a paragraph, I would try to highlight another sentence in the paragraph. Unfortunately, after I highlighted the second sentence and clicked the highlight button, the sentence wouldn't be highlighted. 

Another example would be that I would highlight a sentence and then the program would suddenly highlight the whole paragraph or something different." 

### Acceptance Criteria
- Two sentences in the same paragraph can be highlighted
- Highlighting two sentences in the same paragraph does not force the entire paragraph to be highlighted, if the paragraph is more than two sentences long. 

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by nathanstitt** [comment]
There's nothing immediately obvious stopping highlighting multiple times in a paragraph.  I suspect this is either:
* highlights cannot overlap.  However in that case we show a notice at the bottom left
* some content can't be highlighted, maybe the 2nd fell into that area.  

Unfortunately we'll need to know the URL and para that can't be highlighted to debug further.  my test case worked fine

![image](https://user-images.githubusercontent.com/79566/64269996-73b98b00-cf00-11e9-8257-70c6b30cf137.png)

**Comment by carlycurran** [comment]
Thanks, @nathanstitt! @Brooke-Fail, FYI - I'm also not having this problem. I'm going to close this card, but will you flag me if you see something like this pop up?
