### ISSUE TITLE
Unable to view or edit study brains code

### ISSUE THREAD

**Issue by nathanstitt** [openstax/tutor#588]
### Description
As a tester or researcher I should be able to view and edit the source code for a study brain

### Acceptance Criteria
Give criteria for acceptance.

No error is encountered when viewing or editing the source code for a study brain

**Comment by Brooke-Fail** [comment]
I can edit and view study brains in QA. Will start testing them ASAP.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
