### ISSUE TITLE
Blank student dashboard (gray screen) is displayed after a new student accepts the terms

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#589]
### Description
After a new student agrees to the terms, there is a brief gray screen that displays after the terms are accepted. The screen looks like it is a blank student dashboard, but it goes away fairly quickly and the student is able to progress.

**To Reproduce**
Steps to reproduce the behavior are
1. With a course enrollment link, create a new student account in tutor
2. Go through the log in and pin process until you get to the terms
3. Accept the terms
4. Notice that there is a gray screen that displays briefly after the terms are accepted

**Expected behavior**
There is no gray screen displayed after terms are accepted. 

**Screenshots**
Video:
https://drive.google.com/file/d/1_vRsgUoisctj34g6_7YCGCPcYZsoi_Ne/view?usp=sharing

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Dantemss** [comment]
Cannot reproduce. I'm guessing Nathan's tour rewrite fixed this.

**Comment by nathanstitt** [comment]
You know I didn't even think of that but yes the tours might have been the culprit here.  🤞

**Comment by Brooke-Fail** [comment]
This looks to be fixed in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
