### ISSUE TITLE
Baked books - EOC Sections completely broken !!!

### ISSUE THREAD

**Issue by lwtchu** [openstax/tutor#59]
I'm assuming cause these are supposed to be suppressed and served up separately during the reading E X PE R I EN C E ~~

![Screen Shot 2018-10-11 at 2.32.37 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/0f0af447-ddbf-4641-8193-1c9448e53201)

# In viewing the book 
Screen hangs up when going to EOC sections
It sits like this forever and freezes the page when you try to go to the EOC sections like the Glossary or Section Summary

# Adding a reading
I think this happens regardless of what sections I choose - might be because part of the questions are split between the EOC and the module??? So the exercises are confused? IDK.

![Screen Shot 2018-10-11 at 2.43.16 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/fb1be3b2-b948-4971-b7b6-28d728760c76)
Error: `{"type":"reading","settings":{"page_ids":["76061","76062","76063","76064","76065","76066","76067","76068","76069"]},"tasking_plans":[{"target_type":"period","target_id":"115","opens_at":"2018-10-11 00:01","due_at":"2018-10-26 07:00"}],"title":"Chapter 1","is_publish_requested":true}`

**Comment by carlycurran** [comment]
Is there supposed to be a glossary or summary section EOC in Tutor?

**Comment by Dantemss** [comment]
Fixed in https://github.com/openstax/tutor-server/pull/1816

**Comment by lwtchu** [comment]
@carlycurran if the book has em then yes

**Comment by carlycurran** [comment]
Yup -- we got em in there now!
