### ISSUE TITLE
CHANGE: Update the way we manage withdrawn assignments

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#591]
### Description
As a student, I don't want to know about a withdrawn assignment unless I have done work in it, because it crowds my dashboard.

### Acceptance Criteria
- If a teacher has deleted an assignment, it does not show up on a student's dashboard (as withdrawn) UNLESS that student has done work in the assignment. 
- If a student has opened the assignment and completed a task step, the student gets the withdrawn notice that currently exists with an X. 
- If a student clicks the X to delete a withdrawn assignment, the student gets the notifcation message that we currently have and is taken back to the student dash (does not see error page)

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by Brooke-Fail** [comment]
An error is given if a student is in the middle of an assignment that has been withdrawn. 
<img width="1214" alt="Screen Shot 2019-09-18 at 4 15 33 PM" src="https://user-images.githubusercontent.com/48449285/65186647-ababec80-da2f-11e9-8e93-8d5f450ec324.png">

after clicking Ok they are brought to the course dashboard and when the student goes back into the course, it shows the assignment as withdrawn.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
I got the 403 error again on safari when an assignment was deleted when I was  i nthe missdle of answering a question.

https://tutor-staging.openstax.org/course/5762/task/2007815/step/3
 bf22+18@rice.edu

**Comment by Brooke-Fail** [comment]
Verified in Production.
