### ISSUE TITLE
Fetching assignments wheel will briefly display even if all assignments are already loaded 

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#595]
### Description
If a student clicks on a course, they will briefly see the "fetching assignments" wheel display even thoguht al lthe assignments for that course are already being displayed. 

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor as a student
2. Click on a course with assignments
3. Wait for all assignments to load
4. Go back to the course dashboard
5. Click on the same course you did in step 2
6. Notice that the fetching assignments wheel briefly displays 

**Expected behavior**
There is no loading wheel for assignment if they have already been loaded. 

**Screenshots**
Video:
https://drive.google.com/file/d/1eNDosPVzyCP6At_KSXl3aiTWwi7Oexxg/view?usp=sharing

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
Nathan - need to re-fetch and get updates.

**Comment by carlycurran** [comment]
Can say "Update assignments" instead of "Fetching" - Carly to ask @dkhowala

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
