### ISSUE TITLE
Bug: Investigate "map of undefined" error 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#596]
### Description
Sentry error here: 
https://sentry.cnx.org/openstax/tutor/issues/6029/

Has happened at least 3 times in the past week

### Acceptance Criteria
Give criteria for acceptance.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by Brooke-Fail** [comment]
There is no way I can verify this. We will have to see if we get this error when we go live.

**Comment by Brooke-Fail** [comment]
The user can scroll through the mpq correctly, even with the breadcrumb navigations, but sometime the question will load then scroll to the second question instead of the first.

**Comment by Brooke-Fail** [comment]
Seems like a new student still gets the scroll down issue for MPQ.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
