### ISSUE TITLE
Baked book - blue bar now sits about 3-8px above the feature box

### ISSUE THREAD

**Issue by lwtchu** [openstax/tutor#60]
![Screen Shot 2018-10-11 at 2.34.02 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/4930efc5-201c-44db-b408-89878faeddf6)

Is this new? Or just an existing problem?

**Comment by carlycurran** [comment]
Still seeing some issues with blue bar and box spacing/padding:

![Screen Shot 2018-11-27 at 2.40.43 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/952f5472-dbd3-448c-9582-7e0ebb98ec5d)

![Screen Shot 2018-11-27 at 2.41.10 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/907d3593-77ed-4e86-a35f-56683a5ae4fd)

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2449
