### ISSUE TITLE
Recent Topics includes unopened assignments

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#600]
### Description
Description

The recent topics section of the sidebar performance forecast (student dashboard) uses the last assignments created by the teacher even if the assignments aren't open to student work (ie the instructor creates assignment ahead of time).

All assignments are created but open on different days
![Screen Shot 2019-09-12 at 10.51.32 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/c8ba98f4-f159-4f93-838f-fec07ded1cf1)

Open assignments are on the student dashboard, but the recent topics shows sections from the final, unopened assignment (ch. 47)
![Screen Shot 2019-09-12 at 10.51.40 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/7a2b370f-2cbc-477b-abc4-c258166e26e9)

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

Recent topics includes the most recent, open book sections

**Screenshots**

**Additional context**

### Acceptance Tests
- When a new student with no assignments logs into Tutor, she will see the explanation of the PF.
- When a new student with already created assignments (but not worked) logs into Tutor for the FIRST time, she will see the explanation of the PF. 
- When a new student with already-created assignments (but not worked) logs into Tutor for the FIRST time and then navigates away from the dash and goes back to the dash, she will see the explanation fo the PF UNTIL she has completed a task step. 
- In other words, no PF shows up and the student sees the explanation until he/she has completed a task step. (Justification - we want students to know that the assignments are where graded work happens, not the PF/practice widget) 
- When a student has completed at least one exercise task step in a section, the PF dashboard "recent topics" will appear for that section.
- We will show the four most recently worked sections in the "recent topics" area. Most recently worked = at least one exercise step completed. 
- If you've only worked problems in one section,  you only see one section in your "recent topics" area.
- 

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
@gregfitch can you provide the login and url to the dashboard shown?

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
