### ISSUE TITLE
APUSH: Multi-part assessments not numbered correctly in Reference View

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#601]
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/course/88

Multi-part assessments are assigned a single assessment number in the Student/Teacher Reference View. This will mismatch the Instructor Answer Guide ancillary in which each part is individually numbered. Each separate question under the stimuli (stimuli not shown here, see #602 ). Let us know if this is a markup issue and we will account for it.

For reference, see our manuscript (which our XML team uses to tag content)
![multi-part_assessments_APUSH MS](https://user-images.githubusercontent.com/19212926/64975251-86c34800-d87c-11e9-8cb8-4f138f4ea3d4.JPG)

Reference View Output
![multi-part_assessments_APUSH](https://user-images.githubusercontent.com/19212926/64975584-5def8280-d87d-11e9-9a50-d6ddbc6e4c67.png)

**Comment by carlycurran** [comment]
@mwest-WWprod 

This is definitely an issue in Tutor. For now, this is how Tutor works -- a multi-part question is counted as one question. For a few reasons, I am planning to do some work in Q4 to change this. If we have this ready in Jan, will that work for you?

cc @openstaxalina

**Comment by mwest-WWprod** [comment]
@carlycurran Thanks for the context, we'll confer on this, we may need to find a short-term workaround for an upcoming pilot, I'll add this to our discussion items for our working session on 9/26.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/webview #2278](https://github.com/openstax/webview/issues/2278) via [**ZenHub**](https://www.zenhub.com/)
