### ISSUE TITLE
APUSH: AP Practice Questions stimuli not appearing in Reference View

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#602]
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/course/88

Stimuli are not appearing in AP Practice Questions in Student/Teacher Reference View. See below example in Chapter 2 Chapter Intro Essay (2.2). Our manuscript input is provided for reference. Note that the stimuli does appear in the Question Library.

Reference View
![multi-part_assessments_APUSH](https://user-images.githubusercontent.com/19212926/64976820-3817ad00-d880-11e9-9f26-cee4a0e1e5df.png)

Manuscript
![multi-part_assessments_APUSH MS](https://user-images.githubusercontent.com/19212926/64976848-45cd3280-d880-11e9-84cc-e110a2ed0ffc.JPG)

**Comment by openstaxalina** [comment]
Issue moved to [openstax/webview #2274](https://github.com/openstax/webview/issues/2274) via [**ZenHub**](https://www.zenhub.com/)
