### ISSUE TITLE
APUSH: Block quotation design

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#604]
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/course/88

Block quotation design does not make clear that content is cited/quoted material. It is important to instructors that students of this course see and learn how to correctly cite material and this current design does comport with that objective. If users minimize or turn-off styling displays, there is additional concern that it is not clear that the material is cited/quoted. Per CMS 13.9, block quotations in design should be “distinguished from the surrounding text by being indented (from the left and sometimes from the right) or set in a smaller type or a different font from the text. These matters are normally decided by the publisher’s designer.” 

Could block quotation design be made more dynamic/contrasted to surrounding content? This could be done with darker shading, shrinking margins of block quotation content etc.

![block quote_APUSH](https://user-images.githubusercontent.com/19212926/64993877-27c5f900-d8a5-11e9-81dc-385f0a2fa591.png)

**Comment by nathanstitt** [comment]
@carlycurran when I investigated this I discovered we actually had style rules to accomplish this but they were inactive.  When I restored them I discovered that the left border uses the "book color" so it's themed like the headings and other elements are.  Is that desired, or should the left line be grey like CNX?

If we use the book colors APUSH will be dark blue like this:
![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/0c2757ca-ba7c-4af2-af64-56bc10fd1f40)

**Comment by carlycurran** [comment]
@nathanstitt I like the theme color. Let's go with this!

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
There is no margin between the text and the block bar.

<img width="1184" alt="Screen Shot 2019-10-04 at 4 06 26 PM" src="https://user-images.githubusercontent.com/48449285/66241823-8a046380-e6c5-11e9-9027-b9883e19fcfb.png">

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
