### ISSUE TITLE
APUSH: Component title hanging indents (for long titles)

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#605]
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/course/88

Component titles in the header should have some kind of hanging wrap instead of being flush left when they fall to a second line. It is potentially confusing, especially when numbers jumble together. Many component titles across the book will be long and will include numbers.

![component titles_APUSH](https://user-images.githubusercontent.com/19212926/64994209-03b6e780-d8a6-11e9-8434-2ec44a2af983.png)

**Comment by carlycurran** [comment]
@mwest-WWprod does this work?
![image (2).png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/7fb43d74-eed4-461b-a133-34917218481f)

**Comment by mwest-WWprod** [comment]
@carlycurran that's perfect!

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
