### ISSUE TITLE
APUSH: Scaled-down classes not applied in Student Reading Assignments

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#611]
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/course/88/task/6982/step/1

New scaled-down classes have been applied, and output does look correct in reference view. However, when we create a student reading assignment with the content, the art size reverts to what it was previously.

Reference View
![art size_reference view_APUSH](https://user-images.githubusercontent.com/19212926/65352592-04f35780-dbb9-11e9-9084-c936e37151cb.png)

Student Reading Assignment
![art size_student view_APUSH](https://user-images.githubusercontent.com/19212926/65352603-07ee4800-dbb9-11e9-936a-55a24f4af904.png)

**Comment by carlycurran** [comment]
@mwest-WWprod I'm not sure what the user requirement here is. I thought we'd previously discussed that the art in student view wasn't large enough?

**Comment by mwest-WWprod** [comment]
@carlycurran Yes, that is the case - to confirm: we have applied the pertinent scaled-down and full-width classes to the art. As seen in the above example, a figure tagged with the full-width class, the art appears as it should (full width) in the reference view, but the same figure, when viewed in a student reading assignment, is smaller. In the student reading assignment, it should appear full width as it does in the reference view - let me know if that clarifies, I'm happy to slack other examples or jump on a quick call.

**Comment by openstaxalina** [comment]
@carlycurran these were the cards where I requested the classes dictate art sizing; it seems like this was applied only in Reference View but should also be in reading assignments?
https://github.com/openstax/tutor/issues/409
https://github.com/openstax/tutor/issues/434

(Feel free to edit or delete this comment if not helpful!)

**Comment by nathanstitt** [comment]
I think that perhaps the code on the content server wasn't yet updated when this card was opened.  I see the scaled classes applied correctly both in reference view and reading steps.  for instance currently the test url (https://tutor-content.openstax.org/course/88/task/6982/step/14) has the image scaled to 60% as it should:

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/3e032542-30ac-4570-bbd6-6bf1b40593a5)

**Comment by carlycurran** [comment]
Great! Thanks @nathanstitt. 

@mwest-WWprod can you check this again with updated content? Looks like the art size class is applied in reading assignments.

**Comment by Brooke-Fail** [comment]
Looks good when tested in production.
