### ISSUE TITLE
Student received 403 error when the assignment is deleted and they are in the middle of a free response question 

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#612]
### Description
Student is given a 403 error if they are in the middle of a free response question on an assignment and the assignment has been deleted by the teacher in the process.

**To Reproduce**
Steps to reproduce the behavior are
1. Log onto tutor as a student
2. Start an assignment and get a free response question ready
3. In another browser, log into tutor as an instructor
4. Go to the course and assignment the student is working in and delete the assignment
5. As the student, continue with the free response question
6. Notice there is a 403 error when the assignment is deleted and the free response question is submitted 

**Expected behavior**
There is no error when an assignment is deleted for the teacher or student. 

**Screenshots**
![Screen Shot 2019-09-18 at 4.15.33 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/2355d705-b207-4f5a-abf0-a97e29ac3d0a)

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by carlycurran** [comment]
BE doesn't allow recording the response in a deleted assignment. This release will hide the 403. On task steps we should not be displaying the error modal; they should display in a card.

**Comment by nathanstitt** [comment]
I've made a fix to hide the "server error" modal.  errors in task steps should only appear in the cards

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
