### ISSUE TITLE
APUSH: Navigation in Teacher interface of QL is broken

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#613]
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/course/88/questions

Arrows/navigation in the teacher view of Question Library do not function (at least on our machines).

![APUSH_QL Navigation](https://user-images.githubusercontent.com/19212926/65535604-c4a11b80-decf-11e9-868e-96bef58f4c9b.JPG)

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
