### ISSUE TITLE
APUSH: Appendix (Glossary) needed at end of book

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#619]
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/book/88

We will need an appendix (Glossary) at the end of the book. In our discussions, this has been listed as a long-term fix.

**Comment by carlycurran** [comment]
@openstaxalina -- same question as the preface card :) 
Can we close now that WW has approved our preface and appendix placement?

**Comment by openstaxalina** [comment]
Yes - closing.

Per discussion here, the "17.1", "17.2", etc. treatment in an "Appendices" chapter will work.
