### ISSUE TITLE
Baked Book - Table impact

### ISSUE THREAD

**Issue by lwtchu** [openstax/tutor#62]
![Screen Shot 2018-10-11 at 3.17.28 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/998af2e2-186d-4172-ab35-069b93d8e66e)
![Screen Shot 2018-10-11 at 3.18.24 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/879426a7-37bb-4938-8069-b94ee4685085)

- Headers don't really look like headers? Might be non-issue but in some cases it looks detached from the table especially if there's a note before the table.
- I don't think the table caption and numbering is styled.

**Comment by nathanstitt** [comment]
yes the tables could use some work, but the headers appear the same in non-baked content.  I fixed the caption tho

**Comment by carlycurran** [comment]
Seeing some table problems. I think this has to do with the units/exponents? 

![Screen Shot 2018-11-27 at 2.46.30 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/c551db42-7639-41c2-a306-8db20dd2f9e4)

**Comment by nathanstitt** [comment]
that looks like math processing errors to me, can you attempt to reload and/or test in a different browser to see if it renders fine there?  We'll probably still need to fix it, but that'll give us a clue on what's breaking

**Comment by carlycurran** [comment]
Yes it was!! Reloaded on Chrome and no probs.

**Comment by nathanstitt** [comment]
should be working fine now, didn't see any in safari or chrome

**Comment by Malar-Natarajan** [comment]
The table heading still looks like a heading of the following paragraph. See screenshot from staging:


![Screen Shot 2018-12-14 at 11.00.16 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/00fe8799-82b3-43f9-bb54-2301a37275b8)

**Comment by nathanstitt** [comment]
bottom margin to table added in https://github.com/openstax/tutor-js/pull/2475

**Comment by gregfitch** [comment]
Verified on QA
