### ISSUE TITLE
Bug: biglearn-scheduler stops recalculating exercises for old ecosystems after an ecosystem update

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor#624]
### Description
Biglearn-scheduler stops recalculating exercises for old ecosystems after an ecosystem update, so assignments created in the old ecosystem will no longer receive LQC/SPARFA recommendation updates.

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Can not verify in production until there is an ecosystem import. Closing based on staging testing.
