### ISSUE TITLE
Extremely long assignment instructions can cause issues when editing an assignment or viewing in student view

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#626]
### Description
If the teacher has extremely long assignment details, when they go back to edit the details, the can not move the size of the text box back to it's smaller size. 
Another issue with extremely long assignment details is in student view. If you hover over the blue ! to view the details and try to scroll all the way down to see them, the screen will toggle all grey as long as you are hovering over the blue !. Otherwise, it will display the correct assignments for student view.

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor as an instructor
2. Create an assignment 
3. Insert an extremely long detail for the assignment (example: copy the full format of the description of this card and past it 3-5 times)
4. Save and view in student view
5. Hover over the blue ! and try to scroll down and view all of the assignment details
6. Notice that the user will get a grey screen when they try to toggle over the details now
7. Go back to teacher dashbaord
8. Try to edit the assignment with the details
9. ctrl+a to delete all the text in the assignment details box
10. Try to resize the details box to be smaller
11. Notice the box will not resize smaller until you save the assignment and edit again

**Expected behavior**
Text box can be resized and there is not grey screen when trying to view long assignment details. There can also be a character limit set to avoid the users running into this issue. Expected behavior TBD.

**Screenshots**
Video ( student view):
https://drive.google.com/file/d/1Vb42iQaFljiyvSftpy3ITkkxxz5tz9g4/view?usp=sharing

Video (edit details resize):
https://drive.google.com/file/d/1YaaCiLYsNqDbeIlrpQneqI3h-vfJhTKs/view?usp=sharing

**Additional context**
These issue only happen for teachers. I could not reproduce either of them for a student. 

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
I think we should limit the length of the description when it's entered.  A few questions arise though:
 * How long should we allow?  1,000 characters sounds good to me..
 * Should we show an error if it's longer and make them truncate, or should we just truncate and save it?  Seems unsafe for us to truncate, but maybe it's too much work for them to do it?

**Comment by carlycurran** [comment]
Let's limit to 250 characters and make the cursor stop when that limit is reached. So just disable typing after 250.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
