### ISSUE TITLE
APUSH: Embedded videos in Ch. 5 are broken

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#639]
Ch. 5 
Tutor APUSH
https://tutor-content.openstax.org/book/88/page/94351

Videos in Ch. 5 are broken, although we have tagged them as we normally do. Our team is investigating and may be able to resolve, but I am opening an issue for now for tracking purposes.

![BrokenVideo_5 11_APUSH](https://user-images.githubusercontent.com/19212926/66161196-be125280-e5f9-11e9-8255-86a8cfed5190.JPG)

![BrokenVideo_5 11_APUSH Markup](https://user-images.githubusercontent.com/19212926/66161276-ef8b1e00-e5f9-11e9-9654-adcc950b6acf.JPG)

**Comment by carlycurran** [comment]
@openstaxalina let me know if this is something we need to look into. I think vids are also broken on content server.

**Comment by openstaxalina** [comment]
@oscryan could you investigate this?  Here is a module where the video seems to work properly:
https://content05.cnx.org/contents/CmIfJ6vh@38.2:4_mJkwz1@22/1-2-%F0%9F%93%96-Chapter-1-Introductory-Essay-1491-1607

Here is a module with a broken video: https://content05.cnx.org/contents/CmIfJ6vh@38.2:il5M7Tst@2/5-11-%F0%9F%93%8D-Marbury-v-Madison

**Comment by oscryan** [comment]
the target link of the shortlink is a watch link (https://www.youtube.com/watch?v=Dbl2Lrle3VA) instead of an embed link (https://www.youtube.com/embed/Dbl2Lrle3VA).

**Comment by openstaxalina** [comment]
thank you @oscryan 

@mwest-WWprod if the team uses embed links, this should be resolved.  
There are instructions for acquiring embed links here: https://docs.google.com/document/d/1TNUSZ-SIYU2pruTOu5LmNpQWIGdgxonzhokT-WC-6Yc/edit#heading=h.bgrfwzkgm10n

I am closing this issue; please re-open if needed in the future.
