### ISSUE TITLE
Add Redis and celery-once to biglearn-sparfa-server and fix bulk API calls

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#66]

**Comment by Dantemss** [comment]
Linked PR: https://github.com/openstax/biglearn-sparfa-server/pull/51

**Comment by Dantemss** [comment]
Celery-once needs Redis so it's all happening in one PR. I'll combine this with the Redis issue.

**Comment by carlycurran** [comment]
SPARFA works for Dante locally, working with BL scheduler and BL API. Writing tests for it now.

**Comment by carlycurran** [comment]
Dante wants a test for every file (15) and every method in every file. 
Likely to finish by end of Oct.

**Comment by Dantemss** [comment]
Argh I accidentally unlinked the PR and can't link it again... PR is openstax/biglearn-sparfa-server#51
