### ISSUE TITLE
Fix the deployment script

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#68]
PR is not merge-able as-is. 
Solve the conflicts. (This will take the most time ~ 1 month.)

See if parts of Amanda's PR still apply
Add specific version of Python to deployment script
Add RabbitMQ - may be separate service or service running on same server; for scaling we want it separate

**Comment by Dantemss** [comment]
Linked PR: https://github.com/openstax/tutor-deployment/pull/334

**Comment by Dantemss** [comment]
Linked PR: https://github.com/openstax/tutor-deployment/pull/436

**Comment by carlycurran** [comment]
Dante is starting over with new PR 
Amanda's was too old

**Comment by carlycurran** [comment]
Going to download SPARFA algs in Bastion, package with the app and send to server.

**Comment by carlycurran** [comment]
R2 gave REDIS access to Dante's new server
