### ISSUE TITLE
Accessibility: Fix contrast issues with PhET SIM pages

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#7]
## Description
Fix contrast issues with PhET SIM pages. There is no continue button, and the next button fails contrast test.  

## Acceptance

User can locate and distinguish button that gets her to next page

**Comment by nathanstitt** [comment]
This seems to either be mistaken or perhaps I'm not viewing the content correct, but I see a "CONTINUE" button

![Screen Shot 2018-10-08 at 4.10.33 PM.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/3a102724-c73a-4171-a669-c5b570c43c1a)

**Comment by nathanstitt** [comment]
The continue button is the same as all our other buttons, so if we want it updated we should get input from UX on best color scheme.

**Comment by carlycurran** [comment]
might be talking about a SIM like this (in reading experience)![Screen Shot 2018-10-08 at 4.18.13 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/3907610f-b803-4aa7-802c-4edafb04b5b1)

**Comment by carlycurran** [comment]
@nathanstitt  
here's another
this is on tutor demo,
login as eliza_hamilton
physics course
https://tutor-demo.openstax.org/course/221/task/20148/step/9![Screen Shot 2018-10-15 at 1.11.26 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/00b11add-632a-4b3d-acfc-3bf27e5871f4)

**Comment by nathanstitt** [comment]
Thanks for pointing those out, it looks like the continue button is missing only when the video or sim appears all by itself.  I added it to those cases in https://github.com/openstax/tutor-js/pull/2406
