### ISSUE TITLE
Bug: Student practicing from PF in Tutor cannot get progress bars to green

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#72]
### Description

We go this feedback as a result of the APUSH pilot. A student was trying to get her progress bars to green, but no matter how many questions she got right (in her words), she could not. Is this a function of having too few questions?

----------------
**Steps to Reproduce the bug or Details about Change:** _What, Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ x] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [X ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**
Hopelessness and despair
----------------
**Images or Screenshots** (_attach below_)

**Comment by Malar-Natarajan** [comment]
Refer video: https://drive.google.com/file/d/17PKs8uXKfe5kzDWZ_erdvclWQSokhltD/view?usp=sharing
Tested in QA:
There is a time gap before attempting to improve the performance forecast for the same section. The Question Library for 5.2ch has 14 (12 HW+2 read) question. Everytime I answer one set of questions the green bar increases very little bit. So if I click again it gives me something like "try again, no questions available now". After couple of minutes if I try I get the next set of questions and the green bar progresses again very little bit.

**Comment by Malar-Natarajan** [comment]
Closing this card since we can see the green bar and creating new bug card for the issue noted here.
