### ISSUE TITLE
Page tips slightly wonky in Firefox

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#73]
_Instructions are in italics and can be deleted_
_1. Give the issue a descriptive title_
_2. Add a label: bug | change_
_3. Pick the content template:_

### Description
Page tips slightly wonky in Firefox

----------------
**Steps to Reproduce the bug or Details about Change:** 
Enroll a new instructor and view the page tips in firefox. The page tips in the menu are not properly highlighted. 
Also, the X button is not present in the tip box. So we cannot quit in between the tour
Refer video

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [X] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [X] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [X] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

https://drive.google.com/file/d/1dTrLkk7n6f1ywBkKuzUjPMyfbDkrrW3f/view?usp=sharing

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
Great News!  We've apparently waited long enough that it's been fixed!  (probably by the react upgrade)

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/6e00d2e6-0ff3-4f93-950f-33e4a9809a2e)

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/7f57467f-f18a-47c2-94d7-681a20734ecb)

**Comment by gregfitch** [comment]
![Screen Shot 2019-01-07 at 2.09.47 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/c1bbff19-1d99-426b-b2d4-4d8fae9eddf0)
![Screen Shot 2019-01-07 at 2.09.59 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/214df883-9bb8-41f6-89d1-b197c29206ff)
![Screen Shot 2019-01-07 at 2.10.05 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/58f1b55a-5b59-4eeb-960c-634758bda8c4)
![Screen Shot 2019-01-07 at 2.10.18 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/09548b82-d7a6-4a91-a3a3-7b61d73390aa)
![Screen Shot 2019-01-07 at 2.10.28 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/b60c8d8f-028f-43dd-8351-09cf65059aa1)

**Comment by nathanstitt** [comment]
Those all look pretty ok to me, or at least they look as good as they do in Chrome and others.

@carlycurran ?

**Comment by carlycurran** [comment]
Firefox is the worst! 

Most are fixed. Here are 4 that are still off: 

![Screen Shot 2019-01-15 at 12.35.13 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/fb663ea4-62ea-47ef-9fc9-ca7971a8ae60)

![Screen Shot 2019-01-15 at 12.35.20 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/e16ab78a-c55c-471d-a86d-ea466b3dc479)

![Screen Shot 2019-01-15 at 12.35.27 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/3fb40d6f-968d-40bb-8614-bc75bd195a9b)

![Screen Shot 2019-01-15 at 12.35.32 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/b25803cd-893c-46de-a6cc-03629c9a09b4)
