### ISSUE TITLE
Issues with feedback display on assignments - Question 1 feedback is skipped, remaining questions display the feedback

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#76]
_Instructions are in italics and can be deleted_
_1. Give the issue a descriptive title_
_2. Add a label: bug | change_
_3. Pick the content template:_ 

_For a BUG include these headings:_

### Description
Issues with feedback display on assignments - Question 1 feedback is skipped

----------------
**Steps to Reproduce the bug or Details about Change:** 
Issue: 
Question 1 feedback is skipped - On answering first question, automatically moves to 2nd question without showing the feedback though the circles at the top is marked as right/wrong. We have to manually click the circle to see the feedback of Q1.  But for remaining questions, stays on the page for the student to review feedback until we hit Next button 

This issue occurs in following assignment scenarios:
1. HW Immediate Feedback - Student already crossed due date
2. HW Feedback after due date - Student already crossed due date
3. Read - Student already crossed due date
4. Read - Student has not crossed the due date

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [X] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [X] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [X] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)
I saw this issue multiple times, but when I went to take video i couldn't get this exact issue...but I am sure this issue happened

**Comment by nathanstitt** [comment]
fixed by https://github.com/openstax/tutor-js/pull/2415

**Comment by Malar-Natarajan** [comment]
Verified on QA
