### ISSUE TITLE
Highlight summary page displays in the order of highlight done vs. order of content in the book page

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#80]
_Instructions are in italics and can be deleted_
_1. Give the issue a descriptive title_
_2. Add a label: bug | change_
_3. Pick the content template:_ 

_For a BUG include these headings:_

### Description
Highlight summary page displays in the order of highlight done vs. order of content in the book page

----------------
**Steps to Reproduce the bug or Details about Change:** 
If I highlight the summary section first and then the intro part then it displays in the same order as it was highlighted. Issue exists for both reading & reference view.

Expected result: The summary page should display in the order of book content

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [X] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [X] ` Chrome ` [ ] ` Firefox ` [X] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

![Screen Shot 2018-10-25 at 4.24.01 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/7542f589-0542-4e5c-a7db-3ca6b78e1c23)
![Screen Shot 2018-10-25 at 4.24.10 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/84e9b55b-d526-498c-9d04-4e23902a0a12)

**Comment by Malar-Natarajan** [comment]
Verified in QA

**Comment by Malar-Natarajan** [comment]
Reading still has some issue. Please see screenshot and the highlight summary page in this link:
https://tutor-qa.openstax.org/course/2369/task/365381 (student05)

Screenshot: https://drive.google.com/file/d/18P3Kw-FZmxuMw4bQeXD3tIVb3wBkoDb7/view?usp=sharing

The summary is at the top and others below that which means that the order of highlighting is recorded in the summary page. This was a new assignment created after the previous fix and the student was also enrolled after the previous fix.

**Comment by mmmcglone** [comment]
@carlycurran @Malar-Natarajan where is the video that shows this behavior?

And are we saying that the summary page displays the highlights and notes in content order in there reference view but in the order in which students highlighting in a reading assignment? 

So for example, if I was a student in a reading assignment and I made highlights chronologically in 3.4, 3.3, and 3.2 on the summary page they would show up in the order 3.4, 3.3, and then 3.2. But then if I went to the reference view and clicked on the summary page for chapter 3 I'd see the highlights as 3.2, 3.3, and then 3.4. 

Is that what we're saying is happening?

**Comment by Malar-Natarajan** [comment]
@mmmcglone 
The issue happens only when a section is subdivided into steps in a reading assignment. Eg. Section 3.4 reading is subdivided and has about 5 - 6 steps. So while reading if I highlight content in step 3 and then step 1, the summary page displays the step3 highlight at the top and then step 1 highlight. And this order gets transferred to Reference view as well

But I will test the example that you have mentioned, though I am sure it works properly as long as the sections are not subdivided.

@nathanstitt and @carlycurran can explain better if you have further questions. 

The video is in slack(#research-nsfhighlight channel 9.54 AM). I will upload here when I am in office. My wi-fi is just taking too long to upload.

**Comment by Malar-Natarajan** [comment]
Created new issue for the bug in reading
