### ISSUE TITLE
Scroll bar and continue/submit button are non-responsive when we select a task from the breadcrumbs in the reading assignment

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#83]
_Instructions are in italics and can be deleted_
_1. Give the issue a descriptive title_
_2. Add a label: bug | change_
_3. Pick the content template:_ 

_For a BUG include these headings:_

### Description
I was doing reading in firefox and at one point I went back few pages and it put me in a place where the up/down scroll went missing and the continue button did nothing. I reloaded the assignment from the dashboard - the continue button started working but the scroll bar was still missing. 
I am not able to recreate this issue though. But submitting this bug to see if developers can find anything from the code.

Update 11/06:
Able to replicate the issue in safari, firefox and chrome by trying to select a task from the breadcrumbs
----------------
**Steps to Reproduce the bug or Details about Change:** _What, Who, Where and How?_

1. Open a partial completed reading assignment
2. Go to the breadcrumbs and select any tile
3. The continue/SUbmit button and the scroll bars are non-responsive
4. Sometimes re-loading the assignment from the dashboard helps the Continue button but the scroll bars are still not working till we logout and login

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [X] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [X] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [X] ` Chrome ` [X] ` Firefox ` [X] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)
Refer video
Firefox:
https://drive.google.com/file/d/1J3hO3AIOeGinAjQsJxXDHzckgINpyUEH/view?usp=sharing

Chrome:
https://drive.google.com/file/d/1YKi05nOSFyLA2HAUXDVY6aapMar0Fdoo/view?usp=sharing

**Comment by nathanstitt** [comment]
We have some sentry errors for Firefox on tasks. I've attempted to replicate them but have also been unable to do so. If we can figure out how to replicate that'd be really good since it is affecting users

**Comment by Malar-Natarajan** [comment]
Updated the description and video

**Comment by Malar-Natarajan** [comment]
Verified in QA
