### ISSUE TITLE
REQUEST: Pull assessments using images on quadbase.

### ISSUE THREAD

**Issue by lwtchu** [openstax/tutor#86]
S'il vous plait. Please query all assessment using quadbase hosted images. The image source should have `quadbase.com` in the url 

Need this so we can reupload the images. Nice to have this by December?

**Comment by Dantemss** [comment]
The following exercises contain `quadbase.org` in some Stem in their latest version:

```
15424
15425
15427
15428
15430
15444
15472
15482
15488
15546
15547
15575
15588
15589
15614
15618
15620
15628
15661
15668
15872
15903
15954
16015
16266
16295
```
