### ISSUE TITLE
Convert test studies into study brains

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#89]
### Description
Tutor dev will translate research requirements for two test studies and code corresponding study brains

### Acceptance Criteria
Study brains work as specified be research team.

**Comment by nathanstitt** [comment]
we implemented the second one listed in https://docs.google.com/document/d/1-wp00P2Dl09sdGCkPJcGCfSU0X05qMxpXX27-GZHxd4/edit?usp=sharing

PR for that was: https://github.com/openstax/tutor-server/pull/1799
