### ISSUE TITLE
Accessibility: Allow user to hear answer choices 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#9]
# Description 
Allow user to hear answer choices again when answering a question, without listening to the whole problem again. Distinguish between answer choices and choice-level feedback. 

#Acceptance
User can hear answer choices without listening to whole problem and can distinguish between her answer and other feedback.

**Comment by nathanstitt** [comment]
Based on https://dequeuniversity.com/assets/html/jquery-summit/html5/slides/landmarks.html

* In JAWS, use the semi-colon key to jump to the next landmark, or use shift + semi-colon to go backward through landmarks.
* In NVDA, use the D key to jump to the next landmark, or use shift + D to go backward through landmarks.
* In VoiceOver, use CTRL + ALT + U to start the web rotor, then, if necessary, use the left or right arrow keys to display the list of landmarks (the rotor also displays lists of headings, links, and web spots), then use the down arrow key to navigate through the list of landmarks.

**Comment by Malar-Natarajan** [comment]
Retested in QA:

When an answer is submitted
selected choice a left parent incorrect answer right parent colon button unavailable
choice b left parent incorrect answer right parent colon button unavailable
choice c left parent incorrect answer right parent colon button unavailable
choice d left parent correct answer right parent colon button unavailable

When no choice is selected
choice a colon button
choice b colon button
choice c colon button
choice d colon button

When a choice is selected but not submitted
selected choice a colon button
choice b colon button
choice c colon button
choice d colon button

The landmarks still doesn't seem to work probably...(On hitting ";" key (on the zenhub issue, ";" was mentioned to identify landmarks):
There are no mouse hover elements on this page

**Comment by Malar-Natarajan** [comment]
From scrum: decided to stick to the first fix that cam with the code freeze and ignore the landmarks since we are still meeting the acceptance criteria.

**Comment by Malar-Natarajan** [comment]
Verified in QA
