### ISSUE TITLE
Link to "suggest a correction" for Biology still fills out form as Biology 1e

### ISSUE THREAD

**Issue by lwtchu** [openstax/tutor#91]
# Scenario 
When someone suggests a correction in tutor, it prefills the errata form with the book. It should be Biology 2e for everything now since we are no longer maintaining the first edition.

# Environment
Production

**Comment by marcjeannott** [comment]
I believe users using AP Bio are also having the field filled as Biology, and not "Biology for AP Courses".

**Comment by Malar-Natarajan** [comment]
@nathanstitt  Retested this in staging and the "Select a book" option is not prefilled with the  course book. So unable to retest this issue

**Comment by Malar-Natarajan** [comment]
Verified in Staging
