### ISSUE TITLE
Students going back to reading after due date = incorrectly marked as late work 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#92]
### Description

Students going back to review their completed reading assignments get marked as having late work, even if they were 100% complete on the due date. 

(Evidence in Niklas Manz' spreadsheets) 

Happens when a student clicks the "continue" button for some reading steps. 

We want a student to be able to:
1. go back and click through old work without affecting their grade
2. Finish an assignment late and have it marked late 

----------------
**Steps to Reproduce the bug or Details about Change:** _What, Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ X] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [X ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**
Gets incorrect grade
----------------
**Images or Screenshots** (_attach below_)

**Comment by Malar-Natarajan** [comment]
student08 in staging

**Comment by Malar-Natarajan** [comment]
Verified in QA
