### ISSUE TITLE
Reading step is not scrolling to the top of the page when the previous step is a question/answer

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#96]
_Instructions are in italics and can be deleted_
_1. Give the issue a descriptive title_
_2. Add a label: bug | change_
_3. Pick the content template:_ 

_For a BUG include these headings:_

### Description
Reading step is not scrolling to the top of the page when the previous step is a question/answer

----------------
**Steps to Reproduce the bug or Details about Change:** _What, Who, Where and How?_
1. Navigate through a reading
2. Answer a question in the assignment 
3. Click Continue where the next step of the reading is displayed
Issue: When we hit COntinue the reading in the next step is not scrolled to the top of the page. See video

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [X] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [X] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

https://drive.google.com/file/d/1VSqgUYpnaWxvunMgwE13fIq_cbaJ7JMa/view?usp=sharing

**Comment by nathanstitt** [comment]
i belive it happens when 1) you are in incognito mode so that images aren’t cached and 2) you navigate to a step that has either a large image or video at the top

 the fix will be to watch the images on the page and only scroll after they’re loaded

**Comment by gregfitch** [comment]
Verified on QA
