### ISSUE TITLE
Heading stylings are wonky especially if the heading is in long to fit only in two lines

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#97]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a BUG include these headings:_

**Describe the bug**
Heading stylings are wonky especially if the heading is in long to fit only in two lines

**To Reproduce**
1. Open a book in Reading or reference view and look for two line headings in the blue bar.
Issue: The headings are crossing the blue border and looks very clumsy

**Expected behavior**
The headings should be styled with correct spacing

**Screenshots**
![Screen Shot 2018-11-13 at 3.19.23 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/f4e40675-c74f-41e3-b3e6-88d53d7fa618)

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome, safari, firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Malar-Natarajan** [comment]
Good for the 11/20 release. But reopening the issue with updated screenshot since the padding for the two line heading need to be increased bit more as per discussion with @nathanstitt 

![Screen Shot 2018-11-16 at 4.28.40 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/7c1ba09d-05e5-4755-b0d2-49cd4c946471)

**Comment by nathanstitt** [comment]
additional tweaks were done in https://github.com/openstax/tutor-js/pull/2425 and it now appears better to me

**Comment by Malar-Natarajan** [comment]
Verified in QA
